import {useEffect,useRef,useState} from "react";
import {newIdempotencyKey,WorkbenchRequestError} from "../api/businessWorkspace";
import "./PreparedExecutionPanel.css";
type Resource={kind:string;identity:string;name:string;aggregateVersion:number;revision:{revisionId:string;digest:string;state:string;content:Record<string,unknown>};publishedRevisionId:string|null};
const names:Record<string,string>={skill:"技能",runtime:"运行配置",knowledge:"合成资料",agent:"Agent 职责定义"};
function path(target:string){const parts=target.split("|");if(parts.length!==3||!names[parts[0]])throw new Error("RESOURCE_REFERENCE_INVALID");return `/api/workbench/v1/prepared-resources/${parts.map(encodeURIComponent).join("/")}`}
async function read(target:string):Promise<Resource>{const response=await fetch(path(target),{credentials:"same-origin"});const body=await response.json();if(response.status===401)window.dispatchEvent(new Event("workbench-session-expired"));if(!response.ok)throw new WorkbenchRequestError(body.reasonCode??"RESOURCE_READ_FAILED",response.status);return body.result}
export function PreparedResourceReviewPanel({targets,csrfToken,contextKey,blocked,onBusy}:{targets:string[];csrfToken:string;contextKey:string;blocked:boolean;onBusy:(busy:boolean)=>void}){
 const [requestId,setRequestId]=useState("");
 const [resources,setResources]=useState<Resource[]>([]),[error,setError]=useState(""),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[checked,setChecked]=useState(false);const flight=useRef(false);const targetKey=JSON.stringify(targets);
 useEffect(()=>{let active=true;const list=JSON.parse(targetKey) as string[];Promise.all(list.map(read)).then(r=>{if(active)setResources(r)}).catch(e=>{if(active)setError(String(e))});return()=>{active=false}},[targetKey,contextKey]);
 async function requestAccess(){if(flight.current||blocked)return;flight.current=true;setBusy(true);onBusy(true);setError("");try{const owners:Record<string,[string,string]>={skill:["SKILL","skill-invocation:"],runtime:["RUNTIME_PROFILE","runtime-profile:"],knowledge:["KNOWLEDGE","knowledge:"],agent:["AGENT","agent:"]};const requestedGrants=targets.flatMap(target=>{const [kind,id,rev]=target.split("|");const [owner,prefix]=owners[kind];return ["READ_RESOURCE","REVIEW_PUBLISH_RESOURCE"].map(action=>({owner,action,resource:prefix+"prepared-resource:"+id+":"+rev}))});const storage=`324.resource-grants.${contextKey}.${targetKey}`,key=sessionStorage.getItem(storage)??newIdempotencyKey("resource-grants");sessionStorage.setItem(storage,key);const response=await fetch("/api/workbench/v1/authorization/grant-requests",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-CSRF-Token":csrfToken,"Idempotency-Key":key},body:JSON.stringify({schemaVersion:"exact-grant-request.v1",purpose:"S5_324_RESOURCE_REVIEW",requestedGrants,continuationIds:[]})});const body=await response.json();if(response.status===401)window.dispatchEvent(new Event("workbench-session-expired"));if(!response.ok)throw new WorkbenchRequestError(body.reasonCode??"RESOURCE_AUTHORIZATION_REQUEST_FAILED",response.status);setRequestId(body.requestId)}catch(e){setError(String(e))}finally{flight.current=false;setBusy(false);onBusy(false)}}
 async function refresh(){if(busy)return;setBusy(true);setError("");try{setResources(await Promise.all(targets.map(read)))}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function publish(){if(flight.current||blocked||!checked||!reason.trim())return;flight.current=true;setBusy(true);onBusy(true);setError("");try{for(let i=0;i<resources.length;i++){const r=resources[i];if(r.publishedRevisionId===r.revision.revisionId)continue;const storage=`324.resource.${contextKey}.${targets[i]}`,payload={expectedVersion:r.aggregateVersion,digest:r.revision.digest,reason};const fingerprint=JSON.stringify(payload),prior=JSON.parse(sessionStorage.getItem(storage)??"null") as {fingerprint:string;key:string}|null;const key=prior?.fingerprint===fingerprint?prior.key:newIdempotencyKey("resource-review");sessionStorage.setItem(storage,JSON.stringify({fingerprint,key}));const response=await fetch(path(targets[i])+"/review-publish",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-CSRF-Token":csrfToken},body:JSON.stringify({...payload,idempotencyKey:key})});const body=await response.json();if(response.status===401)window.dispatchEvent(new Event("workbench-session-expired"));if(!response.ok)throw new WorkbenchRequestError(body.reasonCode??"RESOURCE_PUBLICATION_UNKNOWN",response.status)}setResources(await Promise.all(targets.map(read)));setChecked(false)}catch(e){setError(String(e));setResources(await Promise.all(targets.map(read)).catch(()=>resources))}finally{flight.current=false;setBusy(false);onBusy(false)}}
 const pending=resources.filter(r=>r.publishedRevisionId!==r.revision.revisionId).length;
 return <section className="px-inline-card prepared-execution" aria-label="本次执行必要资源审核"><span className="px-eyebrow">本次执行必要资源</span><h2>核对精确修订并发布</h2><p>仅发布以下资源；不会确认方案、授予执行权限或启动任务。每项审核与发布分别留存正式记录。</p><div className="prepared-actions"><button disabled={busy||blocked} onClick={()=>void refresh()}>刷新资源状态</button>{resources.length===0&&<button disabled={busy||blocked} onClick={()=>void requestAccess()}>申请本批资源的精确读取与发布权限</button>}</div>{requestId&&<p>申请已登记：<code>{requestId}</code>。请由独立审批人通过<a href={`/authorization-admin?request=${encodeURIComponent(requestId)}`}>正式准入入口</a>核对并决定，随后返回刷新。</p>}{error&&<div className="prepared-gap" role="alert"><p>资源尚未就绪或权限不足。已保存记录保留，未完成部分不会自动重发。</p><code>{error}</code></div>}{resources.map(r=><details key={r.identity}><summary>{names[r.kind]} · {r.name} · {r.publishedRevisionId===r.revision.revisionId?"已发布":"待审核"}</summary><dl><dt>修订</dt><dd>{r.revision.revisionId}</dd><dt>摘要</dt><dd>{r.revision.digest}</dd></dl><pre>{JSON.stringify(r.revision.content,null,2)}</pre></details>)}{resources.length>0&&pending>0&&<><label className="px-field"><span>审核依据与限制</span><textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)} placeholder="确认用途、合成来源、只读边界和输入输出契约"/></label><label><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> 我已核对以上精确修订，仅同意本次隔离合成只读用途。</label><button className="px-primary-button" disabled={busy||blocked||!checked||!reason.trim()} onClick={()=>void publish()}>审核并发布待处理的 {pending} 项资源</button></>}{resources.length>0&&pending===0&&<p role="status">资源已发布。后续仍需方案修订确认、独立准入及明确启动。</p>}</section>;
}
