import {useEffect,useRef,useState} from "react";
import {preparedRequest,type ExecutionView} from "../api/preparedExecution";
import {newIdempotencyKey} from "../api/businessWorkspace";
import {formatTime} from "../journey/formatTime";
import "./PreparedExecutionPanel.css";
const labels:Record<string,string>={PENDING:"尚未启动",WAITING:"等待前序任务",READY:"依赖已满足",QUEUED:"已排队",RUNNING:"运行中",SUCCEEDED:"执行成功",FAILED:"执行失败",RETRY_WAIT:"等待重试决定",FINAL_FAILED:"最终失败",SKIPPED:"前序失败，已跳过",UNKNOWN:"证据不足或结果未知",RECOVERY_REQUIRED:"需要恢复核验",CANCEL_REQUESTED:"已请求取消，等待停止确认",CANCELLED:"已取消",SATISFIED:"符合标准",NOT_SATISFIED:"不符合标准",NOT_MEASURABLE:"不可度量",UNDETERMINED:"尚无法确定",NOT_SOLVED:"未解决",CONFIRMED_SOLVED:"已确认解决",NOT_CALLED:"尚未调用",READ_RESTRICTED:"调用记录读取受限",ADMITTED:"准入已通过",NOT_ADMITTED:"待独立准入",QUEUE:"任务已排队",STARTED:"任务已开始",REQUEST_CANCEL:"取消请求已保存",STOP_CONFIRMED:"停止已确认",FINALIZE_FAILURE:"已放弃重试",RETRY:"后继尝试已排队"};
const label=(value:string)=>labels[value]??value;
const terminal=new Set(["SUCCEEDED","FAILED","CANCELLED"]);
export function PreparedExecutionPanel({digest,problemId,csrfToken,contextKey,blocked,onBusy}:{digest:string;problemId:string;csrfToken:string;contextKey:string;blocked:boolean;onBusy:(busy:boolean)=>void}){
 const [original,setOriginal]=useState(false);const [view,setView]=useState<ExecutionView|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reason,setReason]=useState(""),[notice,setNotice]=useState("");const flight=useRef(false);
 useEffect(()=>{let active=true;preparedRequest<ExecutionView>(digest).then(v=>{if(active){if(v.preparation.semantics.target.problem.resource_id!==problemId)throw new Error("EXECUTION_PROBLEM_MISMATCH");setView(v)}}).catch(e=>{if(active)setError(String(e))});return()=>{active=false}},[digest,problemId,contextKey]);
 async function refresh(){if(flight.current)return;flight.current=true;setBusy(true);try{const v=await preparedRequest<ExecutionView>(digest);if(v.preparation.semantics.target.problem.resource_id!==problemId)throw new Error("EXECUTION_PROBLEM_MISMATCH");setView(v);setError("");setNotice("已读取正式记录，没有重新派发。")}catch(e){setError(String(e))}finally{flight.current=false;setBusy(false)}}
 async function command(action:string,payload:Record<string,unknown>={}){if(flight.current||blocked)return;flight.current=true;setBusy(true);onBusy(true);setError("");try{const storage=`324.command.${contextKey}.${digest}.${action}`,fingerprint=JSON.stringify(payload),prior=JSON.parse(sessionStorage.getItem(storage)??"null") as {fingerprint:string;key:string}|null;const key=prior?.fingerprint===fingerprint?prior.key:newIdempotencyKey(`prepared-${action}`);sessionStorage.setItem(storage,JSON.stringify({fingerprint,key}));await preparedRequest(digest,action,csrfToken,{...payload,idempotencyKey:key});setView(await preparedRequest<ExecutionView>(digest));setNotice("操作已保存并重新读回。")}catch(e){setError(String(e));setNotice("请先刷新核对实际状态。页面不会自动重发，原操作标识已保留。")}finally{flight.current=false;setBusy(false);onBusy(false)}}
 const p=view?.preparation,s=view?.progress,o=view?.outcome,tasks=(!original&&view?.taskTranslation?.tasks)||p?.semantics.tasks||[];
 return <section className="px-inline-card prepared-execution" aria-label="Native 执行与成果验收"><header><div><span className="px-eyebrow">隔离合成资料 · 只读执行</span><h2>执行与成果验收</h2></div><button disabled={busy} onClick={()=>void refresh()}>刷新正式状态</button></header>
 {error&&<div role="alert" className="prepared-gap"><strong>当前操作未能完成</strong><p>请核对精确权限、资源状态与版本。未读取到的内容不会视为空或成功。</p><code>{error}</code></div>}{notice&&<p role="status">{notice}</p>}{!view&&!error&&<p role="status">正在读取正式记录…</p>}
 {view&&p&&<><h3>{p.semantics.title}</h3><p>方案 v{p.plan_version} · {s?label(s.state):"尚未启动"}</p><p className="prepared-gap">执行成功、标准通过和问题解决分别记录。合成资料不能证明真实企业支出、节约额或业务问题已解决。</p>
 <div className="prepared-milestones"><span>需求已识别</span><span>候选已匹配</span><span>资源已绑定</span><span>{label(view.admission.state)}</span><span>{view.resourceUses.some(u=>u.state==="SUCCEEDED")?"已有实际调用记录":"实际调用尚待核验"}</span></div>
 {view.admission.state!=="ADMITTED"&&<div className="prepared-gap"><strong>执行准入存在缺口</strong><p>请完成独立准入或修复精确资源状态后刷新。</p><code>{view.admission.reason}</code></div>}
 {!view.executionStarted&&<button className="px-primary-button" disabled={busy||blocked||view.admission.state!=="ADMITTED"} onClick={()=>void command("start")}>启动本次只读执行</button>}
 <div className="prepared-progress"><strong>执行进度 {s?.tasks.filter(t=>t.state==="SUCCEEDED").length??0}/{p.semantics.tasks.length}</strong><progress max={p.semantics.tasks.length} value={s?.tasks.filter(t=>t.state==="SUCCEEDED").length??0}/></div>
 {view.taskTranslation&&<button onClick={()=>setOriginal(!original)}>{original?"显示中文译文":"查看方案原文"}</button>}<ol className="prepared-tasks">{tasks.map(t=>{const state=s?.tasks.find(x=>x.task_id===t.task_id),actor=p.participants.find(x=>x.task_id===t.task_id);return <li key={t.task_id}><header><h4>{t.title}</h4><span>{state?label(state.state):"尚未派发"}</span></header><p>{t.responsibility}</p><small>前序：{t.depends_on.map(id=>tasks.find(x=>x.task_id===id)?.title??id).join("、")||"无"} · 尝试 {state?.attempt_ordinal??0}</small><details><summary>分工与精确资源</summary><dl><dt>参与实例</dt><dd>{actor?.instance_id}</dd><dt>职责分配</dt><dd>{actor?.assignment_id}</dd><dt>数字员工</dt><dd>{actor?.definition.resource_id} / {actor?.definition.revision_id}</dd><dt>技能操作</dt><dd>{actor?.skill.operation} / {actor?.skill.reference.revision_id}</dd><dt>技能摘要</dt><dd>{actor?.skill.reference.digest}</dd><dt>运行配置</dt><dd>{actor?.profile.resource_id} / {actor?.profile.revision_id}</dd></dl>{state?.reason&&<code>{state.reason}</code>}</details>{state?.state==="RETRY_WAIT"&&<><button disabled={busy||blocked} onClick={()=>void command("retry",{taskId:t.task_id,expectedAttemptOrdinal:state.attempt_ordinal})}>核验准入并重试</button><button disabled={busy||blocked} onClick={()=>void command("decline-retry",{taskId:t.task_id,expectedAttemptOrdinal:state.attempt_ordinal})}>放弃重试并保留失败</button></>}</li>})}</ol>
 {s&&!terminal.has(s.state)&&!s.cancellation_request_id&&<button disabled={busy||blocked} onClick={()=>void command("cancel")}>请求取消本次执行</button>}{s?.cancellation_request_id&&<p>取消请求已保存，等待停止依据；未知结果不会自动当作已停止。</p>}
 <div className="prepared-columns"><section><h3>产物与交付</h3>{!view.artifacts.length&&<p>尚无已持久化的产物。</p>}{view.artifacts.map(a=><details key={a.artifact_id}><summary>{tasks.find(t=>t.task_id===a.task_id)?.title??a.task_id} · {a.bytes} 字节</summary><time dateTime={a.created_at}>{formatTime(a.created_at)}</time><p><code>{a.digest}</code></p>{a.contentAccess==="AUTHORIZED"?<pre>{a.content}</pre>:<p>产物内容需要独立读取权限。</p>}</details>)}<h3>实际资源调用</h3>{!view.resourceUses.length&&<p>尚无调用记录。</p>}{view.resourceUses.map(u=><details key={u.resourceUseId}><summary>{label(u.state)}</summary><code>{u.resourceUseId}</code></details>)}</section>
 <section><h3>标准评价与人工决定</h3>{!o?<><p>按原完成标准精确修订核对产物；证据不足不记为通过。</p><button disabled={busy||blocked||!s||!terminal.has(s.state)} onClick={()=>void command("evaluate")}>按标准形成评价</button></>:<><strong>业务结果：{label(o.businessResolution)}</strong><ul>{o.evaluation.results.map(r=><li key={r.criterionRevisionId}><p>{label(r.result)} · {r.reason==="HUMAN_DISAGREEMENT"?"人工已提出异议":"核对原标准与合成资料适用范围"}</p><details><summary>标准与证据关联</summary><code>{r.criterionRevisionId}</code><p>{r.criterionDigest}</p><p>关联产物 {r.artifactIds.length} 项</p></details></li>)}</ul><p>{o.confirmationId?"人工决定已保存，历史评价与产物保留。":"待有权限的 Human 作正式决定。"}</p><label className="px-field"><span>验收意见</span><textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="说明已核对的产物、适用范围与后续限制"/></label><div className="px-card-actions">{[["ACKNOWLEDGE_UNDETERMINED","确认限制与待解决事项"],["DISAGREE","记录异议"]].map(([decision,title])=><button key={decision} disabled={busy||blocked||!reason.trim()} onClick={()=>void command("human-decision",{evaluationId:o.evaluation.evaluationId,evaluationDigest:o.evaluationDigest,expectedVersion:o.version,decision,reason})}>{title}</button>)}</div><small>本次合成执行不提供“真实业务问题已解决”的确认。</small></>}</section></div>
 <details><summary>关键事件与方案关联</summary><dl><dt>Plan</dt><dd>{p.plan_id} / v{p.plan_version}</dd><dt>Approval</dt><dd>{p.approval_id}</dd><dt>方案摘要</dt><dd>{p.plan_digest}</dd><dt>准备摘要</dt><dd>{digest}</dd><dt>合成来源</dt><dd>{p.source_snapshot.resource_id} / {p.source_snapshot.revision_id}</dd></dl><ol>{view.events.map(e=><li key={e.version}><time dateTime={e.created_at}>{formatTime(e.created_at)}</time> · {label(e.record.action)} · {e.record.task_id??"本次执行"}</li>)}</ol></details></>}
 </section>;
}
