import {Fragment,useCallback,useEffect,useRef,useState} from "react";
import {useSearchParams} from "react-router-dom";
import {
  WorkbenchRequestError,beginDraftAssistance,cancelDraftAssistance,createBusinessProblem,inspectGrantRequest,linkDraftAssistanceProblem,listBusinessProblems,newIdempotencyKey,observeDraftAssistance,rejectDraftAssistance,resubmitDraftAssistance,
  readBusinessProblem,readCriteriaSets,readProblemCriteria,readWorkbenchSession,reviseBusinessProblem,
  writeCriteriaSet,writeCriterion,submitSuccessCriteriaGrantRequest,
  submitProblemReadGrantRequest,type BusinessProblemDetail,type BusinessProblemRevision,type CriteriaSetRevision,
  type CriterionRevision,type DraftAssistanceResult,type ExactGrantRequest,type GrantRequestStatus,type ProblemCreatorContinuation,type WorkbenchSession,
} from "../api/businessWorkspace";
import {ConversationComposer,ConversationFrame,DraftCard,SystemMessage,UserMessage} from "./ProblemConversation";
import {DraftAssistanceCard} from "./DraftAssistanceCard";
import {suggestProblemTitle,type DraftTurn,type ProblemDraft} from "./problemConversationModel";
import {ProblemTaskSummary} from "./ProblemTaskSummary";
import {SavedCriteriaHistory,SuccessCriterionCard} from "./SuccessCriterionCard";
import {WorkbenchErrorNotice,type WorkbenchOperation} from "./WorkbenchErrorNotice";
import {createSuccessCriterionTurn,type CriteriaSetBase,type SuccessCriterionDraft,type SuccessCriterionTurn} from "./successCriteriaModel";

type Workspace={detail:BusinessProblemDetail;criteria:CriterionRevision[];sets:CriteriaSetRevision[];criteriaReadable:boolean};
type RecordDraft=ProblemDraft;
type AuthorizationState={continuation?:ProblemCreatorContinuation;request?:GrantRequestStatus;requestKey?:string};
type CriteriaAuthorizationState={stage:"WORKSPACE"|"CRITERION"|"SET";requestKey:string;grants:ExactGrantRequest[];request?:GrantRequestStatus};
type StoredAuthorization={contextKey:string;state:AuthorizationState};
type Failure={error:unknown;operation:WorkbenchOperation;mutation?:boolean};
type ComposerTarget="NEW"|"SUPPLEMENT"|"DRAFT"|"FORMAL"|"CRITERION"|"CRITERION_EDIT";
type CreatePayload={title:string;description:string;ownerId:string};
type PendingCreate={payload:CreatePayload;key:string;turnId:string;version:number;epoch:number};
type PendingProblemLink={invocationId:string;problemId:string;problemRevisionId:string;problemDigest:string;contextKey:string};
type Supplement={id:string;text:string;assisted?:boolean};
type ActiveAssistance={result:DraftAssistanceResult;key:string;content:string;originalText:string;contextKey:string};
const EMPTY_RECORD:RecordDraft={title:"",description:""};
const latest=<T extends {revision:number}>(values:T[])=>[...values].sort((a,b)=>b.revision-a.revision)[0];
const readable=(value:string)=>new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",timeZoneName:"short"}).format(new Date(value));
const storageKey=(problemId:string)=>`impl299.authorization.${problemId}`;

function storedAuthorization(problemId:string,contextKey:string):AuthorizationState{try{const stored=JSON.parse(sessionStorage.getItem(storageKey(problemId))??"{}") as Partial<StoredAuthorization>;return stored.contextKey===contextKey&&stored.state?stored.state:{}}catch{return {}}}
function persistAuthorization(problemId:string,contextKey:string,state:AuthorizationState){sessionStorage.setItem(storageKey(problemId),JSON.stringify({contextKey,state} satisfies StoredAuthorization))}
const sessionKey=(value:WorkbenchSession)=>`${value.principal.principalId}\u0000${value.principal.tenantId}\u0000${value.principal.securityDomain}`;
const uncertain=(error:unknown)=>!(error instanceof WorkbenchRequestError)||error.status===0||error.status===503;

export function ProblemWorkspacePage(){
  const [params,setParams]=useSearchParams();
  const [session,setSession]=useState<WorkbenchSession|null>(null),[problems,setProblems]=useState<BusinessProblemRevision[]>([]),[workspace,setWorkspace]=useState<Workspace|null>(null);
  const [createdRevision,setCreatedRevision]=useState<BusinessProblemRevision|null>(null),[authorization,setAuthorization]=useState<AuthorizationState>({});
  const [recordDraft,setRecordDraft]=useState<RecordDraft>(EMPTY_RECORD),[recordSaved,setRecordSaved]=useState<RecordDraft>(EMPTY_RECORD),[recordEditing,setRecordEditing]=useState(false);
  const [turn,setTurn]=useState<DraftTurn|null>(null),[composer,setComposer]=useState(""),[composerTarget,setComposerTarget]=useState<ComposerTarget>("NEW");
  const [assistance,setAssistance]=useState<ActiveAssistance|null>(null);
  const [criterionTurn,setCriterionTurn]=useState<SuccessCriterionTurn|null>(null),[criterionReturn,setCriterionReturn]=useState(""),[criteriaAuthorization,setCriteriaAuthorization]=useState<CriteriaAuthorizationState|null>(null);
  const [supplements,setSupplements]=useState<Supplement[]>([]),[supplementReturn,setSupplementReturn]=useState("");
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[failure,setFailure]=useState<Failure|null>(null),[criteriaFailure,setCriteriaFailure]=useState<Failure|null>(null),[loginRequired,setLoginRequired]=useState(false),[submitted,setSubmitted]=useState(false),[contextNotice,setContextNotice]=useState("");
  const [pendingCreate,setPendingCreate]=useState<PendingCreate|null>(null);
  const [pendingProblemLink,setPendingProblemLink]=useState<PendingProblemLink|null>(null);
  const epoch=useRef(0),loadSequence=useRef(0),idempotency=useRef<Record<string,{fingerprint:string;key:string}>>({}),mutationFlight=useRef(false),sessionRef=useRef<WorkbenchSession|null>(null),initialProblem=useRef(params.get("problem")),initialRequest=useRef(params.get("request")),selectedId=params.get("problem");
  const recordDirty=JSON.stringify(recordDraft)!==JSON.stringify(recordSaved),draftDirty=turn!==null&&turn.phase!=="CANCELLED"&&turn.phase!=="CREATED",criterionDirty=criterionTurn!==null&&criterionTurn.phase!=="CANCELLED"&&criterionTurn.phase!=="SAVED",supplementDirty=supplements.length>0||Boolean(composer.trim());

  function operationKey(operation:string,payload:unknown){const fingerprint=JSON.stringify(payload),current=idempotency.current[operation];if(current?.fingerprint===fingerprint)return current.key;const key=newIdempotencyKey(operation);idempotency.current[operation]={fingerprint,key};return key}
  function completeOperation(...operations:string[]){for(const operation of operations)delete idempotency.current[operation]}
  const applyProblem=useCallback((detail:BusinessProblemDetail,sets:CriteriaSetRevision[]=[],criteria:CriterionRevision[]=[],criteriaReadable=true)=>{
    const problemRevision=detail.revisions.find(item=>item.revision_id===detail.problem.current_revision_id)??latest(detail.revisions);
    const next={title:problemRevision?.title??"",description:problemRevision?.description??""};
    setWorkspace({detail,sets,criteria,criteriaReadable});setCreatedRevision(problemRevision??null);setRecordDraft(next);setRecordSaved(next);setRecordEditing(false);setFailure(null);setSubmitted(false);
  },[]);
  const loadWorkspace=useCallback(async(problemId:string)=>{const context=epoch.current,sequence=++loadSequence.current,detail=await readBusinessProblem(problemId);if(context===epoch.current&&sequence===loadSequence.current)applyProblem(detail,[],[],false);try{const [sets,criteria]=await Promise.all([readCriteriaSets(problemId),readProblemCriteria(problemId)]);if(context===epoch.current&&sequence===loadSequence.current){applyProblem(detail,sets.revisions,criteria.revisions,true);setCriteriaFailure(null)}}catch(error){if(context===epoch.current&&sequence===loadSequence.current)setCriteriaFailure({error,operation:"恢复工作区"})}},[applyProblem]);
  const reloadList=useCallback(async(expectedEpoch=epoch.current)=>{const listed=await listBusinessProblems();if(expectedEpoch===epoch.current)setProblems(listed.problems)},[]);
  const recoverRequest=useCallback(async(problemId:string,requestId:string,expectedEpoch=epoch.current)=>{const current=sessionRef.current;if(!current)return;const currentContext=sessionKey(current),request=await inspectGrantRequest(requestId);if(expectedEpoch!==epoch.current||sessionKey(sessionRef.current??current)!==currentContext)return;const next={...storedAuthorization(problemId,currentContext),request};setAuthorization(next);persistAuthorization(problemId,currentContext,next);if(request.state==="APPROVED"){setWorkspace(null);await loadWorkspace(problemId)}},[loadWorkspace]);

  useEffect(()=>{let active=true;(async()=>{try{
    const current=await readWorkbenchSession();if(!active)return;sessionRef.current=current;setSession(current);
    const listed=await listBusinessProblems();if(!active)return;setProblems(listed.problems);
    const problemId=initialProblem.current;if(!problemId)return;
    setCreatedRevision(listed.problems.find(item=>item.business_problem_id===problemId)??null);setComposerTarget("SUPPLEMENT");
    const currentContext=sessionKey(current),stored=storedAuthorization(problemId,currentContext),requestedId=initialRequest.current,boundRequestId=requestedId&&(requestedId===stored.request?.requestId||requestedId===stored.continuation?.requestId)?requestedId:stored.request?.requestId;setAuthorization(stored);
    if(requestedId&&!boundRequestId)setContextNotice("链接中的申请编号不属于当前会话与问题，已忽略该授权状态。");
    if(boundRequestId)await recoverRequest(problemId,boundRequestId);else if(!stored.continuation)await loadWorkspace(problemId);
  }catch(error){if(active){setLoginRequired(error instanceof WorkbenchRequestError&&error.status===401);setFailure({error,operation:"恢复工作区"})}}finally{if(active)setLoading(false)}})();return()=>{active=false;epoch.current+=1}},[loadWorkspace,recoverRequest]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(recordDirty||draftDirty||criterionDirty||supplementDirty){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[criterionDirty,draftDirty,recordDirty,supplementDirty]);
  useEffect(()=>{if(!session)return;let active=true,controller:AbortController|null=null;
    const refresh=()=>{controller?.abort();controller=new AbortController();readWorkbenchSession(controller.signal).then(next=>{if(!active)return;const previous=sessionRef.current;if(previous&&sessionKey(previous)!==sessionKey(next)){epoch.current+=1;idempotency.current={};setParams({});setProblems([]);setWorkspace(null);setCreatedRevision(null);setAuthorization({});setRecordDraft(EMPTY_RECORD);setRecordSaved(EMPTY_RECORD);setRecordEditing(false);setTurn(null);setCriterionTurn(null);setCriteriaAuthorization(null);setPendingCreate(null);setPendingProblemLink(null);setComposer("");setComposerTarget("NEW");setSupplements([]);setSupplementReturn("");setCriterionReturn("");setFailure(null);setCriteriaFailure(null);if(!mutationFlight.current)setBusy(false);setContextNotice("可信身份或安全范围已经变化。原草稿、消息、授权接续、页内补充和在途响应已隔离，请在当前上下文重新开始。")}sessionRef.current=next;setSession(next);setLoginRequired(false)}).catch(error=>{if(active&&error?.name!=="AbortError"&&error instanceof WorkbenchRequestError&&error.status===401){epoch.current+=1;setParams({});setProblems([]);setWorkspace(null);setCreatedRevision(null);setAuthorization({});setRecordDraft(EMPTY_RECORD);setRecordSaved(EMPTY_RECORD);setRecordEditing(false);setTurn(null);setCriterionTurn(null);setCriteriaAuthorization(null);setPendingCreate(null);setPendingProblemLink(null);setComposer("");setComposerTarget("NEW");setSupplements([]);setSupplementReturn("");setCriterionReturn("");setFailure(null);setCriteriaFailure(null);if(!mutationFlight.current)setBusy(false);setLoginRequired(true)}})};
    const visible=()=>{if(document.visibilityState==="visible")refresh()};document.addEventListener("visibilitychange",visible);window.addEventListener("focus",refresh);return()=>{active=false;controller?.abort();document.removeEventListener("visibilitychange",visible);window.removeEventListener("focus",refresh)};
  },[session,setParams]);

  function applyAssistance(next:ActiveAssistance){
    setAssistance(next);const result=next.result;
    if(result.resultKind==="DRAFT_READY"&&result.draft){setTurn({id:result.invocationId,originalText:next.originalText,draft:result.draft,version:result.turnVersion,phase:"DRAFT",source:result.transport==="SYNTHETIC"?"AI_SYNTHETIC":"AI_PROVIDER"});setComposerTarget("SUPPLEMENT")}
    else if(result.resultKind==="NEEDS_CLARIFICATION")setComposerTarget("SUPPLEMENT");
  }
  async function requestAssistance(value:string,supplement=false){
    if(!session||busy)return;const token=epoch.current,currentSession=sessionKey(session),previous=assistance;
    const content=supplement&&previous?`${previous.content}\n\n用户补充：${value}`:value;
    const key=newIdempotencyKey("draft-assistance");setBusy(true);setFailure(null);
    try{const result=await beginDraftAssistance(session.csrfToken,{idempotencyKey:key,content,...(supplement&&previous?{parentContextId:previous.result.contextId,parentTurnId:previous.result.turnId,expectedParentVersion:previous.result.turnVersion,predecessorInvocationId:previous.result.invocationId}:{})});if(token!==epoch.current||sessionKey(sessionRef.current??session)!==currentSession)return;applyAssistance({result,key,content,originalText:previous?.originalText??value,contextKey:currentSession});setComposer("")}
    catch(error){if(token===epoch.current)setFailure({error,operation:"请求 AI 草稿辅助",mutation:true})}finally{if(token===epoch.current)setBusy(false)}
  }
  async function refreshAssistance(){if(!session||!assistance||busy)return;const token=epoch.current;setBusy(true);setFailure(null);try{const result=await resubmitDraftAssistance(session.csrfToken,assistance.result.invocationId,{idempotencyKey:assistance.key,content:assistance.content});if(token===epoch.current)applyAssistance({...assistance,result})}catch(error){if(token===epoch.current)setFailure({error,operation:"刷新 AI 草稿辅助",mutation:true})}finally{if(token===epoch.current)setBusy(false)}}
  async function observeAssistance(){if(!session||!assistance||busy)return;setBusy(true);try{const result=await observeDraftAssistance(session.csrfToken,assistance.result.invocationId);applyAssistance({...assistance,result})}catch(error){setFailure({error,operation:"观察 AI 原调用"})}finally{setBusy(false)}}
  async function cancelAssistance(){if(!session||!assistance||busy)return;setBusy(true);try{const result=await cancelDraftAssistance(session.csrfToken,assistance.result.invocationId);setAssistance({...assistance,result});if(turn)setTurn({...turn,phase:"CANCELLED"})}catch(error){setFailure({error,operation:"取消 AI 草稿辅助",mutation:true})}finally{setBusy(false)}}
  async function rejectAssistance(){if(!session||!assistance||busy)return;setBusy(true);try{const result=await rejectDraftAssistance(session.csrfToken,assistance.result.invocationId);setAssistance({...assistance,result});if(turn)setTurn({...turn,phase:"CANCELLED"})}catch(error){setFailure({error,operation:"拒绝 AI 草稿",mutation:true})}finally{setBusy(false)}}
  async function repairProblemLink(){
    if(!session||!assistance||!pendingProblemLink||busy||pendingProblemLink.contextKey!==sessionKey(session))return;
    const pending=pendingProblemLink,token=epoch.current,currentSession=sessionKey(session);setBusy(true);setFailure(null);
    try{const linked=await linkDraftAssistanceProblem(session.csrfToken,pending.invocationId,{problemId:pending.problemId,problemRevisionId:pending.problemRevisionId,problemDigest:pending.problemDigest});if(token===epoch.current&&sessionKey(sessionRef.current??session)===currentSession){setAssistance({...assistance,result:linked});setPendingProblemLink(null)}}
    catch(error){if(token===epoch.current)setFailure({error,operation:"补记草稿来源",mutation:true})}
    finally{if(token===epoch.current)setBusy(false)}
  }
  function manualFallback(){const value=assistance?.content??composer.trim();if(!value)return;setTurn({id:crypto.randomUUID(),originalText:assistance?.originalText??value,draft:{title:suggestProblemTitle(value),description:value},version:(assistance?.result.turnVersion??0)+1,phase:"DRAFT",source:"MANUAL"});setComposer("");setComposerTarget("SUPPLEMENT");setFailure(null)}

  async function sendComposer(){
    const value=composer.trim();if(!value||(busy&&composerTarget!=="SUPPLEMENT"))return;
    if(composerTarget==="NEW"){await requestAssistance(value)}
    else if(composerTarget==="SUPPLEMENT"&&assistance?.result.resultKind==="NEEDS_CLARIFICATION"&&!turn){setSupplements(current=>[...current,{id:crypto.randomUUID(),text:value,assisted:true}]);await requestAssistance(value,true)}
    else if(composerTarget==="SUPPLEMENT"){setSupplements(current=>[...current,{id:crypto.randomUUID(),text:value}]);setComposer("")}
    else if(composerTarget==="DRAFT"&&turn){setTurn({...turn,draft:{...turn.draft,description:value},version:turn.version+1,phase:"DRAFT"});setComposer(supplementReturn);setSupplementReturn("");setComposerTarget("SUPPLEMENT");setFailure(null)}
    else if(composerTarget==="FORMAL"){setRecordDraft(current=>({...current,description:value}));setRecordEditing(true);setComposer(supplementReturn);setSupplementReturn("");setComposerTarget("SUPPLEMENT");setFailure(null)}
    else if(composerTarget==="CRITERION"&&selectedId&&canonical){setCriterionTurn(current=>createSuccessCriterionTurn(selectedId,canonical.revision_id,value,current?.baseSet));setComposer(criterionReturn);setCriterionReturn("");setComposerTarget("SUPPLEMENT");setFailure(null)}
    else if(composerTarget==="CRITERION_EDIT"&&criterionTurn){setCriterionTurn({...criterionTurn,draft:{...criterionTurn.draft,text:value},version:criterionTurn.version+1,phase:"DRAFT"});setComposer(criterionReturn);setCriterionReturn("");setComposerTarget("SUPPLEMENT");setFailure(null)}
  }
  function updateTurn(draft:ProblemDraft){if(turn&&turn.phase==="EDITING"&&composerTarget==="SUPPLEMENT")setTurn({...turn,draft,version:turn.version+1})}
  function editTurnFields(){if(!turn||composerTarget!=="SUPPLEMENT")return;setTurn({...turn,phase:"EDITING"})}
  function finishTurnFields(){if(!turn||turn.phase!=="EDITING")return;setTurn({...turn,phase:"DRAFT"})}
  function editTurnWithComposer(){if(!turn)return;setTurn({...turn,phase:"DRAFT"});setSupplementReturn(composer);setComposer(turn.draft.description);setComposerTarget("DRAFT")}
  function cancelComposerEdit(){if(composerTarget==="FORMAL")setRecordEditing(true);setComposer(composerTarget==="CRITERION"||composerTarget==="CRITERION_EDIT"?criterionReturn:supplementReturn);setCriterionReturn("");setSupplementReturn("");setComposerTarget("SUPPLEMENT")}
  async function cancelTurn(){if(!turn)return;if(assistance&&turn.source!=="MANUAL"){await rejectAssistance();return}setTurn({...turn,phase:"CANCELLED"});setPendingCreate(null);completeOperation("create-problem");setComposerTarget("NEW");setFailure(null)}
  async function select(problemId:string){if((recordDirty||draftDirty||criterionDirty||supplementDirty)&&!window.confirm("当前页面有未保存修改或页内补充。确定放弃并切换吗？"))return;const token=++epoch.current,currentContext=session?sessionKey(session):"",stored=currentContext?storedAuthorization(problemId,currentContext):{};setParams({problem:problemId});setBusy(true);setFailure(null);setCriteriaFailure(null);setContextNotice("");setWorkspace(null);setCreatedRevision(problems.find(item=>item.business_problem_id===problemId)??null);setAuthorization(stored);setTurn(null);setCriterionTurn(null);setCriteriaAuthorization(null);setPendingCreate(null);setPendingProblemLink(null);setComposer("");setComposerTarget("SUPPLEMENT");setSupplements([]);setSupplementReturn("");setCriterionReturn("");try{if(stored.request)await recoverRequest(problemId,stored.request.requestId,token);else if(!stored.continuation)await loadWorkspace(problemId)}catch(error){if(token===epoch.current)setFailure({error,operation:"打开业务问题"})}finally{if(token===epoch.current)setBusy(false)}}
  async function create(recover=false){
    if(!session||!turn||mutationFlight.current||(recover&&!pendingCreate)||(!recover&&(!turn.draft.title.trim()||!turn.draft.description.trim())))return;
    const token=epoch.current,currentSession=sessionKey(session);
    const payload:CreatePayload=recover&&pendingCreate?pendingCreate.payload:{title:turn.draft.title.trim(),description:turn.draft.description.trim(),ownerId:session.principal.principalId};
    const command:PendingCreate=recover&&pendingCreate?pendingCreate:{payload,key:operationKey("create-problem",payload),turnId:turn.id,version:turn.version,epoch:token};
    if(command.epoch!==token||command.turnId!==turn.id||sessionKey(session)!==currentSession)return;
    mutationFlight.current=true;setPendingCreate(command);setTurn({...turn,phase:"SUBMITTING"});setBusy(true);setFailure(null);
    try{
      const created=await createBusinessProblem(session.csrfToken,{...command.payload,idempotencyKey:command.key});
      if(token!==epoch.current||sessionKey(sessionRef.current??session)!==currentSession)return;
      completeOperation("create-problem");const problemId=created.revision.business_problem_id,next:AuthorizationState={continuation:created.creatorContinuation};
      setPendingCreate(null);setTurn(current=>current&&current.id===command.turnId?{...current,draft:{title:command.payload.title,description:command.payload.description},phase:"CREATED"}:current);setCreatedRevision(created.revision);setAuthorization(next);persistAuthorization(problemId,currentSession,next);setParams({problem:problemId});
      try{await reloadList(token)}catch(error){if(token===epoch.current)setFailure({error,operation:"恢复工作区"})}
      if(created.creatorContinuation.requestId){try{await recoverRequest(problemId,created.creatorContinuation.requestId,token);if(token===epoch.current)setParams({problem:problemId,request:created.creatorContinuation.requestId})}catch(error){if(token===epoch.current)setFailure({error,operation:"恢复授权状态"})}}
      if(assistance&&turn.source!=="MANUAL"&&assistance.result.invocationId===command.turnId){const pending={invocationId:assistance.result.invocationId,problemId,problemRevisionId:created.revision.revision_id,problemDigest:created.revision.digest,contextKey:currentSession};setPendingProblemLink(pending);try{const linked=await linkDraftAssistanceProblem(session.csrfToken,pending.invocationId,{problemId:pending.problemId,problemRevisionId:pending.problemRevisionId,problemDigest:pending.problemDigest});if(token===epoch.current){setAssistance({...assistance,result:linked});setPendingProblemLink(null)}}catch(error){if(token===epoch.current)setFailure({error,operation:"补记草稿来源",mutation:true})}}
    }catch(error){if(token===epoch.current){if(uncertain(error))setTurn(current=>current&&current.id===command.turnId?{...current,phase:"UNKNOWN"}:current);else{setPendingCreate(null);setTurn(current=>current&&current.id===command.turnId?{...current,phase:"DRAFT"}:current)}setFailure({error,operation:"创建业务问题",mutation:true})}}finally{mutationFlight.current=false;setBusy(false)}
  }
  async function requestAccess(){const continuation=authorization.continuation;if(!session||!selectedId||!continuation?.continuationId||continuation.state!=="AVAILABLE"||mutationFlight.current)return;const token=epoch.current,problemId=selectedId,currentSession=sessionKey(session),requestKey=authorization.requestKey??newIdempotencyKey("request-problem-read"),pending={...authorization,requestKey};mutationFlight.current=true;setAuthorization(pending);persistAuthorization(problemId,currentSession,pending);setBusy(true);setFailure(null);try{const request=await submitProblemReadGrantRequest(session.csrfToken,continuation.continuationId,requestKey);if(token!==epoch.current||sessionKey(sessionRef.current??session)!==currentSession)return;const next={...pending,request};setAuthorization(next);persistAuthorization(problemId,currentSession,next);setParams({problem:problemId,request:request.requestId})}catch(error){if(token===epoch.current)setFailure({error,operation:"申请查看权限",mutation:true})}finally{mutationFlight.current=false;setBusy(false)}}
  async function refreshAuthorization(){
    if(!selectedId||!authorization.request||busy)return;
    const token=epoch.current,problemId=selectedId,focusAtStart=document.activeElement instanceof HTMLElement?document.activeElement:null;
    let userMovedFocus=false;
    const observeFocus=(event:FocusEvent)=>{if(event.target!==focusAtStart)userMovedFocus=true};
    document.addEventListener("focusin",observeFocus,true);setBusy(true);setFailure(null);
    try{await recoverRequest(problemId,authorization.request.requestId,token)}catch(error){if(token===epoch.current)setFailure({error,operation:"刷新授权状态"})}finally{
      document.removeEventListener("focusin",observeFocus,true);
      if(token===epoch.current){setBusy(false);window.setTimeout(()=>{if(token===epoch.current&&!userMovedFocus&&focusAtStart&&document.contains(focusAtStart))focusAtStart.focus({preventScroll:true})},0)}
    }
  }
  async function saveProblem(){setSubmitted(true);if(!session||!workspace||mutationFlight.current||!recordDraft.title.trim()||!recordDraft.description.trim())return;const token=epoch.current,currentSession=sessionKey(session),problemId=workspace.detail.problem.business_problem_id,current=workspace.detail.revisions.find(item=>item.revision_id===workspace.detail.problem.current_revision_id)??latest(workspace.detail.revisions);if(!current)return;const payload={predecessorRevisionId:current.revision_id,expectedVersion:workspace.detail.problem.aggregate_version,title:recordDraft.title.trim(),description:recordDraft.description.trim(),ownerId:current.owner_id};mutationFlight.current=true;setBusy(true);setFailure(null);try{await reviseBusinessProblem(session.csrfToken,problemId,{...payload,idempotencyKey:operationKey("revise-problem",payload)});if(token!==epoch.current||sessionKey(sessionRef.current??session)!==currentSession)return;completeOperation("revise-problem");await reloadList(token);if(token===epoch.current)await loadWorkspace(problemId)}catch(error){if(token===epoch.current)setFailure({error,operation:"保存业务问题",mutation:true})}finally{mutationFlight.current=false;setBusy(false)}}
  function startFormalEdit(){if(composerTarget!=="SUPPLEMENT")return;setRecordEditing(true)}
  function startFormalComposerEdit(){setRecordEditing(false);setSupplementReturn(composer);setComposer(recordDraft.description);setComposerTarget("FORMAL")}
  function cancelFormalEdit(){setRecordDraft(recordSaved);setRecordEditing(false);setFailure(null);setSubmitted(false)}
  function startNew(){if((recordDirty||draftDirty||criterionDirty||supplementDirty)&&!window.confirm("放弃未保存内容和页内补充并新建？"))return;epoch.current+=1;idempotency.current={};setParams({});setWorkspace(null);setCreatedRevision(null);setAuthorization({});setRecordDraft(EMPTY_RECORD);setRecordSaved(EMPTY_RECORD);setRecordEditing(false);setTurn(null);setCriterionTurn(null);setCriteriaAuthorization(null);setPendingCreate(null);setPendingProblemLink(null);setComposer("");setComposerTarget("NEW");setSupplements([]);setSupplementReturn("");setCriterionReturn("");setFailure(null);setCriteriaFailure(null);setContextNotice("");setSubmitted(false)}

  function startCriterion(text="",baseSet?:CriteriaSetBase){if(!selectedId||!canonical||composerTarget!=="SUPPLEMENT"||criterionTurn&&criterionTurn.phase!=="CANCELLED"&&criterionTurn.phase!=="SAVED")return;setCriteriaAuthorization(null);setCriterionReturn(text&&text===composer?"":composer);setComposer(text);setCriterionTurn(baseSet?createSuccessCriterionTurn(selectedId,canonical.revision_id,"",baseSet):null);setComposerTarget("CRITERION")}
  function reviseCriterion(baseSet:CriteriaSetBase,criterion:CriterionRevision){if(!selectedId||!canonical||composerTarget!=="SUPPLEMENT")return;const text=String(criterion.measurement.rubric??"");setCriteriaAuthorization(null);setCriterionReturn(composer);setComposer(text);setCriterionTurn(createSuccessCriterionTurn(selectedId,canonical.revision_id,text,baseSet,{successCriterionId:criterion.success_criterion_id,revisionId:criterion.revision_id,revision:criterion.revision}));setComposerTarget("CRITERION_EDIT")}
  function editCriterion(){if(!criterionTurn||composerTarget!=="SUPPLEMENT")return;setCriterionReturn(composer);setComposer(criterionTurn.draft.text);setCriterionTurn({...criterionTurn,phase:"EDITING"});setComposerTarget("CRITERION_EDIT")}
  function updateCriterion(draft:SuccessCriterionDraft){if(!criterionTurn||!["DRAFT","EDITING"].includes(criterionTurn.phase))return;setCriterionTurn({...criterionTurn,draft,version:criterionTurn.version+1,phase:"DRAFT"})}
  function cancelCriterion(){if(!criterionTurn)return;setCriterionTurn({...criterionTurn,phase:"CANCELLED"});setCriteriaAuthorization(null);setFailure(null)}

  function criteriaGrantBundle(turn:SuccessCriterionTurn):{stage:"CRITERION"|"SET";grants:ExactGrantRequest[]}|null{
    const pending=turn.pending;if(!pending)return null;
    if(!pending.criterionRevisionId){
      return turn.source?{stage:"CRITERION",grants:[
        {owner:"SUCCESS_CRITERION",action:"REVISE",resource:`success-criterion:${turn.source.successCriterionId}`},
        {owner:"SUCCESS_CRITERION",action:"READ",resource:`success-criterion:${turn.source.successCriterionId}`},
        {owner:"SUCCESS_CRITERION",action:"READ",resource:`success-criterion:revision:${turn.source.revisionId}`},
      ]}:{stage:"CRITERION",grants:[
        {owner:"SUCCESS_CRITERION",action:"CREATE",resource:"success-criterion:collection"},
        {owner:"SUCCESS_CRITERION",action:"READ",resource:"success-criterion:collection"},
      ]};
    }
    const setResource=`success-criteria-set:${turn.problemId}`,action=turn.baseSet?"REVISE" as const:"CREATE" as const;
    return {stage:"SET",grants:[
      {owner:"SUCCESS_CRITERION",action:"READ",resource:`success-criterion:revision:${pending.criterionRevisionId}`},
      {owner:"SUCCESS_CRITERIA_SET",action,resource:setResource},
      {owner:"SUCCESS_CRITERIA_SET",action:"READ",resource:setResource},
    ]};
  }

  async function submitCriteriaAccess(bundle:{stage:"WORKSPACE"|"CRITERION"|"SET";grants:ExactGrantRequest[]}){
    if(!session||mutationFlight.current)return;
    const same=criteriaAuthorization?.request?.state!=="REJECTED"&&criteriaAuthorization?.stage===bundle.stage&&JSON.stringify(criteriaAuthorization.grants)===JSON.stringify(bundle.grants),requestKey=same?criteriaAuthorization.requestKey:newIdempotencyKey(`request-success-criteria-${bundle.stage.toLowerCase()}`),token=epoch.current,currentSession=sessionKey(session),pending={...bundle,requestKey};
    mutationFlight.current=true;setBusy(true);setFailure(null);setCriteriaAuthorization(pending);
    try{const request=await submitSuccessCriteriaGrantRequest(session.csrfToken,bundle.grants,requestKey);if(token!==epoch.current||sessionKey(sessionRef.current??session)!==currentSession)return;setCriteriaAuthorization({...pending,request})}catch(error){if(token===epoch.current)setFailure({error,operation:"申请成功标准权限",mutation:true})}finally{mutationFlight.current=false;setBusy(false)}
  }

  async function requestCriteriaAccess(){if(!criterionTurn)return;const bundle=criteriaGrantBundle(criterionTurn);if(bundle)await submitCriteriaAccess(bundle)}
  async function requestCriteriaWorkspaceAccess(){if(!selectedId)return;const resource=`success-criteria-set:${selectedId}`;await submitCriteriaAccess({stage:"WORKSPACE",grants:[{owner:"SUCCESS_CRITERION",action:"CREATE",resource:"success-criterion:collection"},{owner:"SUCCESS_CRITERION",action:"READ",resource:"success-criterion:collection"},{owner:"SUCCESS_CRITERIA_SET",action:"CREATE",resource},{owner:"SUCCESS_CRITERIA_SET",action:"READ",resource}]})}

  async function refreshCriteriaAccess(){
    if(!criteriaAuthorization?.request||busy)return;const token=epoch.current;setBusy(true);setFailure(null);let resume=false;
    try{const request=await inspectGrantRequest(criteriaAuthorization.request.requestId);if(token!==epoch.current)return;setCriteriaAuthorization({...criteriaAuthorization,request});if(request.state==="APPROVED"){resume=true;setBusy(false);if(criteriaAuthorization.stage==="WORKSPACE"&&selectedId){await loadWorkspace(selectedId);setCriteriaAuthorization(null)}else await saveCriterion(true)}}catch(error){if(token===epoch.current)setFailure({error,operation:"刷新成功标准权限"})}finally{if(token===epoch.current&&!resume)setBusy(false)}
  }
  async function saveCriterion(recover=false){
    if(!session||!selected||!criterionTurn||criterionTurn.draft.kind!=="HUMAN_EVALUATED"||mutationFlight.current)return;
    const token=epoch.current,currentSession=sessionKey(session),current=selected.detail.revisions.find(item=>item.revision_id===selected.detail.problem.current_revision_id)??latest(selected.detail.revisions);if(!current||criterionTurn.problemId!==selected.detail.problem.business_problem_id)return;
    let pending=criterionTurn.pending;if(!recover){
      if(criterionTurn.problemRevisionId!==current.revision_id){setCriterionTurn({...criterionTurn,phase:"CONFLICT"});setFailure({error:new WorkbenchRequestError("BUSINESS_PROBLEM_CONFLICT",409),operation:"保存成功标准",mutation:true});return}
      const criterionPayload={...(criterionTurn.source?{successCriterionId:criterionTurn.source.successCriterionId,predecessorRevisionId:criterionTurn.source.revisionId,expectedVersion:criterionTurn.source.revision}:{}),criterionType:"HUMAN_EVALUATED" as const,measurement:{rubric:criterionTurn.draft.text.trim()},requiredEvidenceKinds:[],evaluatorType:"HUMAN",evaluatorVersion:"v1",applicability:{}};
      pending={criterionPayload,criterionKey:newIdempotencyKey(criterionTurn.source?"revise-success-criterion":"create-success-criterion"),setKey:newIdempotencyKey("write-success-criteria-set"),problemRevisionId:current.revision_id,expectedProblemVersion:selected.detail.problem.aggregate_version};
    }
    if(!pending)return;mutationFlight.current=true;setBusy(true);setFailure(null);
    try{
      let criterionRevisionId=pending.criterionRevisionId;
      if(!criterionRevisionId){setCriterionTurn(value=>value?{...value,phase:"SAVING_CRITERION",pending}:value);try{const result=await writeCriterion(session.csrfToken,{...pending.criterionPayload,idempotencyKey:pending.criterionKey});criterionRevisionId=result.revision.revision_id;pending={...pending,criterionRevisionId};setCriteriaAuthorization(null);if(token!==epoch.current||sessionKey(sessionRef.current??session)!==currentSession)return}catch(error){if(token===epoch.current){const phase=error instanceof WorkbenchRequestError&&error.status===409?"CONFLICT":uncertain(error)?"UNKNOWN_CRITERION":"CRITERION_FAILED";setCriterionTurn(value=>value?{...value,phase,pending}:value);if(!(error instanceof WorkbenchRequestError&&error.status===403))setCriteriaAuthorization(null);setFailure({error,operation:"保存成功标准",mutation:true})}return}}
      const members=criterionTurn.baseSet?[...criterionTurn.baseSet.orderedCriterionRevisionIds]:[];
      if(criterionTurn.source){const index=members.indexOf(criterionTurn.source.revisionId);if(index<0)throw new WorkbenchRequestError("CRITERIA_SET_PREDECESSOR_MISMATCH",409);members[index]=criterionRevisionId}else members.push(criterionRevisionId);
      const setPayload=pending.setPayload??{problemRevisionId:pending.problemRevisionId,...(criterionTurn.baseSet?{predecessorSetRevisionId:criterionTurn.baseSet.setRevisionId}:{}),orderedCriterionRevisionIds:members,expectedVersion:pending.expectedProblemVersion};pending={...pending,setPayload};setCriterionTurn(value=>value?{...value,phase:"SAVING_SET",pending}:value);
      try{await writeCriteriaSet(session.csrfToken,criterionTurn.problemId,{...setPayload,idempotencyKey:pending.setKey})}catch(error){if(token===epoch.current){const phase=error instanceof WorkbenchRequestError&&error.status===409?"CONFLICT":uncertain(error)?"UNKNOWN_SET":"SET_FAILED";setCriterionTurn(value=>value?{...value,phase,pending}:value);if(!(error instanceof WorkbenchRequestError&&error.status===403))setCriteriaAuthorization(null);setFailure({error,operation:"保存成功标准",mutation:true})}return}
      if(token!==epoch.current||sessionKey(sessionRef.current??session)!==currentSession)return;setCriteriaAuthorization(null);setCriterionTurn(value=>value?{...value,phase:"SAVED",pending}:value);try{await loadWorkspace(criterionTurn.problemId)}catch(error){if(token===epoch.current)setFailure({error,operation:"恢复工作区"})}
    }finally{mutationFlight.current=false;setBusy(false)}
  }
  async function restartCriterionAfterConflict(){if(!selectedId||!criterionTurn)return;const text=criterionTurn.draft.text;setBusy(true);setFailure(null);setCriteriaAuthorization(null);try{await loadWorkspace(selectedId);setCriterionTurn(null);setComposer(text);setComposerTarget("SUPPLEMENT")}catch(error){setFailure({error,operation:"恢复工作区"})}finally{setBusy(false)}}

  const selected=workspace?.detail.problem.business_problem_id===selectedId?workspace:null;
  const canonical=selected?.detail.revisions.find(item=>item.revision_id===selected.detail.problem.current_revision_id)??createdRevision??problems.find(item=>item.business_problem_id===selectedId);
  const visibleAssistance=assistance&&session&&assistance.contextKey===sessionKey(session)&&(!selectedId||Boolean(turn))?assistance:null;
  const titleError=submitted&&!recordDraft.title.trim()?"请输入问题名称。":recordDraft.title.length>200?"问题名称不能超过 200 个字符。":"";
  const descriptionError=submitted&&!recordDraft.description.trim()?"请输入问题描述。":recordDraft.description.length>2_000?"问题描述不能超过 2000 个字符。":"";
  const messageKey=[turn?.id,turn?.phase==="EDITING",visibleAssistance?.result.state,visibleAssistance?.result.aggregateVersion,criterionTurn?.id,criterionTurn?.phase,supplements.length,contextNotice].join(":");
  function locateMessage(id:string){const node=document.getElementById(id);node?.scrollIntoView({behavior:"smooth",block:"center"});node?.focus({preventScroll:true})}

  if(loading)return <main className="px-page"><section className="px-state" role="status"><span className="px-spinner"/><strong>正在恢复可信业务工作区</strong></section></main>;
  if(loginRequired)return <main className="px-page"><section className="px-state"><h1>需要登录可信工作台</h1><p>请重新登录。身份只来自受保护的浏览器会话，不接受页面提供的身份信息。</p><a className="px-primary-button" href="/api/workbench/v1/login">登录可信工作台</a></section>{failure&&<WorkbenchErrorNotice {...failure}/>}</main>;
  return <main className="px-page px-workspace"><header className="px-page-title"><div><p>工作与流程 <small>Trusted Business Workspace</small></p><h1>新建对话</h1><span>通过受治理的 AI 补问形成可编辑草稿；只有你确认后才会创建正式业务问题。</span></div></header>
    <details className="px-problem-switcher"><summary>业务问题与新建入口</summary><button type="button" disabled={busy||!selectedId||turn?.phase==="UNKNOWN"} onClick={()=>{setAssistance(null);startNew()}}>＋ 新建对话</button><nav aria-label="业务问题列表">{[...problems].reverse().map(problem=><button type="button" disabled={busy||turn?.phase==="UNKNOWN"} className={selectedId===problem.business_problem_id?"selected":""} key={problem.business_problem_id} onClick={()=>void select(problem.business_problem_id)}><strong>{problem.title}</strong><small>修订 {problem.revision} · {readable(problem.created_at)}</small></button>)}</nav></details>
    <div className="px-workspace-body"><ConversationFrame newMessageKey={messageKey} composer={<ConversationComposer value={composer} onChange={setComposer} onSend={sendComposer} onCancelEdit={cancelComposerEdit} disabled={busy&&composerTarget!=="SUPPLEMENT"} contextLabel={canonical?.title} mode={composerTarget==="DRAFT"?"DRAFT_REPLACE":composerTarget==="FORMAL"?"FORMAL_REPLACE":composerTarget==="CRITERION_EDIT"?"CRITERION_REPLACE":composerTarget}/> }>
      {contextNotice&&<SystemMessage><section className="px-inline-card px-context-card" role="status"><span className="px-eyebrow">上下文已隔离</span><h2>请在当前可信会话重新开始</h2><p>{contextNotice}</p></section></SystemMessage>}
      {!turn&&!visibleAssistance&&!selectedId&&<SystemMessage><section className="px-welcome"><h2>你希望解决什么问题？</h2><p>直接描述即可。平台会先完成精确授权，再通过 AI 补问或生成可修改草稿；只有你确认后才会创建正式 Problem。</p><p>首批合成 transport 与真实 provider 会明确区分；页面不会自动调用数字员工、Agent、Skill、知识库或附件。</p></section></SystemMessage>}
      {visibleAssistance&&!turn&&<UserMessage>{visibleAssistance.originalText}</UserMessage>}
      {visibleAssistance&&<SystemMessage label="AI 辅助"><DraftAssistanceCard result={visibleAssistance.result} busy={busy} onRefresh={()=>void refreshAssistance()} onObserve={()=>void observeAssistance()} onCancel={()=>void cancelAssistance()} onReject={()=>void rejectAssistance()} onManualFallback={manualFallback}/>{failure&&["请求 AI 草稿辅助","刷新 AI 草稿辅助","观察 AI 原调用","取消 AI 草稿辅助","拒绝 AI 草稿","补记草稿来源"].includes(failure.operation)&&<WorkbenchErrorNotice {...failure} onRetry={failure.operation==="补记草稿来源"?()=>void repairProblemLink():visibleAssistance.result.state==="OUTCOME_UNKNOWN"?()=>void observeAssistance():()=>void refreshAssistance()} retryLabel={failure.operation==="补记草稿来源"?"仅重试来源补记":"继续原辅助调用"}/>}</SystemMessage>}
      {turn&&<><UserMessage>{turn.originalText}</UserMessage><SystemMessage><DraftCard turn={turn} busy={busy} composerEditing={composerTarget==="DRAFT"} onConfirm={()=>void create()} onRecover={()=>void create(true)} onEditFields={editTurnFields} onFinishFields={finishTurnFields} onEditWithComposer={editTurnWithComposer} onCancel={cancelTurn} onChange={updateTurn}/>{failure?.operation==="创建业务问题"&&<WorkbenchErrorNotice {...failure} onRetry={turn.phase==="UNKNOWN"?undefined:()=>void create()} retryLabel="重新提交当前草稿"/>}</SystemMessage></>}
      {supplements.map(item=><Fragment key={item.id}><UserMessage>{item.text}</UserMessage><SystemMessage><section className="px-inline-card px-supplement-card" role="status"><span className="px-eyebrow">{item.assisted?"AI 补问回复":"页内补充"}</span><h2>{item.assisted?"已形成新 turn":"已保留，尚未采用"}</h2><p>{item.assisted?"正文只在本次受控请求和当前页面内存中使用；服务端只保留新 turn/invocation 元数据。":"这段内容仅保留在当前页面，尚未修改正式问题，也不会自动发送给管理员。刷新、离开或切换可信上下文可能丢失。"}</p>{selected&&selected.sets.length===0&&(!criterionTurn||criterionTurn.phase==="CANCELLED"||criterionTurn.phase==="SAVED")&&<button type="button" onClick={()=>startCriterion(item.text)}>明确采用为成功标准</button>}</section></SystemMessage></Fragment>)}
      {canonical&&selectedId&&<SystemMessage><CreatedProblemCard revision={canonical} restored={!turn}/></SystemMessage>}
      {selectedId&&(authorization.continuation||authorization.request)&&<SystemMessage><AuthorizationCard state={authorization} busy={busy} readComplete={Boolean(selected)} onRequest={()=>void requestAccess()} onRefresh={()=>void refreshAuthorization()}/>{failure&&failure.operation!=="创建业务问题"&&failure.operation!=="保存业务问题"&&failure.operation!=="保存成功标准"&&<WorkbenchErrorNotice {...failure} onRetry={failure.operation==="申请查看权限"?()=>void requestAccess():authorization.request?()=>void refreshAuthorization():undefined} retryLabel={failure.operation==="申请查看权限"?"恢复原授权申请":"重新读取当前状态"}/>}</SystemMessage>}
      {failure&&failure.operation!=="创建业务问题"&&failure.operation!=="保存业务问题"&&failure.operation!=="保存成功标准"&&!authorization.continuation&&!authorization.request&&<SystemMessage><WorkbenchErrorNotice {...failure}/></SystemMessage>}
      {selected&&<SystemMessage><FormalProblemCard detail={selected.detail} draft={recordDraft} editing={recordEditing} composerEditing={composerTarget==="FORMAL"} busy={busy} dirty={recordDirty} titleError={titleError} descriptionError={descriptionError} onChange={setRecordDraft} onEdit={startFormalEdit} onEditWithComposer={startFormalComposerEdit} onCancel={cancelFormalEdit} onSave={()=>void saveProblem()}/>{failure?.operation==="保存业务问题"&&<WorkbenchErrorNotice {...failure} onRetry={()=>void saveProblem()} retryLabel="重新提交正式修订"/>}</SystemMessage>}
      {selected&&selected.criteriaReadable&&selected.sets.length>0&&<SystemMessage><SavedCriteriaHistory sets={selected.sets} criteria={selected.criteria} busy={busy||Boolean(criterionTurn&&!["DRAFT","EDITING","CANCELLED","SAVED"].includes(criterionTurn.phase))} pendingText={composerTarget==="SUPPLEMENT"?composer:""} onCreateFrom={base=>startCriterion(composer,base)} onRevise={reviseCriterion}/></SystemMessage>}
      {selected&&!selected.criteriaReadable&&<SystemMessage><CriteriaWorkspaceAuthorization authorization={criteriaAuthorization?.stage==="WORKSPACE"?criteriaAuthorization:null} busy={busy} onRequest={()=>void requestCriteriaWorkspaceAccess()} onRefresh={()=>void refreshCriteriaAccess()}/>{criteriaFailure&&<WorkbenchErrorNotice {...criteriaFailure}/>}</SystemMessage>}
      {selected&&selected.criteriaReadable&&(criterionTurn&&criterionTurn.problemId===selectedId||selected.sets.length===0)&&<SystemMessage>{criterionTurn&&criterionTurn.problemId===selectedId?<><SuccessCriterionCard turn={criterionTurn} busy={busy} composerEditing={composerTarget==="CRITERION_EDIT"} authorization={criteriaAuthorization?.stage==="WORKSPACE"?null:criteriaAuthorization} onConfirm={()=>void saveCriterion()} onRecover={()=>void saveCriterion(true)} onRequestAuthorization={()=>void requestCriteriaAccess()} onRefreshAuthorization={()=>void refreshCriteriaAccess()} onRestartAfterConflict={()=>void restartCriterionAfterConflict()} onEdit={editCriterion} onCancel={cancelCriterion} onChange={updateCriterion}/>{failure&&["保存成功标准","申请成功标准权限","刷新成功标准权限"].includes(failure.operation)&&<WorkbenchErrorNotice {...failure}/>}</>:<section className="px-inline-card px-boundary-card"><span className="px-eyebrow">下一步</span><h2>为当前问题定义成功标准</h2><p>请说明达到什么结果才算解决。发送后先确认原文和人工验收类型，确认后才调用正式接口。</p><button type="button" className="px-primary-button" disabled={busy||composerTarget!=="SUPPLEMENT"} onClick={()=>startCriterion()}>定义成功标准</button></section>}</SystemMessage>}
      {selected&&<SystemMessage><section className="px-inline-card px-boundary-card"><span className="px-eyebrow">后续边界</span><h2>成功标准不等于已经达成</h2><p>本轮不启动计划、执行或结果评价；修改正式问题仍需要独立权限。</p><details><summary>技术边界详情</summary><p>本批不伪造 Workflow / Plan、执行、Human Intervention、Evidence 或 Outcome。数字员工、资源可选项、已绑定与实际使用保持分离；只有 Attempt 事实才能证明本次实际使用。</p><p>未配置、未绑定、未执行、暂不可用与执行失败继续保持为不同状态。</p></details></section></SystemMessage>}
    </ConversationFrame><ProblemTaskSummary revision={canonical} detail={selected?.detail} criteria={selected?.criteria??[]} sets={selected?.sets??[]} authorization={authorization} busy={busy} readFailed={Boolean(authorization.request?.state==="APPROVED"&&!selected&&failure)} contextKey={`${session?sessionKey(session):"none"}:${selectedId??"new"}:${canonical?.revision_id??"none"}:${authorization.request?.requestId??"none"}:${authorization.request?.aggregateVersion??0}`} onLocateProblem={()=>locateMessage(selected?"formal-problem-message":canonical?"created-problem-message":"draft-problem-message")} onLocateAuthorization={()=>locateMessage("authorization-message")}/></div>
  </main>;
}

function CreatedProblemCard({revision,restored}:{revision:BusinessProblemRevision;restored:boolean}){return <section id="created-problem-message" tabIndex={-1} className="px-inline-card px-created-card is-complete"><header><div><span className="px-eyebrow">创建结果</span><h2>{restored?"已恢复正式业务记录":"业务问题已创建"}</h2></div><span className="px-status success">已创建</span></header><details><summary>查看创建事实</summary><p>{restored?"此卡片来自当前正式 Problem 端口允许读取的业务事实，不是恢复的聊天历史。":"创建响应已经确认；后续聊天不会覆盖这条已提交事实。"}</p><dl><dt>Problem ID</dt><dd><code>{revision.business_problem_id}</code></dd><dt>Problem Revision</dt><dd><code>{revision.revision_id}</code></dd><dt>Digest</dt><dd><code>{revision.digest}</code></dd></dl></details></section>}

function FormalProblemCard({detail,draft,editing,composerEditing,busy,dirty,titleError,descriptionError,onChange,onEdit,onEditWithComposer,onCancel,onSave}:{detail:BusinessProblemDetail;draft:RecordDraft;editing:boolean;composerEditing:boolean;busy:boolean;dirty:boolean;titleError:string;descriptionError:string;onChange:(value:RecordDraft)=>void;onEdit:()=>void;onEditWithComposer:()=>void;onCancel:()=>void;onSave:()=>void}){
  const current=detail.revisions.find(item=>item.revision_id===detail.problem.current_revision_id)??latest(detail.revisions);
  return <section id="formal-problem-message" tabIndex={-1} className="px-inline-card px-formal-card"><header><div><span className="px-eyebrow">问题详情</span><h2>读取成功</h2></div><span className="px-status success">已读取</span></header><p className="px-truth-note">已获得查看权限并读取问题详情；修改此问题需要另行授权。</p>{editing?<><label className="px-field" htmlFor="problem-title"><span>问题名称（可选修改）</span><input id="problem-title" maxLength={200} value={draft.title} aria-invalid={Boolean(titleError)} disabled={busy} onChange={event=>onChange({...draft,title:event.target.value})}/>{titleError&&<strong className="px-field-error">{titleError}</strong>}</label><label className="px-field" htmlFor="problem-description"><span>完整描述</span><textarea id="problem-description" maxLength={2_000} value={draft.description} aria-invalid={Boolean(descriptionError)} disabled={busy} onChange={event=>onChange({...draft,description:event.target.value})}/>{descriptionError&&<strong className="px-field-error">{descriptionError}</strong>}</label><div className="px-card-actions"><button type="button" disabled={busy} onClick={onCancel}>放弃修改</button><button type="button" disabled={busy} onClick={onEditWithComposer}>使用输入框完整修改</button><button type="button" className="px-primary-button" disabled={busy||!dirty} onClick={onSave}>{busy?"正在保存…":"保存正式修订"}</button></div></>:composerEditing?<><h3>{draft.title}</h3><p>{draft.description}</p><p className="px-mode-note">正在底部输入框完整替换描述；卡片字段和保存操作暂时停用。</p></>:<><h3>{current?.title}</h3><p>{current?.description}</p><button type="button" disabled={busy} onClick={onEdit}>修改正式问题</button></>}<details><summary>技术详情</summary><p>查看权限批准后，本页执行 fresh exact GET；READ 不隐含 REVISE。</p><dl><dt>Problem ID</dt><dd><code>{detail.problem.business_problem_id}</code></dd><dt>Problem Revision</dt><dd><code>{current?.revision_id}</code></dd><dt>Aggregate Version</dt><dd>{detail.problem.aggregate_version}</dd><dt>Owner</dt><dd>{current?.owner_id}</dd></dl></details></section>;
}

function AuthorizationCard({state,busy,readComplete,onRequest,onRefresh}:{state:AuthorizationState;busy:boolean;readComplete:boolean;onRequest:()=>void;onRefresh:()=>void}){
  const continuation=state.continuation,request=state.request;
  return <section id="authorization-message" tabIndex={-1} className="px-inline-card px-authorization-card"><header><div><span className="px-eyebrow">授权状态</span><h2>申请查看权限</h2></div></header>{continuation?.state==="AVAILABLE"&&!request&&<><p>问题已创建，但查看问题详情需要独立授权。提交后请把准确申请编号交给管理员。</p><button className="px-primary-button" disabled={busy} onClick={onRequest}>{busy?"正在提交…":state.requestKey?"恢复原授权申请":"申请查看权限"}</button></>}{continuation?.state==="CONSUMED"&&!request&&<p>查看申请已经提交。页面只恢复原申请，不会重复提交。</p>}{continuation?.state==="EXPIRED"&&<><span className="px-status danger">申请窗口已过期</span><p>已创建问题仍保留；页面不会自动延长窗口、撤销创建或换新标识重建。</p></>}{request&&<><div className="px-request-status"><span className={`px-status ${request.state==="APPROVED"?"success":request.state==="REJECTED"?"danger":"warning"}`}>{request.state==="APPROVED"?"已批准":request.state==="REJECTED"?"已拒绝":"等待管理员处理"}</span><p>{request.state==="PENDING"?"将申请编号交给独立管理员；处理后在这里刷新。":request.state==="REJECTED"?"管理员已拒绝；页面不会读取问题详情。":readComplete?"授权已批准；问题详情已读取成功。":"授权已批准；页面会重新读取，成功后才显示问题详情。"}</p></div><dl><dt>申请编号</dt><dd><code>{request.requestId}</code></dd><dt>状态版本</dt><dd>{request.aggregateVersion}</dd></dl><button id="refresh-authorization" disabled={busy} onClick={onRefresh}>{busy?"正在刷新…":"刷新授权状态"}</button></>}{(continuation||request)&&<details><summary>授权技术详情</summary>{request&&<p>批准后通过 fresh exact GET 读取；READ 权限不包含 REVISE。</p>}{continuation&&<dl><dt>Continuation 状态</dt><dd>{continuation.state}</dd><dt>申请窗口到期</dt><dd>{readable(continuation.expiresAt)}</dd></dl>}</details>}</section>;
}

function CriteriaWorkspaceAuthorization({authorization,busy,onRequest,onRefresh}:{authorization:CriteriaAuthorizationState|null;busy:boolean;onRequest:()=>void;onRefresh:()=>void}){
  const request=authorization?.request;
  return <section className="px-inline-card px-boundary-card"><span className="px-eyebrow">成功标准权限</span><h2>尚未读取成功标准</h2><p>业务问题 READ 不包含成功标准或集合的读取、创建、修订权限。页面不会把不可读状态显示成“未配置”。</p>{!authorization&&<button type="button" className="px-primary-button" disabled={busy} onClick={onRequest}>申请定义与读取权限</button>}{authorization&&!request&&<p className="px-mode-note">正在提交正式申请；申请本身不会授予权限。</p>}{request&&<><span className={`px-status ${request.state==="APPROVED"?"success":request.state==="REJECTED"?"danger":"warning"}`}>{request.state==="PENDING"?"等待独立审批":request.state==="APPROVED"?"已批准":"已拒绝"}</span><dl><dt>申请编号</dt><dd><code>{request.requestId}</code></dd><dt>请求操作</dt><dd>{request.requestedActions.join(", ")}</dd></dl><div className="px-card-actions">{request.state==="PENDING"&&<a href={`/authorization-admin?request=${encodeURIComponent(request.requestId)}`} target="_blank" rel="noreferrer">在独立管理员窗口打开</a>}<button type="button" disabled={busy} onClick={request.state==="REJECTED"?onRequest:onRefresh}>{request.state==="REJECTED"?"重新提交新申请":busy?"正在检查…":"刷新权限状态并继续"}</button></div></>}</section>;
}
