import { useEffect, type ReactNode } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";

interface ConsoleShellProps { children: ReactNode }
type IconName="home"|"problem"|"employee"|"flow"|"knowledge"|"resource"|"record"|"manage";
function Icon({name}:{name:IconName}) { const paths:Record<IconName,ReactNode>={home:<><path d="M3 10.5 12 3l9 7.5"/><path d="M5.5 9.5V21h13V9.5M9 21v-7h6v7"/></>,problem:<><path d="M4 5h16v12H8l-4 4V5Z"/><path d="M8 9h8M8 13h5"/></>,employee:<><circle cx="12" cy="8" r="3"/><path d="M5 21v-2a7 7 0 0 1 14 0v2M4 7h2M18 7h2M12 2v2"/></>,flow:<><rect x="3" y="4" width="6" height="5" rx="1"/><rect x="15" y="15" width="6" height="5" rx="1"/><path d="M9 6.5h4a4 4 0 0 1 4 4V15M15 17.5h-4a4 4 0 0 1-4-4V9"/></>,knowledge:<><path d="M4 5.5A3.5 3.5 0 0 1 7.5 2H12v18H7.5A3.5 3.5 0 0 0 4 23V5.5Z"/><path d="M20 5.5A3.5 3.5 0 0 0 16.5 2H12v18h4.5A3.5 3.5 0 0 1 20 23V5.5Z"/></>,resource:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,record:<><path d="M5 3h14v18H5zM9 8h6M9 12h6M9 16h4"/></>,manage:<><circle cx="12" cy="12" r="3"/><path d="M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0ZM12 2v3M12 19v3M2 12h3M19 12h3"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg> }
const primary:[[string,IconName,string,string],...[string,IconName,string,string][]]=[["/dashboard","home","首页","业务总览"],["/work","problem","业务问题","工作台"],["/digital-employees","employee","数字员工","定义与装配"],["/skills","resource","Skill","技能资源"],["/mcp","resource","MCP","工具连接"],["/knowledge","knowledge","Knowledge","知识依据"],["/workflow-definitions","flow","Workflow","流程定义"],["/runtime-profiles","flow","Runtime","运行配置"],["/evidence","record","Evidence","事实证据"],["/outcomes","record","Outcome","业务结果"]];
const technical=[["/problems","问题审核与修订"],["/agents","Agent Definition"],["/catalog","资源统一目录"],["/relationships","对象关系"],["/attention","系统与治理"]] as const;
const support=[["/applications","应用市场"],["/agent-center","Agent Center"],["/permissions","权限中心"],["/security","安全中心"],["/operations","运维监控"],["/models","模型中心"],["/usage","费用与使用量"],["/settings","系统设置"],["/help","帮助中心"]] as const;
type JourneyStep={to:string;label:string};
const journeys:Record<string,{title:string;steps:JourneyStep[]}>= {
  business:{title:"业务闭环总览",steps:[{to:"/work?journey=business&stage=problem",label:"业务问题"},{to:"/work?journey=business&stage=success",label:"成功标准"},{to:"/problems?journey=business&stage=plan",label:"已批准 Plan"},{to:"/digital-employees?journey=business",label:"数字员工"},{to:"/skills?journey=business",label:"Skill"},{to:"/mcp?journey=business",label:"MCP"},{to:"/knowledge?journey=business",label:"Knowledge"},{to:"/workflow-definitions?journey=business",label:"Workflow"},{to:"/runtime-profiles?journey=business&stage=attempt",label:"Runtime / Attempt"},{to:"/evidence?journey=business",label:"Evidence"},{to:"/outcomes?journey=business",label:"Outcome"}]},
  assembly:{title:"数字员工装配",steps:[{to:"/digital-employees?journey=assembly",label:"数字员工"},{to:"/agent-center?journey=assembly",label:"Agent Definition"},{to:"/skills?journey=assembly",label:"Skill 绑定"},{to:"/mcp?journey=assembly",label:"MCP 端点边界"},{to:"/knowledge?journey=assembly",label:"Knowledge 绑定"},{to:"/workflow-definitions?journey=assembly",label:"Workflow 定义"},{to:"/runtime-profiles?journey=assembly",label:"Runtime 配置"},{to:"/evidence?journey=assembly",label:"Evidence 入口"}]},
  governance:{title:"平台治理与运营",steps:[{to:"/dashboard?journey=governance",label:"首页"},{to:"/permissions?journey=governance",label:"权限中心"},{to:"/security?journey=governance",label:"安全中心"},{to:"/operations?journey=governance",label:"运维监控"},{to:"/models?journey=governance",label:"模型中心"},{to:"/usage?journey=governance",label:"费用与使用量"},{to:"/settings?journey=governance",label:"系统设置"},{to:"/help?journey=governance",label:"帮助中心"}]}
};
function JourneyRail(){const location=useLocation(),params=new URLSearchParams(location.search),id=params.get("journey")??"",journey=journeys[id];if(!journey)return null;const current=`${location.pathname}${location.search}`,exact=journey.steps.findIndex(step=>step.to===current),index=Math.max(0,exact>=0?exact:journey.steps.findIndex(step=>new URL(step.to,"http://local").pathname===location.pathname));return <nav className="px-journey-rail" aria-label={`${journey.title}演示路径`}><div><strong>{journey.title}</strong><span>第 {index+1} / {journey.steps.length} 步 · {journey.steps[index].label}</span></div><ol>{journey.steps.map((step,stepIndex)=><li key={step.to}><Link aria-current={stepIndex===index?"step":undefined} to={step.to}>{step.label}</Link></li>)}</ol><div className="px-journey-actions">{index>0&&<Link to={journey.steps[index-1].to}>上一步</Link>}{index<journey.steps.length-1&&<Link to={journey.steps[index+1].to}>下一步</Link>}<Link to={location.pathname}>退出演示</Link></div></nav>}
export function ConsoleShell({children}:ConsoleShellProps){const location=useLocation();useEffect(()=>{const heading=document.querySelector<HTMLElement>("main h1");if(heading){heading.tabIndex=-1;heading.focus()}},[location.pathname,location.search]);return <div className="px-shell"><aside className="px-sidebar"><NavLink className="px-brand" to="/dashboard"><span className="px-brand-mark">A</span><span>企业智能体平台<small>Enterprise Agent Platform</small></span></NavLink><span className="demo-primary-nav px-nav-compat" aria-hidden="true"/><nav className="px-primary-nav" aria-label="P1 核心产品导航">{primary.map(([to,icon,label,secondary])=><NavLink key={to} to={to}><span className="px-nav-icon"><Icon name={icon}/></span><span>{label}<small>{secondary}</small></span></NavLink>)}</nav><div className="px-nav-group"><span>管理与技术</span><nav aria-label="管理与技术导航">{technical.map(([to,label])=><NavLink aria-label={to==="/attention"?"Attention":undefined} key={to} to={to}><Icon name="manage"/><span>{label}</span></NavLink>)}</nav></div><div className="px-nav-group"><span>平台支撑</span><nav aria-label="平台支撑导航">{support.map(([to,label])=><NavLink key={to} to={to}><Icon name="manage"/><span>{label}</span></NavLink>)}</nav></div><a className="px-sidebar-foot" href="/dashboard#planned"><span className="px-plan-dot"/>v0.3 能力建设中</a></aside><header className="px-topbar"><label className="px-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input aria-label="全局搜索" placeholder="搜索业务问题、数字员工、知识或资源"/><kbd>⌘ K</kbd></label><nav className="px-demo-launcher" aria-label="可重复演示路径"><Link to={journeys.business.steps[0].to}>业务闭环</Link><Link to={journeys.assembly.steps[0].to}>数字员工装配</Link><Link to={journeys.governance.steps[0].to}>平台治理</Link></nav><div className="px-tools"><NavLink to="/attention" aria-label="通知"><span className="px-notification"/>通知</NavLink><NavLink to="/help">帮助</NavLink><span className="px-user" aria-hidden="true">审</span><span>审核人员</span></div></header><nav className="px-mobile-nav" aria-label="移动端产品导航">{[...primary.map(([to,,label])=>[to,label] as const),...support].map(([to,label])=><NavLink key={to} to={to}>{label}</NavLink>)}</nav><div className="px-content"><JourneyRail/>{children}</div></div>}
