import type { ReactNode } from "react";
import { NavLink } from "react-router-dom";

interface ConsoleShellProps { children: ReactNode }
type IconName="home"|"problem"|"employee"|"flow"|"knowledge"|"resource"|"record"|"manage";
function Icon({name}:{name:IconName}) { const paths:Record<IconName,ReactNode>={home:<><path d="M3 10.5 12 3l9 7.5"/><path d="M5.5 9.5V21h13V9.5M9 21v-7h6v7"/></>,problem:<><path d="M4 5h16v12H8l-4 4V5Z"/><path d="M8 9h8M8 13h5"/></>,employee:<><circle cx="12" cy="8" r="3"/><path d="M5 21v-2a7 7 0 0 1 14 0v2M4 7h2M18 7h2M12 2v2"/></>,flow:<><rect x="3" y="4" width="6" height="5" rx="1"/><rect x="15" y="15" width="6" height="5" rx="1"/><path d="M9 6.5h4a4 4 0 0 1 4 4V15M15 17.5h-4a4 4 0 0 1-4-4V9"/></>,knowledge:<><path d="M4 5.5A3.5 3.5 0 0 1 7.5 2H12v18H7.5A3.5 3.5 0 0 0 4 23V5.5Z"/><path d="M20 5.5A3.5 3.5 0 0 0 16.5 2H12v18h4.5A3.5 3.5 0 0 1 20 23V5.5Z"/></>,resource:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,record:<><path d="M5 3h14v18H5zM9 8h6M9 12h6M9 16h4"/></>,manage:<><circle cx="12" cy="12" r="3"/><path d="M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0ZM12 2v3M12 19v3M2 12h3M19 12h3"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg> }
const primary:[[string,IconName,string,string],...[string,IconName,string,string][]]=[["/dashboard","home","首页","业务总览"],["/problems","problem","业务问题","提出与分析"],["/digital-employees","employee","数字员工","定义与装配"],["/work","flow","工作与流程","计划与执行"],["/knowledge","knowledge","知识","依据与引用"],["/catalog","resource","能力资源","统一目录"],["/tasks","record","工作记录","任务与状态"],["/workspace","home","我的空间","个人入口"]];
const technical=[["/skills","Skill 管理"],["/mcp","MCP 管理"],["/runtime-profiles","Runtime 管理"],["/evidence","Evidence 检查"],["/attention","系统与治理"]] as const;
export function ConsoleShell({children}:ConsoleShellProps){return <div className="px-shell"><aside className="px-sidebar"><NavLink className="px-brand" to="/dashboard"><span className="px-brand-mark">A</span><span>企业智能体平台<small>Enterprise Agent Platform</small></span></NavLink><nav className="px-primary-nav" aria-label="产品主导航">{primary.map(([to,icon,label,secondary])=><NavLink key={to} to={to}><span className="px-nav-icon"><Icon name={icon}/></span><span>{label}<small>{secondary}</small></span></NavLink>)}</nav><div className="px-nav-group"><span>管理与技术</span><nav aria-label="管理与技术导航">{technical.map(([to,label])=><NavLink key={to} to={to}><Icon name="manage"/><span>{label}</span></NavLink>)}</nav></div><a className="px-sidebar-foot" href="/dashboard#planned"><span className="px-plan-dot"/>v0.3 能力建设中</a></aside><header className="px-topbar"><label className="px-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input aria-label="全局搜索" placeholder="搜索业务问题、数字员工、知识或资源"/><kbd>⌘ K</kbd></label><div className="px-tools"><NavLink to="/attention" aria-label="通知"><span className="px-notification"/>通知</NavLink><a href="#px-help">帮助</a><span className="px-user" aria-hidden="true">审</span><span>审核人员</span></div></header><nav className="px-mobile-nav" aria-label="移动端产品主导航">{primary.slice(0,6).map(([to,,label])=><NavLink key={to} to={to}>{label}</NavLink>)}</nav><div className="px-content">{children}</div></div>}
