import {useEffect,useMemo,useRef,useState} from "react";
import {useSearchParams} from "react-router-dom";
import {createRuntimeProfile,editRuntimeProfile,getRuntimeProfile,listRuntimeProfiles,publishRuntimeProfile,reviewRuntimeProfile,runtimeControlledState,successorRuntimeProfile,validateRuntimeProfile,RuntimeProfileRequestError,type RuntimeControlledState,type RuntimeContent,type RuntimeProjection} from "../api/runtimeProfiles";
import {RuntimeProfileTechnicalProjection} from "./RuntimeProfileTechnicalProjection";

const blank:RuntimeContent={provider:"NATIVE_KUBERNETES",resources:{cpuRequest:"250m",cpuLimit:"500m",memoryRequest:"256Mi",memoryLimit:"1Gi"},isolation:"NAMESPACE",stateMode:"STATELESS",sessionAffinity:"NONE",secretReferences:[],openClawPackageRef:null};
const csv=(value:string)=>value.split(",").map(item=>item.trim()).filter(Boolean);
type Recovery={state:RuntimeControlledState;reason:string;attemptedVersion:number;authoritative:RuntimeProjection;safeDraft:RuntimeContent|null};

function RuntimeProfileForm({name,content,onName,onChange}:{name:string;content:RuntimeContent;onName:(value:string)=>void;onChange:(value:RuntimeContent)=>void}){
 const resources=(patch:Partial<RuntimeContent["resources"]>)=>onChange({...content,resources:{...content.resources,...patch}});
 return <section className="workbench-card resource-form" aria-label="Runtime Profile 表单"><h2>Runtime Profile 声明</h2><p>仅配置声明。保存或发布不会创建 Runtime Instance，也不证明运行或健康。</p><label>名称<input value={name} maxLength={120} onChange={event=>onName(event.target.value)}/></label><div className="resource-form-grid">
  <label>Provider<select value={content.provider} onChange={event=>{const provider=event.target.value as RuntimeContent["provider"];onChange({...content,provider,openClawPackageRef:provider==="OPENCLAW"?(content.openClawPackageRef??""):null})}}><option>NATIVE_KUBERNETES</option><option>OPENCLAW</option></select></label>
  <label>Isolation<select value={content.isolation} onChange={event=>onChange({...content,isolation:event.target.value as RuntimeContent["isolation"]})}><option>NAMESPACE</option><option>DEDICATED_RUNTIME</option></select></label>
  <label>CPU request<input value={content.resources.cpuRequest} pattern="[1-9][0-9]*m" onChange={event=>resources({cpuRequest:event.target.value})}/></label><label>CPU limit<input value={content.resources.cpuLimit} pattern="[1-9][0-9]*m" onChange={event=>resources({cpuLimit:event.target.value})}/></label>
  <label>Memory request<input value={content.resources.memoryRequest} pattern="[1-9][0-9]*(Mi|Gi)" onChange={event=>resources({memoryRequest:event.target.value})}/></label><label>Memory limit<input value={content.resources.memoryLimit} pattern="[1-9][0-9]*(Mi|Gi)" onChange={event=>resources({memoryLimit:event.target.value})}/></label>
  <label>State mode<select value={content.stateMode} onChange={event=>onChange({...content,stateMode:event.target.value as RuntimeContent["stateMode"]})}><option>STATELESS</option><option>EXTERNAL_REFERENCE</option></select></label><label>Session affinity<select value={content.sessionAffinity} onChange={event=>onChange({...content,sessionAffinity:event.target.value as RuntimeContent["sessionAffinity"]})}><option>NONE</option><option>REQUIRED</option></select></label>
  <label>Secret References（逗号分隔）<input value={content.secretReferences.join(", ")} placeholder="secret-ref:namespace/name" onChange={event=>onChange({...content,secretReferences:csv(event.target.value)})}/></label>
  {content.provider==="OPENCLAW"&&<label>OpenClaw immutable package reference<input value={content.openClawPackageRef??""} placeholder="oci://registry/package@sha256:…" onChange={event=>onChange({...content,openClawPackageRef:event.target.value})}/></label>}
 </div></section>;
}

export function RuntimeProfileWorkbenchPage(){
 const [searchParams,setSearchParams]=useSearchParams();const [initialProfileId]=useState(()=>searchParams.get("resourceId"));
 const [items,setItems]=useState<RuntimeProjection[]>([]),[selected,setSelected]=useState<RuntimeProjection|null>(null),[form,setForm]=useState<RuntimeContent|null>(null),[formName,setFormName]=useState(""),[query,setQuery]=useState(searchParams.get("query")??""),[filter,setFilter]=useState(searchParams.get("lifecycle")??"ALL");
 const [state,setState]=useState<"LOADING"|"READY"|"SAVING">("LOADING"),[failure,setFailure]=useState<{state:RuntimeControlledState;reason:string}|null>(null),[recovery,setRecovery]=useState<Recovery|null>(null);const requestId=useRef(0),actionInFlight=useRef(false),saveInFlight=useRef(false);
 function preserveContext(patch:Record<string,string|null>){const next=new URLSearchParams(searchParams);for(const [key,value] of Object.entries(patch)){if(value)next.set(key,value);else next.delete(key)}setSearchParams(next,{replace:true})}
 function fail(reason:unknown){const error=reason instanceof RuntimeProfileRequestError?reason:new RuntimeProfileRequestError("RUNTIME_PROFILE_UNAVAILABLE",503);setFailure({state:runtimeControlledState(error),reason:error.reasonCode});setState("READY")}
 async function refresh(id?:string){const current=++requestId.current;setState("LOADING");try{const values=await listRuntimeProfiles();const detail=id?await getRuntimeProfile(id):null;if(current!==requestId.current)return;setItems(values);if(detail){setSelected(detail);preserveContext({resourceId:id!})}setFailure(null);setState("READY")}catch(reason){if(current===requestId.current)fail(reason)}}useEffect(()=>{let active=true;Promise.all([listRuntimeProfiles(),initialProfileId?getRuntimeProfile(initialProfileId):Promise.resolve(null)]).then(([values,detail])=>{if(active){setItems(values);if(detail)setSelected(detail);setState("READY")}}).catch(reason=>{if(active)fail(reason)});return()=>{active=false}},[initialProfileId]);
 function startCreate(provider:RuntimeContent["provider"]="NATIVE_KUBERNETES"){setSelected(null);setFormName("");setForm({...blank,provider,openClawPackageRef:provider==="OPENCLAW"?"":null});setFailure(null)}
 function startEdit(){if(!selected)return;const draft=selected.profile.revisions.find(item=>item.revisionId===selected.profile.currentDraftRevisionId);if(draft){setFormName(selected.profile.name);setForm(structuredClone(draft.content))}}
 async function save(){if(!form||!formName.trim()||saveInFlight.current)return;saveInFlight.current=true;setState("SAVING");try{const value=selected?.profile.currentDraftRevisionId&&selected.profile.name===formName?await editRuntimeProfile(selected.profile,form):await createRuntimeProfile(formName.trim(),form);setForm(null);setFormName("");await refresh(value.profile.runtimeProfileId)}catch(reason){fail(reason)}finally{saveInFlight.current=false}}
 async function act(operation:(profile:RuntimeProjection["profile"])=>Promise<RuntimeProjection>){if(!selected||actionInFlight.current)return;actionInFlight.current=true;const attemptedVersion=selected.profile.aggregateVersion;setState("SAVING");try{const value=await operation(selected.profile);const [values,authoritative]=await Promise.all([listRuntimeProfiles(),getRuntimeProfile(value.profile.runtimeProfileId)]);actionInFlight.current=false;setSelected(authoritative);setItems(values);setFailure(null);setRecovery(null);setState("READY")}catch(reason){const error=reason instanceof RuntimeProfileRequestError?reason:new RuntimeProfileRequestError("RUNTIME_PROFILE_UNAVAILABLE",503);if(error.status===409){try{const authoritative=await getRuntimeProfile(selected.profile.runtimeProfileId);setSelected(authoritative);setRecovery({state:runtimeControlledState(error),reason:error.reasonCode,attemptedVersion,authoritative,safeDraft:form});setState("READY");return}catch(fetchReason){fail(fetchReason);return}}fail(error)}finally{actionInFlight.current=false}}
 const filtered=useMemo(()=>items.filter(item=>(filter==="ALL"||item.profile.lifecycleState===filter)&&`${item.profile.name} ${item.profile.runtimeProfileId}`.toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
 const profile=selected?.profile,draft=profile?.revisions.find(item=>item.revisionId===profile.currentDraftRevisionId),review=profile?.reviews.at(-1),active=draft??profile?.revisions.find(item=>item.revisionId===profile?.publishedRevisionId),pair=profile?.revisions.slice(-2)??[];
 return <main className="module-workbench resource-management"><header><p className="eyebrow">企业 Runtime 资源工作台</p><h1>运行配置中心</h1><p>治理 Runtime Profile 声明；不推断 Pod、Placement、Runtime Instance、执行、OpenClaw 健康或模型能力。</p></header>{state==="LOADING"&&<p role="status">正在读取权威 Runtime Profile…</p>}{state==="SAVING"&&<p role="status">正在保存受治理的 Runtime Profile…</p>}{failure&&<section role="alert" aria-label={`${failure.state} state`}><h2>{failure.state}</h2><p>{failure.state==="denied"||failure.state==="not found"?"Runtime Profile 不可用或当前访问未获授权。":failure.reason}</p><button onClick={()=>void refresh(profile?.runtimeProfileId)}>重新读取权威数据</button></section>}{recovery&&<section role="alert" aria-label="Guided conflict recovery"><h2>{recovery.state}: 需要明确恢复操作</h2><dl><dt>尝试的聚合版本</dt><dd>{recovery.attemptedVersion}</dd><dt>权威聚合版本</dt><dd>{recovery.authoritative.profile.aggregateVersion}</dd><dt>权威修订</dt><dd>{recovery.authoritative.profile.revisions.at(-1)?.revisionId}</dd></dl><p>已重新读取权威声明；没有重放生命周期命令，也没有更改 Runtime Instance。</p>{recovery.safeDraft?<button onClick={()=>{setForm(recovery.safeDraft);setFormName(recovery.authoritative.profile.name);setRecovery(null)}}>明确恢复保留的 Profile 输入</button>:<button onClick={()=>setRecovery(null)}>确认权威版本</button>}<button onClick={()=>{setForm(null);setRecovery(null)}}>放弃保留输入</button></section>}
 <section className="module-dashboard" aria-label="Runtime Profile dashboard"><article><strong>{items.length}</strong><span>Profiles</span></article><article><strong>{items.filter(x=>x.profile.lifecycleState==="PUBLISHED").length}</strong><span>Published declarations</span></article><article><strong>{items.filter(x=>x.profile.currentDraftRevisionId).length}</strong><span>Drafts</span></article></section>
 {form?<section aria-label="Runtime Profile authoring"><RuntimeProfileForm name={formName} content={form} onName={setFormName} onChange={setForm}/><div className="module-actions"><button disabled={state==="SAVING"||!formName.trim()} onClick={()=>void save()}>保存 Runtime Profile Draft</button><button onClick={()=>setForm(null)}>取消</button></div></section>:<div className="module-actions"><button onClick={()=>startCreate("NATIVE_KUBERNETES")}>Create Native Kubernetes Profile</button><button onClick={()=>startCreate("OPENCLAW")}>Create bounded OpenClaw Profile</button></div>}
 <div className="module-layout"><aside><h2>Runtime Profile Catalog</h2><label>搜索 Profile<input aria-label="搜索 Runtime Profile" value={query} onChange={event=>{setQuery(event.target.value);preserveContext({query:event.target.value||null})}}/></label><label>生命周期筛选<select aria-label="Runtime Profile 生命周期筛选" value={filter} onChange={event=>{setFilter(event.target.value);preserveContext({lifecycle:event.target.value==="ALL"?null:event.target.value})}}><option>ALL</option><option>DRAFT</option><option>VALIDATED</option><option>HUMAN_REVIEWED</option><option>PUBLISHED</option></select></label>{filtered.length===0&&state==="READY"?<p>No Runtime Profiles yet.</p>:filtered.map(item=><button className={profile?.runtimeProfileId===item.profile.runtimeProfileId?"selected":""} key={item.profile.runtimeProfileId} onClick={()=>void refresh(item.profile.runtimeProfileId)}><strong>{item.profile.name}</strong><span>{item.profile.lifecycleState}</span></button>)}</aside>
 <section>{!profile?<div className="empty-state"><h2>Select a Runtime Profile</h2><p>Requests、limits、isolation、state、affinity 与声明限制显示在这里。</p></div>:<><header><p className="eyebrow">{profile.lifecycleState}</p><h2>{profile.name}</h2><span className="technical-value">{profile.runtimeProfileId}</span></header>{active&&<section className="workbench-card"><h3>{active.content.provider} declaration</h3><dl><dt>CPU request → limit</dt><dd>{active.content.resources.cpuRequest} → {active.content.resources.cpuLimit}</dd><dt>Memory request → limit</dt><dd>{active.content.resources.memoryRequest} → {active.content.resources.memoryLimit}</dd><dt>Isolation declaration</dt><dd>{active.content.isolation}</dd><dt>State mode</dt><dd>{active.content.stateMode}</dd><dt>Session affinity</dt><dd>{active.content.sessionAffinity}</dd><dt>Secret References</dt><dd>{active.content.secretReferences.join(", ")||"NONE"}</dd><dt>Model verification</dt><dd>UNVERIFIED</dd><dt>Execution / placement authority</dt><dd>NOT_GRANTED</dd></dl><label>Exact revision digest<input readOnly value={active.digest}/></label>{draft&&<div className="module-actions"><button onClick={startEdit}>编辑当前 Profile Draft</button>{draft.state==="DRAFT"&&<button onClick={()=>void act(x=>validateRuntimeProfile(x.runtimeProfileId,x.aggregateVersion))}>Validate Runtime Profile</button>}{draft.state==="VALIDATED"&&<button onClick={()=>void act(x=>reviewRuntimeProfile(x.runtimeProfileId,x.aggregateVersion,draft.digest))}>Review exact Runtime digest</button>}{draft.state==="HUMAN_REVIEWED"&&review&&<button onClick={()=>void act(x=>publishRuntimeProfile(x.runtimeProfileId,x.aggregateVersion,draft.digest,review.reviewId))}>Publish immutable Runtime Profile</button>}</div>}<h4>Lifecycle Evidence</h4><p>Validation: {draft?.state!=="DRAFT"?"RECORDED":"REQUIRED"} · Human review: {review?.reviewId??"REQUIRED"} · Publication: {profile.publishedRevisionId??"NOT_PUBLISHED"}</p></section>}{profile.publishedRevisionId&&!profile.currentDraftRevisionId&&<button onClick={()=>void act(x=>successorRuntimeProfile(x.runtimeProfileId,x.aggregateVersion))}>Create Runtime successor</button>}<section aria-label="Runtime Profile comparison"><h3>Revision comparison</h3>{pair.length===2?<><p><span className="technical-value">{pair[0].revisionId}</span> → <span className="technical-value">{pair[1].revisionId}</span></p><pre className="technical-value">{JSON.stringify({before:pair[0].content,after:pair[1].content},null,2)}</pre></>:<p>No successor comparison is available yet.</p>}<h3>History</h3><ol>{profile.revisions.map(item=><li key={item.revisionId}>{item.state} · <span className="technical-value">{item.revisionId}</span> · digest {item.digest}</li>)}</ol></section><RuntimeProfileTechnicalProjection projection={selected}/></>}</section></div></main>;
}
