import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {getProductDashboard,listAttention,listDigitalEmployeeTemplates,type AttentionItem,type DigitalEmployeeTemplate,type ProductDashboard} from "../api/productAssembly";
import {listProblems,type ProblemPlan} from "../api/problemPlanning";

type HomeData={dashboard:ProductDashboard|null;employees:DigitalEmployeeTemplate[]|null;problems:ProblemPlan[]|null;attention:AttentionItem[]|null};
const kinds:Record<string,[string,string]>={AGENT:["数字员工定义","A"],SKILL:["技能","S"],MCP:["MCP 与工具","M"],KNOWLEDGE:["知识","K"],WORKFLOW:["工作流","W"],RUNTIME_PROFILE:["运行配置","R"]};
const entries=[["/problems","问","新建业务问题","明确目标并形成可审核计划"],["/work","工","业务工作台","查看计划、人工介入与资源状态"],["/digital-employees","员","数字员工","查看已配置的定义模板"],["/catalog","能","能力资源","查找 Skill、MCP 和工作流"],["/knowledge","知","知识","检查知识来源和引用"],["/runtime-profiles","运","运行环境","查看 Runtime Profile"]];
function WorkStatus({problem}:{problem:ProblemPlan}){if(problem.approval)return <span className="px-status success">计划已批准</span>;if(problem.status.includes("FAIL"))return <span className="px-status danger">执行失败</span>;return <span className="px-status warning">等待人工处理</span>}

export function ProductDashboardPage(){
  const [data,setData]=useState<HomeData|null>(null);
  useEffect(()=>{let active=true;Promise.all([getProductDashboard().catch(()=>null),listDigitalEmployeeTemplates().catch(()=>null),listProblems().catch(()=>null),listAttention().catch(()=>null)]).then(([dashboard,employees,problems,attention])=>{if(active)setData({dashboard,employees,problems,attention})});return()=>{active=false}},[]);
  return <main className="px-page px-home">
    <h2 className="sr-only">Dashboard</h2>
    <header className="px-page-title"><div><p>产品首页 <small>Product Home</small></p><h1>把业务问题交给可信的数字员工</h1><span>从成功标准、受治理计划到可核验证据，让每一步都清楚可见。</span></div><Link className="px-primary-button" to="/problems">提出业务问题</Link></header>
    {!data?<section className="px-state" role="status"><span className="px-spinner"/><strong>正在读取授权信息</strong></section>:<>
      <section className="px-hero"><div><span className="px-eyebrow">企业智能体生命周期平台</span><h2>从问题出发，以结果收尾</h2><p>Digital Employee 是业务执行主体；能力、知识、工作流和运行环境均在治理边界内装配和使用。</p><div className="px-journey"><span>业务问题</span><i>→</i><span>数字员工</span><i>→</i><span>批准计划</span><i>→</i><span>证据与结果</span></div></div><div className="px-hero-mark" aria-hidden="true"><span>A</span><i/><i/><i/></div></section>
      <section className="px-summary" aria-label="真实产品摘要"><Summary to="/catalog" label="授权资源" value={data.dashboard?.resourceCount} note="来自持久化产品投影"/><Summary to="/attention" label="待处理事项" value={data.attention?.length} note="需要人工关注"/><Summary to="/digital-employees" label="数字员工模板" value={data.employees?.length} note="模板不代表运行实例"/><Summary to="/work" label="业务问题记录" value={data.problems?.length} note="来自规划服务"/></section>
      <section className="px-section"><Heading eyebrow="快速开始" title="常用入口"/><div className="px-quick-grid">{entries.map(([to,icon,title,copy])=><Link key={to} to={to}><b>{icon}</b><span><strong>{title}</strong><small>{copy}</small></span><i>›</i></Link>)}</div></section>
      <div className="px-home-grid"><section className="px-section"><Heading eyebrow="需要我处理" title="待处理事项" to="/attention"/>{data.attention===null?<Unavailable copy="待处理事项投影暂不可用。"/>:data.attention.length?<ul className="px-list">{data.attention.slice(0,4).map(item=><li key={`${item.kind}:${item.identity}`}><span className="px-status warning">待处理</span><div><strong>{item.identity}</strong><small>{item.reason}</small></div><Link to={item.deepLink}>查看</Link></li>)}</ul>:<Empty title="当前没有待处理事项" copy="这里只展示授权投影返回的真实事项。"/>}</section>
      <section className="px-section"><Heading eyebrow="最近工作" title="业务问题与计划" to="/work"/>{data.problems===null?<Unavailable copy="业务问题投影暂不可用。"/>:data.problems.length?<ul className="px-list">{[...data.problems].reverse().slice(0,4).map(problem=><li key={problem.problemId}><WorkStatus problem={problem}/><div><strong>{problem.name}</strong><small>{problem.displayCode} · {problem.planRevisions.length} 个计划修订</small></div><Link to={`/work?problem=${encodeURIComponent(problem.problemId)}`}>打开</Link></li>)}</ul>:<Empty title="尚无业务问题记录" copy="提出第一个真实问题后，这里会显示其计划状态。"/>}</section></div>
      <section className="px-section"><Heading eyebrow="数字员工" title="已配置的业务角色" to="/digital-employees"/>{data.employees===null?<Unavailable copy="数字员工模板投影暂不可用。"/>:data.employees.length?<div className="px-employee-grid">{data.employees.slice(0,3).map(item=><article key={item.templateId}><span className="px-avatar">{item.name.slice(0,1)}</span><div><span className="px-status info">定义模板</span><h3>{item.name}</h3><p>{item.purpose}</p><small>{item.composition.length} 项组合绑定 · 无执行权限</small></div><Link to={item.deepLink}>查看定义</Link></article>)}</div>:<Empty title="尚无数字员工模板" copy="系统不会用示例人物或虚构实例填充此区域。"/>}</section>
      <section className="px-section"><Heading eyebrow="能力与资源" title="授权资源可用性" to="/catalog"/>{data.dashboard?<div className="px-capability-grid">{Object.entries(kinds).map(([kind,[label,mark]])=><Link key={kind} to={`/catalog?kind=${kind}`}><b>{mark}</b><strong>{data.dashboard!.countsByKind[kind]??0}</strong><span>{label}</span></Link>)}</div>:<Unavailable copy="资源聚合投影暂不可用；不显示推测数量。"/>}</section>
      <div className="px-home-grid"><section className="px-section"><Heading eyebrow="最近证据与结果" title="Evidence / Outcome"/><Unavailable copy="首页尚无跨执行聚合投影。请从具体工作记录检查真实证据。"/></section><section id="planned" className="px-section"><Heading eyebrow="产品演进" title="v0.3 规划能力"/><ul className="px-planned"><li><span/>成本与用量治理<small>规划中 · 当前不显示 Token、费用或趋势</small></li><li><span/>模型管理与评估<small>规划中 · 当前无企业模型目录</small></li><li><span/>完整 Fleet 运营<small>建设中 · 当前无跨运行环境聚合</small></li></ul></section></div>
    </>}
  </main>
}
function Summary({to,label,value,note}:{to:string;label:string;value:number|undefined;note:string}){return <Link to={to}><span>{label}</span><strong>{value??"—"}</strong><small>{value===undefined?"暂不可用":note}</small></Link>}
function Heading({eyebrow,title,to}:{eyebrow:string;title:string;to?:string}){return <div className="px-section-heading"><div><span className="px-eyebrow">{eyebrow}</span><h2>{title}</h2></div>{to&&<Link to={to}>查看全部</Link>}</div>}
function Empty({title,copy}:{title:string;copy:string}){return <div className="px-empty"><strong>{title}</strong><p>{copy}</p></div>}
function Unavailable({copy}:{copy:string}){return <div className="px-empty"><span className="px-status neutral">暂不可用</span><p>{copy}</p></div>}
