"""Public surface of the internal, unfrozen v0.2 representation package."""

from .domain import (
    AgentDefinitionProjection,
    AgentDefinitionRef,
    AgentInstance,
    AgentInstanceId,
    AgentInstanceLifecycle,
    DefinitionFacingTaskTarget,
    DesiredRuntimeBinding,
    EffectiveRuntimeBinding,
    ExecutionIdentityRecord,
    NativeCorrelationId,
    NativeRealizationEvidence,
    PlatformExecutionIdentity,
    RuntimeBinding,
    SelectedInstanceEvidence,
    mint_agent_instance_id,
    mint_platform_execution_identity,
)
from .errors import (
    CoreRepresentationError,
    DefinitionOwnershipConflictError,
    DuplicateInstanceError,
    InstanceNotFoundError,
    InvalidBindingError,
    InvalidDomainValueError,
    InvalidNativeEvidenceError,
)
from .serialization import (
    SCHEMA_VERSION,
    agent_instance_from_dict,
    agent_instance_to_dict,
    execution_identity_from_dict,
    execution_identity_to_dict,
)

__all__ = [
    "SCHEMA_VERSION",
    "AgentDefinitionProjection",
    "AgentDefinitionRef",
    "AgentInstance",
    "AgentInstanceId",
    "AgentInstanceLifecycle",
    "CoreRepresentationError",
    "DefinitionFacingTaskTarget",
    "DefinitionOwnershipConflictError",
    "DesiredRuntimeBinding",
    "DuplicateInstanceError",
    "EffectiveRuntimeBinding",
    "ExecutionIdentityRecord",
    "InstanceNotFoundError",
    "InvalidBindingError",
    "InvalidDomainValueError",
    "InvalidNativeEvidenceError",
    "NativeCorrelationId",
    "NativeRealizationEvidence",
    "PlatformExecutionIdentity",
    "RuntimeBinding",
    "SelectedInstanceEvidence",
    "agent_instance_from_dict",
    "agent_instance_to_dict",
    "execution_identity_from_dict",
    "execution_identity_to_dict",
    "mint_agent_instance_id",
    "mint_platform_execution_identity",
]
