export type EmployeeMember={kind:"AGENT"|"WORKFLOW"|"SKILL"|"MCP"|"KNOWLEDGE"|"RUNTIME_PROFILE";resourceId:string;revisionId:string;digest:string};
export type EmployeeFact={action:string;decisionId:string;ordinal:number};
export type EmployeeDefinition={resourceKind:"DIGITAL_EMPLOYEE_DEFINITION";employeeDefinitionId:string;employeeDefinitionRevisionId:string;employeeDefinitionDigest:string;aggregateVersion:number;role:string;responsibilities:string[];members:EmployeeMember[];predecessorEmployeeRevisionId:string|null;published:boolean;matchable:boolean;facts:EmployeeFact[]};
export type EmployeeInstance={instanceId:string;version:number;employeeDefinition?:{authorityKind:string;employeeDefinitionId:string;employeeDefinitionRevisionId:string;digest:string};legacyDefinitionReference?:{authorityKind:string;employeeDefinitionId:string;employeeDefinitionRevisionId:string;digest:string};ownerId:string;organizationId:string;lifecycle:string;workspaceReference:string|null;modelReference:string|null;policyReferences:string[];relationships:unknown;createdAt:string;updatedAt:string;disposition?:string;execution:{state:string;reasonCode:string};health:{state:string;reasonCode:string}};
export type EmployeeAssignment={assignmentId:string;instanceId:string;assigneeId:string;businessRole:string;lifecycle:string;effectiveFrom:string;effectiveUntil:string|null;version:number;commandId?:string;disposition?:string;binding?:{state:string;reasonCode:string}};
export type EmployeePlacement={placementId:string;requestId:string;decision:string;runtimeInstanceId:string;policyVersion:string;compatibilityFacts:string[];limitationCodes:string[];decidedAt:string;digest:string;observation?:{freshness:"CURRENT"|"STALE"|"UNOBSERVED";observationId:string|null};execution:{state:string;reasonCode:string};outcome:{state:string;reasonCode:string};disposition?:string};
export type EmployeePlacementReadContext={instanceId:string;assignmentId:string;placementId:string;attemptId:string;agentInstanceId:string};
export type EmployeeCreateInput={employeeDefinitionId:string;employeeDefinitionRevisionId:string;role:string;responsibilities:string[];members:EmployeeMember[];predecessorEmployeeRevisionId?:string;expectedVersion:number;commandId:string};
export class DigitalEmployeeRequestError extends Error{reasonCode:string;status:number;constructor(reasonCode:string,status:number){super(reasonCode);this.reasonCode=reasonCode;this.status=status}}
export type EmployeeControlledState="validation error"|"denied"|"not found"|"stale"|"conflict"|"backend unavailable"|"retryable";
export const employeeControlledState=(error:DigitalEmployeeRequestError):EmployeeControlledState=>error.status===401||error.status===403?"denied":error.status===404?"not found":error.status===409?(error.reasonCode.includes("STALE")?"stale":"conflict"):error.status===422?"validation error":error.status>=500?"backend unavailable":"retryable";
const headers=()=>({Accept:"application/json","Content-Type":"application/json","X-Tenant-ID":import.meta.env.VITE_DIGITAL_EMPLOYEE_TENANT_ID??"tenant-a","X-Security-Domain":import.meta.env.VITE_DIGITAL_EMPLOYEE_SECURITY_DOMAIN??"supplier-quality","X-Principal-ID":import.meta.env.VITE_DIGITAL_EMPLOYEE_PRINCIPAL_ID??"console-user"});
async function request<T>(path:string,init?:RequestInit,signal?:AbortSignal):Promise<T>{let response:Response;try{response=await fetch(path,{...init,signal,headers:{...headers(),...init?.headers}})}catch(error){if(error instanceof DOMException&&error.name==="AbortError")throw error;throw new DigitalEmployeeRequestError("DIGITAL_EMPLOYEE_NETWORK_UNAVAILABLE",503)}const body=await response.json().catch(()=>null);if(!response.ok)throw new DigitalEmployeeRequestError(body?.detail?.reasonCode??"DIGITAL_EMPLOYEE_UNAVAILABLE",response.status);return body as T}
const root="/api/internal/v0.2.3/digital-employees";
export const listEmployeeDefinitions=(signal?:AbortSignal)=>request<EmployeeDefinition[]>(`${root}/definitions`,undefined,signal);
export const getEmployeeDefinition=(id:string,revisionId:string,signal?:AbortSignal)=>request<EmployeeDefinition>(`${root}/definitions/${encodeURIComponent(id)}?${new URLSearchParams({employeeDefinitionRevisionId:revisionId})}`,undefined,signal);
export const createEmployeeDefinition=(input:EmployeeCreateInput)=>request<EmployeeDefinition>(`${root}/definitions`,{method:"POST",body:JSON.stringify(input)});
export const decideEmployeeDefinition=(value:EmployeeDefinition,action:"validate"|"approve"|"publish")=>request<EmployeeDefinition>(`${root}/definitions/${encodeURIComponent(value.employeeDefinitionId)}/${action}`,{method:"POST",body:JSON.stringify({employeeDefinitionRevisionId:value.employeeDefinitionRevisionId,employeeDefinitionDigest:value.employeeDefinitionDigest,expectedVersion:value.aggregateVersion,commandId:`${action}:${crypto.randomUUID()}`})});
export const createEmployeeInstance=(value:EmployeeDefinition,instanceId:string)=>request<EmployeeInstance>(`${root}/instances`,{method:"POST",body:JSON.stringify({instanceId,employeeDefinitionId:value.employeeDefinitionId,employeeDefinitionRevisionId:value.employeeDefinitionRevisionId,commandId:`instantiate:${crypto.randomUUID()}`})});
export const getEmployeeInstance=(id:string,signal?:AbortSignal)=>request<EmployeeInstance>(`${root}/instances/${encodeURIComponent(id)}`,undefined,signal);
export const createEmployeeAssignment=(instanceId:string,input:{assignmentId:string;assigneeId:string;businessRole:string;effectiveFrom:string;effectiveUntil?:string})=>request<EmployeeAssignment>(`${root}/instances/${encodeURIComponent(instanceId)}/assignments`,{method:"POST",body:JSON.stringify({...input,commandId:`assign:${crypto.randomUUID()}`})});
export const getEmployeeAssignment=(instanceId:string,assignmentId:string,signal?:AbortSignal)=>request<EmployeeAssignment>(`${root}/instances/${encodeURIComponent(instanceId)}/assignments/${encodeURIComponent(assignmentId)}`,undefined,signal);
export const getEmployeePlacement=(context:EmployeePlacementReadContext,signal?:AbortSignal)=>request<EmployeePlacement>(`${root}/instances/${encodeURIComponent(context.instanceId)}/assignments/${encodeURIComponent(context.assignmentId)}/placements/${encodeURIComponent(context.placementId)}?${new URLSearchParams({attemptId:context.attemptId,agentInstanceId:context.agentInstanceId})}`,undefined,signal);
