export type PlanTask={taskId:string;displayCode:string;name:string;description:string;revision:number;lifecycle:string;provenance:string;dependencies:string[];role:string;agentRevision:string;skillRevisions:string[];mcpRevisions:string[];knowledgeSnapshotId:string;runtimeRequirements:string[];inputs:string[];outputs:string[];approvalRequirements:string[];expectedEvidence:string[];validationCriteria:string[];candidateMatches:{digitalEmployees:string[];agentRevisions:string[];skillRevisions:string[];mcpOperations:string[];knowledgeSnapshots:string[];runtimeRequirements:string[]}};
export type Citation={citationId:string;documentRevisionId:string;documentTitle:string;documentVersion:string;chunkId:string;chunkDigest:string;excerpt:string;denseRank:number|null;denseScore:number|null;lexicalScore:number;influence:string;selectionReason:string;affectedTasks:string[]};
export type CapabilityGap={state:string;description:string;missingCapability?:string;impact?:string;recommendedAction?:string;targetVersion?:string};
export type PlanRevision={planId:string;planRevisionId:string;displayCode:string;revision:number;status:string;approvalState:string;createdAt:string;updatedAt:string;knowledgeSnapshotId:string;capabilityGapCount:number;canonicalDigest:string;summary:string;classification:string;tasks:PlanTask[];capabilityGaps:CapabilityGap[];limitations:string[];humanChangeSet?:{evidenceId:string;kind:string;reason:string;changes:{field:string;previous:unknown;new:unknown}[];affectedTaskIds:string[];previousRevisionId:string};provenance:{provider:string;model:string;promptTemplateRevision:string;schemaValidation:string;ruleValidation:string}};
export type Blueprint={blueprintId?:string;name?:string;purpose?:string;state:string;description?:string;visibleReusableComponents?:string[];matchedAgents?:string[];matchedSkills?:string[];matchedMcpOperations?:string[];matchedKnowledge?:string[];runtimeRequirements?:string[];authorizationPrerequisites?:string[];supportReason?:string;planImpact?:string;recommendedAction?:string;targetVersion?:string};
export type ProblemPlan={problemId:string;displayCode:string;name:string;description:string;revision:number;status:string;provenance:string;createdAt:string;updatedAt:string;tenantId:string;securityDomain:string;principalId:string;currentPlanRevisionId:string;planRevisions:PlanRevision[];planningAttempts:{attemptId:string;displayCode:string;state:string;createdAt:string;knowledgeMode:string}[];clarificationAttempts:{streamId:string;response:Record<string,unknown>;submittedAt:string;state:string}[];interpretations:{revision:number;supplierScope:string;timeRange:string;improvementIndicator:string;summary:string;createdAt:string;source:string}[];humanDecisions:{evidenceId:string;kind:string;reason:string;changes:{field:string;previous:unknown;new:unknown}[];planRevisionId:string;canonicalDigest:string}[];knowledge:{knowledgeBaseId:string;indexSnapshotId:string;indexManifestDigest:string;retrievalState:string;selectedCitationIds:string[];citations:Citation[]};selectedBlueprintId:string|null;blueprints:Blueprint[];events:{eventId:string;eventType:string;sequence:number;eventDigest:string;previousEventDigest:string;classification:string;occurredAt:string}[];approval:null|{approvalId:string;planRevisionId:string;canonicalDigest:string;state:string;approvedAt:string;evidence:{evidenceId:string;type:string;planRevisionId:string;canonicalDigest:string}};dispatchBoundary?:{state:string;reason:string;prerequisites:string[];unresolvedGaps:CapabilityGap[]};timings:{problemAcceptanceMs:number;retrievalMs:number;controlledModelPlanningMs:number;schemaAndRuleValidationMs:number;comparisonAssemblyMs:number;totalMs:number}};
export type AnalysisEvent={schemaVersion:string;streamId:string;eventId:string;sequence:number;occurredAt:string;eventType:string;stage:string;status:string;classification:"PARTIAL"|"FORMAL";terminal:boolean;previousEventDigest:string;eventDigest:string;correlationId:string;causationId:string;actor:string;payload:Record<string,unknown>};

export class PlanningRequestError extends Error{readonly reasonCode:string;readonly status:number;constructor(reasonCode:string,status:number){super(reasonCode);this.reasonCode=reasonCode;this.status=status}}
async function request<T>(path:string,init?:RequestInit,timeoutMs=180000):Promise<T>{
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);
  try{const response=await fetch(path,{...init,signal:controller.signal,headers:{Accept:"application/json","Content-Type":"application/json",...(init?.headers??{})}});const body=await response.json().catch(()=>null);if(!response.ok)throw new PlanningRequestError(body?.detail?.reasonCode??"PROBLEM_PLANNING_UNAVAILABLE",response.status);return body as T}catch(reason){if(reason instanceof PlanningRequestError)throw reason;if(controller.signal.aborted)throw new PlanningRequestError("PLANNING_TIMEOUT",504);throw new PlanningRequestError("PLANNING_NETWORK_UNAVAILABLE",503)}finally{clearTimeout(timer)}
}
export const listProblems=()=>request<ProblemPlan[]>("/api/internal/v0.2.1/problems",undefined,15000);
export const getProblem=(id:string)=>request<ProblemPlan>(`/api/internal/v0.2.1/problems/${encodeURIComponent(id)}`,undefined,15000);
export function createProblem(includeNewKnowledge:boolean,description:string){return request<ProblemPlan>("/api/internal/v0.2.1/problems",{method:"POST",body:JSON.stringify({name:"供应商质量下降分析与整改",description,includeNewKnowledge})})}
export function correctProblem(problem:ProblemPlan,summary:string){const current=problem.planRevisions.at(-1)!;return request<ProblemPlan>(`/api/internal/v0.2.1/problems/${encodeURIComponent(problem.problemId)}/corrections`,{method:"POST",body:JSON.stringify({predecessorDigest:current.canonicalDigest,summary,reason:"人工修订计划解释与验证门槛"})},30000)}
export function interveneProblem(problem:ProblemPlan,kind:string,reason:string,payload:Record<string,unknown>){const current=problem.planRevisions.at(-1)!;return request<ProblemPlan>(`/api/internal/v0.2.1/problems/${encodeURIComponent(problem.problemId)}/interventions`,{method:"POST",body:JSON.stringify({predecessorDigest:current.canonicalDigest,kind,reason,payload})},30000)}
export function approveProblem(problem:ProblemPlan){const current=problem.planRevisions.at(-1)!;return request<ProblemPlan>(`/api/internal/v0.2.1/problems/${encodeURIComponent(problem.problemId)}/approvals`,{method:"POST",body:JSON.stringify({planRevisionId:current.planRevisionId,canonicalDigest:current.canonicalDigest})},30000)}

async function stream(path:string,body:Record<string,unknown>,onEvent:(event:AnalysisEvent)=>void){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),180000);try{const response=await fetch(path,{method:"POST",signal:controller.signal,headers:{Accept:"text/event-stream","Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok||!response.body){const failure=await response.json().catch(()=>null);throw new PlanningRequestError(failure?.detail?.reasonCode??"ANALYSIS_STREAM_UNAVAILABLE",response.status)}const reader=response.body.getReader();const decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value??new Uint8Array(),{stream:!done});let boundary=buffer.indexOf("\n\n");while(boundary>=0){const frame=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);const data=frame.split("\n").find(line=>line.startsWith("data: "))?.slice(6);if(data)onEvent(JSON.parse(data) as AnalysisEvent);boundary=buffer.indexOf("\n\n")}if(done)break}}catch(reason){if(reason instanceof PlanningRequestError)throw reason;if(controller.signal.aborted)throw new PlanningRequestError("PLANNING_TIMEOUT",504);throw new PlanningRequestError("PLANNING_NETWORK_UNAVAILABLE",503)}finally{clearTimeout(timer)}}
export const beginProblemAnalysis=(description:string,onEvent:(event:AnalysisEvent)=>void)=>stream("/api/internal/v0.2.1/problem-analysis-streams",{name:"供应商质量下降分析与整改",description,includeNewKnowledge:true},onEvent);
export const resumeProblemAnalysis=(streamId:string,response:Record<string,unknown>,onEvent:(event:AnalysisEvent)=>void)=>stream(`/api/internal/v0.2.1/problem-analysis-streams/${encodeURIComponent(streamId)}/resume`,response,onEvent);
export async function replayProblemAnalysis(streamId:string,onEvent:(event:AnalysisEvent)=>void,lastEventId?:string){const response=await fetch(`/api/internal/v0.2.1/problem-analysis-streams/${encodeURIComponent(streamId)}/events`,{headers:{Accept:"text/event-stream",...(lastEventId?{"Last-Event-ID":lastEventId}:{})}});if(!response.ok||!response.body)throw new PlanningRequestError("ANALYSIS_RESUME_UNAVAILABLE",response.status);const reader=response.body.getReader();const decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value??new Uint8Array(),{stream:!done});let boundary=buffer.indexOf("\n\n");while(boundary>=0){const frame=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);const data=frame.split("\n").find(line=>line.startsWith("data: "))?.slice(6);if(data)onEvent(JSON.parse(data) as AnalysisEvent);boundary=buffer.indexOf("\n\n")}if(done)break}}
