export type ResourceKind = "skill" | "mcp";
export type ResourceContent = { description: string; capabilities: string[]; instructions?: string | null; endpoint?: string | null };
export type ResourceRevision = { revisionId:string; predecessorRevisionId:string|null; state:string; digest:string; content:ResourceContent; createdAt:string };
export type SkillMcpResource = { resourceId:string; kind:ResourceKind; name:string; aggregateVersion:number; lifecycleState:string; enabled:boolean; archived:boolean; currentDraftRevisionId:string|null; publishedRevisionId:string|null; revisions:ResourceRevision[]; reviews:Array<{reviewId:string;digest:string}>; relationships:unknown[]; bindings:Array<{bindingId:string;mcpResourceId:string;mcpRevisionId:string;skillRevisionId:string;capability:string}>; invocations:unknown[]; limitations:string[] };
export type ResourceProjection = { resource:SkillMcpResource; productProjection:Record<string,unknown>; technicalProjection:Record<string,unknown>; invocation?:{status:string;result:unknown;evidence:{redacted:boolean}} };

export class SkillMcpRequestError extends Error { reasonCode:string;status:number;constructor(reasonCode:string,status:number){super(reasonCode);this.reasonCode=reasonCode;this.status=status} }
async function request<T>(path:string, init?:RequestInit):Promise<T>{let response:Response;try{response=await fetch(path,{...init,headers:{Accept:"application/json","Content-Type":"application/json",...init?.headers}})}catch{throw new SkillMcpRequestError("SKILL_MCP_NETWORK_UNAVAILABLE",503)}const body=await response.json().catch(()=>null);if(!response.ok)throw new SkillMcpRequestError(body?.detail?.reasonCode??"SKILL_MCP_UNAVAILABLE",response.status);return body as T}
const root="/api/internal/v0.2.2/resources";
export const listResources=(kind:ResourceKind)=>request<SkillMcpResource[]>(`${root}/${kind}`);
export const getResource=(kind:ResourceKind,id:string)=>request<ResourceProjection>(`${root}/${kind}/${encodeURIComponent(id)}`);
export const createResource=(kind:ResourceKind,name:string,content:ResourceContent)=>request<ResourceProjection>(`${root}/${kind}`,{method:"POST",body:JSON.stringify({name,content})});
export const validateResource=(kind:ResourceKind,id:string,expectedVersion:number)=>request<ResourceProjection>(`${root}/${kind}/${id}/validation`,{method:"POST",body:JSON.stringify({expectedVersion})});
export const reviewResource=(kind:ResourceKind,id:string,expectedVersion:number,digest:string)=>request<ResourceProjection>(`${root}/${kind}/${id}/reviews`,{method:"POST",body:JSON.stringify({expectedVersion,digest,decision:"APPROVE",reason:"Human reviewed the exact revision digest"})});
export const publishResource=(kind:ResourceKind,id:string,expectedVersion:number,digest:string,reviewId:string)=>request<ResourceProjection>(`${root}/${kind}/${id}/publications`,{method:"POST",body:JSON.stringify({expectedVersion,digest,reviewId})});
export const lifecycleResource=(kind:ResourceKind,id:string,action:string,expectedVersion:number)=>request<ResourceProjection>(`${root}/${kind}/${id}/${action.toLowerCase()}`,{method:"POST",body:JSON.stringify({expectedVersion,reason:`Human requested ${action}`})});
export const successorResource=(kind:ResourceKind,id:string,expectedVersion:number)=>request<ResourceProjection>(`${root}/${kind}/${id}/successors`,{method:"POST",body:JSON.stringify({expectedVersion})});
export const bindCapability=(skill:SkillMcpResource,mcp:SkillMcpResource,capability:string)=>request<ResourceProjection>(`${root}/skill/${skill.resourceId}/bindings`,{method:"POST",body:JSON.stringify({expectedVersion:skill.aggregateVersion,skillRevisionId:skill.publishedRevisionId,mcpResourceId:mcp.resourceId,mcpRevisionId:mcp.publishedRevisionId,capability,reason:"Human approved exact Skill-to-MCP capability binding"})});
export const invokeCapability=(skill:SkillMcpResource,bindingId:string)=>request<ResourceProjection>(`${root}/skill/${skill.resourceId}/invocations`,{method:"POST",body:JSON.stringify({expectedVersion:skill.aggregateVersion,bindingId,authorization:"ALLOW_BOUNDED_CAPABILITY_TEST",input:{probe:"bounded-workbench-test"}})});
