export type ExactReference={kind:"AGENT"|"SKILL"|"MCP"|"KNOWLEDGE"|"RUNTIME_PROFILE";resourceId:string;revisionId:string;digest?:string|null};
export type SkillOperationBinding={skillId:string;skillRevisionId:string;skillDigest:string;operation:string};
export type WorkflowTask={taskId:string;name:string;dependsOn:string[];inputs:string[];outputs:string[];capabilityRequirements:string[];references:ExactReference[];skillOperationBindings?:SkillOperationBinding[]|null;retryLimit:number;timeoutSeconds:number;failurePolicy:"FAIL_WORKFLOW"|"SKIP_DEPENDENTS"};
export const hasSkillOperationBindings=(task:WorkflowTask)=>Boolean(task.skillOperationBindings?.length);
export const referenceSupportsBinding=(task:WorkflowTask,binding:SkillOperationBinding)=>task.references.some(reference=>reference.kind==="SKILL"&&reference.resourceId===binding.skillId&&reference.revisionId===binding.skillRevisionId&&reference.digest===binding.skillDigest);
export type WorkflowContent={description:string;tasks:WorkflowTask[];inputs:string[];outputs:string[];runtimeProfile:ExactReference};
export type WorkflowRevision={revisionId:string;predecessorRevisionId:string|null;state:string;digest:string;content:WorkflowContent;createdAt:string};
export type WorkflowDefinition={workflowDefinitionId:string;name:string;aggregateVersion:number;lifecycleState:string;currentDraftRevisionId:string|null;publishedRevisionId:string|null;revisions:WorkflowRevision[];reviews:Array<{reviewId:string;digest:string}>;relationships:unknown[];consumers:unknown[]};
export type WorkflowProjection={definition:WorkflowDefinition;productProjection:Record<string,unknown>;technicalProjection:Record<string,unknown>};
export type WorkflowValidationIssue={path:Array<string|number>;code:string};
export class WorkflowDefinitionRequestError extends Error{reasonCode:string;status:number;validationIssues:WorkflowValidationIssue[];constructor(reasonCode:string,status:number,validationIssues:WorkflowValidationIssue[]=[]){super(reasonCode);this.reasonCode=reasonCode;this.status=status;this.validationIssues=validationIssues}}
export type WorkflowControlledState="validation error"|"denied"|"not found"|"conflict"|"stale"|"backend unavailable"|"partial"|"retryable"|"recovery required"|"unsupported";
export const workflowControlledState=(error:WorkflowDefinitionRequestError):WorkflowControlledState=>error.status===403?"denied":error.status===404?"not found":error.status===409?(error.reasonCode.includes("STALE")?"stale":"conflict"):error.status===422?"validation error":error.status===501?"unsupported":error.status>=500?"backend unavailable":"retryable";
const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const errorReason=(body:unknown)=>{if(!object(body))return "WORKFLOW_DEFINITION_UNAVAILABLE";const detail=body.detail;if(object(detail)&&typeof detail.reasonCode==="string")return detail.reasonCode;if(Array.isArray(detail)){const reason=detail.find(item=>object(item)&&typeof item.reasonCode==="string");if(object(reason)&&typeof reason.reasonCode==="string")return reason.reasonCode}return "WORKFLOW_DEFINITION_UNAVAILABLE"};
const validationIssues=(body:unknown):WorkflowValidationIssue[]=>{if(!object(body)||!Array.isArray(body.detail))return[];return body.detail.flatMap(item=>object(item)&&Array.isArray(item.loc)?[{path:item.loc.filter(value=>typeof value==="string"||typeof value==="number") as Array<string|number>,code:typeof item.type==="string"?item.type:"SCHEMA_VALIDATION_ERROR"}]:[])};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let response:Response;try{response=await fetch(path,{...init,headers:{Accept:"application/json","Content-Type":"application/json",...init?.headers}})}catch(reason){if(reason instanceof DOMException&&reason.name==="AbortError")throw reason;throw new WorkflowDefinitionRequestError("WORKFLOW_DEFINITION_NETWORK_UNAVAILABLE",503)}const body:unknown=await response.json().catch(()=>null);if(!response.ok)throw new WorkflowDefinitionRequestError(errorReason(body),response.status,validationIssues(body));return body as T}
const root="/api/internal/v0.2.2/workflow-definitions";
export const listWorkflowDefinitions=(signal?:AbortSignal)=>request<WorkflowProjection[]>(root,{signal});
export const getWorkflowDefinition=(id:string,signal?:AbortSignal)=>request<WorkflowProjection>(`${root}/${encodeURIComponent(id)}`,{signal});
export const createWorkflowDefinition=(name:string,content:WorkflowContent)=>request<WorkflowProjection>(root,{method:"POST",body:JSON.stringify({name,content})});
export const editWorkflowDefinition=(definition:WorkflowDefinition,content:WorkflowContent)=>request<WorkflowProjection>(`${root}/${encodeURIComponent(definition.workflowDefinitionId)}/draft`,{method:"PUT",body:JSON.stringify({expectedVersion:definition.aggregateVersion,content})});
export const validateWorkflowDefinition=(id:string,expectedVersion:number)=>request<WorkflowProjection>(`${root}/${encodeURIComponent(id)}/validation`,{method:"POST",body:JSON.stringify({expectedVersion})});
export const reviewWorkflowDefinition=(id:string,expectedVersion:number,digest:string)=>request<WorkflowProjection>(`${root}/${encodeURIComponent(id)}/reviews`,{method:"POST",body:JSON.stringify({expectedVersion,digest,decision:"APPROVE",reason:"Human reviewed exact Workflow digest"})});
export const publishWorkflowDefinition=(id:string,expectedVersion:number,digest:string,reviewId:string)=>request<WorkflowProjection>(`${root}/${encodeURIComponent(id)}/publications`,{method:"POST",body:JSON.stringify({expectedVersion,digest,reviewId})});
export const successorWorkflowDefinition=(id:string,expectedVersion:number)=>request<WorkflowProjection>(`${root}/${encodeURIComponent(id)}/successors`,{method:"POST",body:JSON.stringify({expectedVersion})});
export const compareWorkflowRevisions=(id:string,left:string,right:string)=>request<Record<string,unknown>>(`${root}/${encodeURIComponent(id)}/comparison?${new URLSearchParams({leftRevisionId:left,rightRevisionId:right})}`);
