import {useEffect,useMemo,useRef,useState} from "react";
import {Link,useLocation,useSearchParams} from "react-router-dom";
import {AgentDefinitionRequestError,agentControlledState,createAgentDefinition,editAgentDefinition,getAgentDefinition,lifecycleAgentDefinition,listAgentDefinitions,publishAgentDefinition,reviewAgentDefinition,successorAgentDefinition,validateAgentDefinition,type AgentDefinition,type AgentContent,type AgentProjection,type ControlledState} from "../api/agentDefinitions";
import {listResources} from "../api/skillMcpResources";
import {listKnowledge} from "../api/knowledgeResources";
import {listWorkflowDefinitions} from "../api/workflowDefinitions";
import {listRuntimeProfiles} from "../api/runtimeProfiles";
import {AgentTechnicalProjection} from "./AgentTechnicalProjection";
import {AgentBuilderPage,AgentBindingDetails,type AgentBindingOption} from "./AgentBuilderPage";
import {AgentVersionComparison} from "./AgentVersionComparison";

function published<T extends {revisionId:string;digest:string}>(revisions:T[],id:string|null){return revisions.find(item=>item.revisionId===id)}
// Agent binding DTOs use bare SHA-256 hex; these authorities return the sha256: scheme.
const bindingDigest=(digest:string)=>/^sha256:[0-9a-f]{64}$/.test(digest)?digest.slice(7):digest;
async function loadBindingOptions():Promise<AgentBindingOption[]>{const[skills,mcps,knowledge,workflows,runtimes]=await Promise.all([listResources("skill"),listResources("mcp"),listKnowledge(),listWorkflowDefinitions(),listRuntimeProfiles()]);return[
  ...skills.flatMap(item=>{const revision=published(item.revisions,item.publishedRevisionId);return revision&&item.enabled&&!item.archived&&item.lifecycleState!=="DEPRECATED"?[{kind:"skill" as const,resourceId:item.resourceId,name:item.name,revisionId:revision.revisionId,digest:revision.digest}]:[]}),
  ...mcps.flatMap(item=>{const revision=published(item.revisions,item.publishedRevisionId),selection=item.toolSelections.at(-1);return revision&&selection&&item.enabled&&!item.archived&&item.lifecycleState!=="DEPRECATED"?[{kind:"mcp" as const,resourceId:item.resourceId,name:item.name,revisionId:revision.revisionId,digest:revision.digest,tools:selection.toolNames,snapshots:[selection.snapshotId]}]:[]}),
  ...knowledge.flatMap(item=>{const revision=published(item.revisions,item.publishedRevisionId);return revision&&!item.archived&&item.lifecycleState!=="DEPRECATED"?[{kind:"knowledge" as const,resourceId:item.knowledgeId,name:item.name,revisionId:revision.revisionId,digest:revision.digest,snapshots:item.activeIndexSnapshotId?[item.activeIndexSnapshotId]:[]}]:[]}),
  ...workflows.flatMap(item=>{const revision=published(item.definition.revisions,item.definition.publishedRevisionId);return revision?[{kind:"workflow" as const,resourceId:item.definition.workflowDefinitionId,name:item.definition.name,revisionId:revision.revisionId,digest:bindingDigest(revision.digest)}]:[]}),
  ...runtimes.flatMap(item=>{const revision=published(item.profile.revisions,item.profile.publishedRevisionId);return revision?[{kind:"runtimeProfile" as const,resourceId:item.profile.runtimeProfileId,name:item.profile.name,revisionId:revision.revisionId,digest:bindingDigest(revision.digest)}]:[]}),
]}

export function AgentWorkbenchPage(){
  const[params,setParams]=useSearchParams(),location=useLocation();const[items,setItems]=useState<AgentDefinition[]>([]),[selected,setSelected]=useState<AgentProjection|null>(null),[options,setOptions]=useState<AgentBindingOption[]>([]);const[manifest,setManifest]=useState<string|null>(null),[state,setState]=useState<"LOADING"|"READY"|"SAVING"|"ERROR">("LOADING"),[error,setError]=useState<string|null>(null),[controlledState,setControlledState]=useState<ControlledState|null>(null),[recovery,setRecovery]=useState<{attemptedVersion:number;authoritative:AgentProjection}|null>(null),[authoring,setAuthoring]=useState<"create"|"edit"|null>(null);const[query,setQuery]=useState(params.get("query")??""),[filter,setFilter]=useState(params.get("lifecycle")??"ALL");const requestId=useRef(0),writeInFlight=useRef<symbol|null>(null),initialId=useRef(params.get("resourceId"));
  function context(patch:Record<string,string|null>){setParams(current=>{const next=new URLSearchParams(current);Object.entries(patch).forEach(([key,value])=>value?next.set(key,value):next.delete(key));return next},{replace:true})}
  function fail(reason:unknown){const failure=reason instanceof AgentDefinitionRequestError?reason:new AgentDefinitionRequestError("AGENT_DEFINITION_UNAVAILABLE",503);setControlledState(agentControlledState(failure));setError(failure.reasonCode);setState("ERROR")}
  function invalidate(){requestId.current+=1;writeInFlight.current=null;setRecovery(null);setError(null);setControlledState(null);setManifest(null);return requestId.current}
  async function refresh(id?:string,detail=true){const current=invalidate();setAuthoring(null);setSelected(null);setState("LOADING");try{const definitions=await listAgentDefinitions();if(current!==requestId.current)return;const projection=id&&detail?await getAgentDefinition(id):null;if(current!==requestId.current)return;setItems(definitions);if(projection){setSelected(projection);context({resourceId:id!})}setState("READY")}catch(reason){if(current===requestId.current)fail(reason)}}
  useEffect(()=>{const current=++requestId.current;Promise.all([listAgentDefinitions(),loadBindingOptions(),initialId.current?getAgentDefinition(initialId.current):Promise.resolve(null)]).then(([definitions,bindingOptions,detail])=>{if(current!==requestId.current)return;setItems(definitions);setOptions(bindingOptions);if(detail)setSelected(detail);setState("READY")}).catch(reason=>{if(current===requestId.current)fail(reason)});return()=>{requestId.current+=1;writeInFlight.current=null}},[]);
  async function write(operation:()=>Promise<AgentProjection>,closeAuthoring=false){
    if(writeInFlight.current)return;
    const current=requestId.current,atStart=selected?.definition,token=Symbol();
    const owns=()=>current===requestId.current&&writeInFlight.current===token;
    writeInFlight.current=token;setState("SAVING");
    try{
      const value=await operation();if(!owns())return;
      const definitions=await listAgentDefinitions();if(!owns())return;
      setSelected(value);setItems(definitions);context({resourceId:value.definition.definitionId});
      if(closeAuthoring)setAuthoring(null);setRecovery(null);setError(null);setControlledState(null);setState("READY");
    }catch(reason){
      if(!owns())return;
      if(reason instanceof AgentDefinitionRequestError&&reason.status===409&&atStart){
        try{const authoritative=await getAgentDefinition(atStart.definitionId);if(!owns())return;setSelected(authoritative);setRecovery({attemptedVersion:atStart.aggregateVersion,authoritative});setControlledState(agentControlledState(reason));setError(reason.reasonCode);setState("READY")}
        catch(fetchReason){if(owns())fail(fetchReason)}
      }else fail(reason);
    }finally{if(owns())writeInFlight.current=null}
  }
  async function save(name:string,content:AgentContent){
    if(authoring==="edit"&&selected){const target=selected.definition;await write(()=>editAgentDefinition(target.definitionId,target.aggregateVersion,content),true)}
    else if(authoring==="create")await write(()=>createAgentDefinition(name,content),true);
  }
  async function act(operation:(value:AgentDefinition)=>Promise<AgentProjection>){if(selected)await write(()=>operation(selected.definition))}
  const definition=selected?.definition,draft=definition?.revisions.find(item=>item.revisionId===definition.currentDraftRevisionId),review=definition?.reviews.find(item=>item.digest===draft?.digest),filtered=useMemo(()=>items.filter(item=>(filter==="ALL"||item.lifecycleState===filter)&&`${item.name} ${item.definitionId}`.toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
  return <main className="agent-workbench agent-management"><header className="agent-page-header"><div><p className="eyebrow">企业资源工作台 · Agent 管理中心</p><h1>Agent Workbench</h1><p>创建、验证、审查、发布并检查 canonical Agent Definition；浏览器不持有生命周期权威。</p></div><span className="agent-authority-note">PostgreSQL 权威数据</span></header>
    {state==="LOADING"&&<p role="status" className="agent-state">正在读取 Agent Definition…</p>}{state==="SAVING"&&<p role="status" aria-label="Agent save status" className="agent-state">正在保存受治理 Agent 状态…</p>}
    {error&&<div role="alert" className="agent-error" aria-label={`${controlledState??"retryable"} state`}><strong>{controlledState??"操作不可用"}</strong><span>{controlledState==="denied"||controlledState==="not found"?"资源不可用或当前访问未获授权。":error}</span><button onClick={()=>void refresh(definition?.definitionId)}>重新读取权威状态</button></div>}
    {recovery&&<section role="alert" aria-label="Guided conflict recovery"><h2>版本冲突：需要明确恢复</h2><dl><dt>提交版本</dt><dd>{recovery.attemptedVersion}</dd><dt>权威版本</dt><dd>{recovery.authoritative.definition.aggregateVersion}</dd></dl><p>已读取最新权威对象，未自动重放写入；编辑表单仍保留原输入，可由用户核对后再次保存。</p><button onClick={()=>setRecovery(null)}>确认已核对</button></section>}
    <section className="agent-dashboard" aria-label="Agent metrics"><article><strong>{items.length}</strong><span>Definitions in scope</span></article><article><strong>{items.filter(item=>item.publishedRevisionId&&item.enabled&&!item.archived&&!['DEPRECATED','ARCHIVED'].includes(item.lifecycleState)).length}</strong><span>Published and eligible</span></article><article><strong>{items.filter(item=>item.currentDraftRevisionId).length}</strong><span>Drafts requiring review</span></article></section>
    <div className="agent-actions"><button className="primary" disabled={state==="SAVING"||state==="LOADING"} onClick={()=>{invalidate();setState("READY");setSelected(null);setAuthoring("create")}}>创建 Agent Draft</button>{definition&&draft&&<button disabled={state==="SAVING"} onClick={()=>setAuthoring("edit")}>编辑当前 Draft</button>}<Link to={`/agent-center?returnTo=${encodeURIComponent(location.pathname+location.search)}`}>返回 Agent 目录</Link></div>
    <AgentBuilderPage key={`${authoring}:${authoring==="edit"?definition?.definitionId:"new"}`} open={authoring!==null} mode={authoring??"create"} initial={authoring==="edit"&&definition&&draft?{name:definition.name,content:draft.content}:null} options={options} saving={state==="SAVING"} onSave={save} onCancel={()=>setAuthoring(null)}/>
    <div className="agent-layout"><aside><div className="agent-list-heading"><div><p className="eyebrow">Catalog</p><h2>Agent Definitions</h2></div></div><label>搜索目录<input aria-label="搜索 Agent 目录" value={query} onChange={event=>{setQuery(event.target.value);context({query:event.target.value||null})}} placeholder="名称或 canonical ID"/></label><label>生命周期筛选<select aria-label="Agent 生命周期筛选" value={filter} onChange={event=>{setFilter(event.target.value);context({lifecycle:event.target.value==="ALL"?null:event.target.value})}}><option>ALL</option><option>DRAFT</option><option>VALIDATED</option><option>HUMAN_REVIEWED</option><option>PUBLISHED</option><option>DEPRECATED</option><option>ARCHIVED</option></select></label>{state!=="LOADING"&&filtered.length===0?<div className="agent-empty"><h3>没有匹配的 Agent</h3><p>调整筛选或创建 Draft；创建不会自动发布。</p></div>:<ul className="agent-list">{filtered.map(item=><li key={item.definitionId}><button className={definition?.definitionId===item.definitionId?"selected":""} onClick={()=>{setAuthoring(null);void refresh(item.definitionId)}}><span className={`agent-status status-${item.lifecycleState.toLowerCase()}`}>{item.lifecycleState}</span><strong>{item.name}</strong><small>Aggregate v{item.aggregateVersion}</small></button></li>)}</ul>}</aside>
      <section className="agent-detail">{!definition?<div className="agent-empty"><h2>选择 Agent Definition</h2><p>详情、精确绑定、生命周期和历史会显示在这里。</p></div>:<><header><div><span className={`agent-status status-${definition.lifecycleState.toLowerCase()}`}>{definition.lifecycleState}</span><p className="eyebrow">{definition.enabled?"Enabled":"Disabled"}</p><h2>{definition.name}</h2><code>{definition.definitionId}</code></div></header>{(draft??definition.revisions.find(item=>item.revisionId===definition.publishedRevisionId))&&<AgentBindingDetails bindings={(draft??definition.revisions.find(item=>item.revisionId===definition.publishedRevisionId))!.content.bindings}/>} {draft&&<section className="agent-review-card"><h3>当前 Draft</h3><p>{draft.content.title} · {draft.content.businessPurpose}</p><div className="agent-tags">{draft.content.capabilities.map(item=><span key={item}>{item}</span>)}</div><label>精确 revision digest<input aria-label="Exact revision digest" readOnly value={draft.digest}/></label><div className="agent-actions">{draft.state==="DRAFT"&&<button disabled={state==="SAVING"} onClick={()=>act(value=>validateAgentDefinition(value.definitionId,value.aggregateVersion))}>Validate draft</button>}{draft.state==="VALIDATED"&&<button disabled={state==="SAVING"} onClick={()=>act(value=>reviewAgentDefinition(value.definitionId,value.aggregateVersion,draft.digest))}>Human review exact digest</button>}{draft.state==="HUMAN_REVIEWED"&&review&&<button className="primary" disabled={state==="SAVING"} onClick={()=>act(value=>publishAgentDefinition(value.definitionId,value.aggregateVersion,draft.digest,review.reviewId))}>Publish immutable revision</button>}</div></section>}
        <section><h3>生命周期操作</h3><div className="agent-actions">{definition.publishedRevisionId&&!definition.currentDraftRevisionId&&<button disabled={state==="SAVING"} onClick={()=>act(value=>successorAgentDefinition(value.definitionId,value.aggregateVersion))}>Create successor Draft</button>}<button onClick={()=>setManifest(JSON.stringify({manifestVersion:"agent-definition.v1",definitionId:definition.definitionId,revisionId:(draft??definition.revisions.at(-1))?.revisionId,digest:(draft??definition.revisions.at(-1))?.digest,content:(draft??definition.revisions.at(-1))?.content},null,2))}>Export bounded manifest</button><button disabled={state==="SAVING"} onClick={()=>act(value=>lifecycleAgentDefinition(value.definitionId,value.enabled?"DISABLE":"ENABLE",value.aggregateVersion))}>{definition.enabled?"Disable":"Enable"}</button>{definition.publishedRevisionId&&<button disabled={state==="SAVING"} onClick={()=>act(value=>lifecycleAgentDefinition(value.definitionId,"DEPRECATE",value.aggregateVersion))}>Deprecate</button>}<button disabled={state==="SAVING"} onClick={()=>act(value=>lifecycleAgentDefinition(value.definitionId,"ARCHIVE",value.aggregateVersion))}>Archive</button></div><p>Definition 发布不等于 Agent Instance 运行或执行授权。</p>{manifest&&<pre aria-label="Bounded Agent manifest" className="technical-value">{manifest}</pre>}</section>
        <section><h3>Revision history</h3><ol className="agent-history">{definition.revisions.map(item=><li key={item.revisionId}><span className={`agent-status status-${item.state.toLowerCase()}`}>{item.state}</span><code>{item.revisionId}</code><small>{item.predecessorRevisionId?`successor of ${item.predecessorRevisionId}`:"initial revision"}</small></li>)}</ol><h3>Relationships and consumers</h3><p>{definition.relationships.length===0?"No authorized consumers recorded.":`${definition.relationships.length} consumers`}</p></section><AgentVersionComparison revisions={definition.revisions}/><AgentTechnicalProjection projection={selected}/></>}</section></div>
  </main>;
}
