import { useMemo, useState } from "react";
import type { AgentContent, GovernedBindings } from "../api/agentDefinitions";

export type AgentBindingOption = { kind: "skill"|"mcp"|"knowledge"|"workflow"|"runtimeProfile"; resourceId:string; name:string; revisionId:string; digest:string; tools?:string[]; snapshots?:string[] };
const emptyContent=():AgentContent=>({title:"",duties:[],data:[],knowledge:[],skills:[],capabilities:[],runtimes:[],businessPurpose:"",bindings:{skills:[],mcpTools:[],knowledge:[]}});
const csv=(value:string)=>value.split(",").map(item=>item.trim()).filter(Boolean);

export function AgentBindingDetails({bindings}:{bindings:GovernedBindings}){
  const rows=[...bindings.skills.map(value=>({kind:"SKILL",...value})),...bindings.mcpTools.map(value=>({kind:"MCP",...value})),...bindings.knowledge.map(value=>({kind:"KNOWLEDGE",...value})),...(["workflow","runtimeProfile","model"] as const).flatMap(key=>bindings[key]?[bindings[key]!]:[])];
  return <section aria-label="Agent exact resource bindings" className="agent-binding-details"><h3>实际绑定身份</h3><p>以下 digest 属于绑定资源；Agent 自身 revision digest 单独显示。未提供的身份不代表已验证。</p>{rows.length?<ul>{rows.map((row,index)=><li key={index}><dl><dt>Resource kind</dt><dd>{row.kind}</dd><dt>Resource ID</dt><dd>{row.resourceId}</dd><dt>Revision</dt><dd>{row.revisionId||"未提供 / 未验证"}</dd><dt>Resource digest</dt><dd>{row.digest||"未提供 / 未验证"}</dd>{(row.kind==="MCP"||row.kind==="KNOWLEDGE")&&<><dt>Snapshot ID</dt><dd>{"snapshotId" in row&&typeof row.snapshotId==="string"&&row.snapshotId||"未提供 / 未验证"}</dd></>}{row.kind==="MCP"&&<><dt>Tool identity</dt><dd>{"toolName" in row&&typeof row.toolName==="string"&&row.toolName||"未选择 / 未验证"}</dd></>}</dl></li>)}</ul>:<p>未绑定资源。</p>}</section>;
}

function ExactSelections({options,value,onChange}:{options:AgentBindingOption[];value:GovernedBindings;onChange:(value:GovernedBindings)=>void}){
  const toggle=(kind:"skill"|"knowledge",option:AgentBindingOption)=>{const exact={resourceId:option.resourceId,revisionId:option.revisionId,digest:option.digest};if(kind==="skill")onChange({...value,skills:value.skills.some(item=>item.resourceId===option.resourceId)?value.skills.filter(item=>item.resourceId!==option.resourceId):[...value.skills,exact]});else onChange({...value,knowledge:value.knowledge.some(item=>item.resourceId===option.resourceId)?value.knowledge.filter(item=>item.resourceId!==option.resourceId):[...value.knowledge,{...exact,snapshotId:option.snapshots?.at(-1)}]})};
  const mcpOption=options.find(item=>item.kind==="mcp"&&item.resourceId===value.mcpTools[0]?.resourceId);
  return <section className="agent-binding-editor" aria-label="正式资源绑定"><h3>正式资源绑定</h3><p>仅列出当前 scope 内已发布且可用的精确修订；不会自动选择首项。</p>
    {(["skill","knowledge"] as const).map(kind=><fieldset key={kind}><legend>{kind==="skill"?"Skill":"Knowledge"}（可多选）</legend>{options.filter(item=>item.kind===kind).length===0?<p role="status">暂无可绑定的已发布资源。</p>:options.filter(item=>item.kind===kind).map(option=>{const checked=kind==="skill"?value.skills.some(item=>item.resourceId===option.resourceId):value.knowledge.some(item=>item.resourceId===option.resourceId);return <label className="agent-choice" key={option.resourceId}><input type="checkbox" checked={checked} onChange={()=>toggle(kind,option)}/><span>{option.name}<small>{option.resourceId} · {option.revisionId} · {option.digest}</small></span></label>})}</fieldset>)}
    <fieldset><legend>MCP governed Tool（单项）</legend><label>MCP 连接<select aria-label="MCP 连接" value={value.mcpTools[0]?.resourceId??""} onChange={event=>{const option=options.find(item=>item.kind==="mcp"&&item.resourceId===event.target.value);onChange({...value,mcpTools:option?[{resourceId:option.resourceId,revisionId:option.revisionId,digest:option.digest,toolName:"",snapshotId:option.snapshots?.at(-1)}]:[]})}}><option value="">不绑定</option>{options.filter(item=>item.kind==="mcp").map(option=><option key={option.resourceId} value={option.resourceId}>{option.name} · {option.revisionId}</option>)}</select></label>{mcpOption&&<label>受治理 Tool<select aria-label="受治理 Tool" value={value.mcpTools[0]?.toolName??""} onChange={event=>onChange({...value,mcpTools:[{...value.mcpTools[0],toolName:event.target.value}]})}><option value="">请选择 Tool</option>{mcpOption.tools?.map(tool=><option key={tool}>{tool}</option>)}</select></label>}</fieldset>
    {(["workflow","runtimeProfile"] as const).map(kind=><label key={kind}>{kind==="workflow"?"Workflow Definition":"Runtime Profile"}<select aria-label={kind==="workflow"?"Workflow Definition":"Runtime Profile"} value={value[kind]?.resourceId??""} onChange={event=>{const option=options.find(item=>item.kind===kind&&item.resourceId===event.target.value);onChange({...value,[kind]:option?{kind:kind==="workflow"?"WORKFLOW":"RUNTIME_PROFILE",resourceId:option.resourceId,revisionId:option.revisionId,digest:option.digest}:undefined})}}><option value="">不绑定</option>{options.filter(item=>item.kind===kind).map(option=><option key={option.resourceId} value={option.resourceId}>{option.name} · {option.revisionId}</option>)}</select></label>)}
    <AgentBindingDetails bindings={value}/><p className="qto-disclosure">Model 当前只有未验证 opaque reference，没有正式可验证目录；本表单不伪造 Model 绑定。</p></section>;
}

export function AgentBuilderPage({open,mode,initial,options,saving,onSave,onCancel}:{open:boolean;mode:"create"|"edit";initial?:{name:string;content:AgentContent}|null;options:AgentBindingOption[];saving:boolean;onSave:(name:string,content:AgentContent)=>Promise<void>;onCancel:()=>void}){
  const[name,setName]=useState(initial?.name??"");const[content,setContent]=useState<AgentContent>(()=>structuredClone(initial?.content??emptyContent()));
  const valid=useMemo(()=>Boolean(name.trim()&&content.title.trim()&&content.businessPurpose.trim()&&content.duties.length&&content.capabilities.length&&content.bindings.mcpTools.every(item=>item.toolName)),[name,content]);
  if(!open)return null;
  const field=(label:string,key:"duties"|"data"|"knowledge"|"skills"|"capabilities"|"runtimes")=><label>{label}<input value={content[key].join(", ")} onChange={event=>setContent({...content,[key]:csv(event.target.value)})}/></label>;
  return <section className="agent-review-card agent-authoring" aria-label="Agent Draft authoring"><p className="eyebrow">Agent Builder</p><h2>{mode==="edit"?"编辑当前 Agent Draft":"创建 Agent Draft"}</h2><div className="resource-form-grid"><label>Agent 名称<input value={name} readOnly={mode==="edit"} maxLength={240} onChange={event=>setName(event.target.value)}/></label>{mode==="edit"&&<p>名称只读：正式 Draft 更新 API 当前不支持改名。</p>}<label>角色标题<input value={content.title} onChange={event=>setContent({...content,title:event.target.value})}/></label><label>业务目的<textarea aria-label="业务目的" value={content.businessPurpose} onChange={event=>setContent({...content,businessPurpose:event.target.value})}/></label>{field("职责（逗号分隔）","duties")}{field("业务能力（逗号分隔）","capabilities")}{field("数据（逗号分隔）","data")}{field("知识说明（逗号分隔）","knowledge")}{field("Skill 说明（逗号分隔）","skills")}{field("Runtime 要求（逗号分隔）","runtimes")}</div><ExactSelections options={options} value={content.bindings} onChange={bindings=>setContent({...content,bindings})}/><p className="qto-disclosure">保存只创建或修改 Draft；Definition 发布不创建 Agent Instance，也不授予执行、MCP 调用或凭据权限。</p><div className="agent-actions"><button className="primary" disabled={saving||!valid} onClick={()=>void onSave(name.trim(),content)}>{saving?"正在保存…":"保存 Agent Draft"}</button><button disabled={saving} onClick={onCancel}>取消</button></div></section>;
}
