import { useState } from "react";
import type { AgentContent, ExactResourceReference, GovernedBindings } from "../api/agentDefinitions";

const emptyBindings = (): GovernedBindings => ({ skills: [], mcpTools: [], knowledge: [] });
const exact = (resourceId:string, revisionId:string, digest:string): ExactResourceReference | null => resourceId && revisionId && digest ? { resourceId, revisionId, digest } : null;

export function AgentBuilderPage({ onCreate, saving }: { onCreate:(name:string, content:AgentContent)=>Promise<void>; saving:boolean }) {
  const [open,setOpen]=useState(false); const [name,setName]=useState("Supplier Quality Analysis Agent");
  const [purpose,setPurpose]=useState("Analyze supplier quality and recommend governed corrective action");
  const [skill,setSkill]=useState(["", "", ""]); const [mcp,setMcp]=useState(["", "", "", ""]); const [knowledge,setKnowledge]=useState(["", "", "", ""]);
  async function submit(){const bindings=emptyBindings();const skillRef=exact(skill[0],skill[1],skill[2]);if(skillRef)bindings.skills.push(skillRef);const mcpRef=exact(mcp[0],mcp[1],mcp[2]);if(mcpRef)bindings.mcpTools.push({...mcpRef,toolName:mcp[3]});const knowledgeRef=exact(knowledge[0],knowledge[1],knowledge[2]);if(knowledgeRef)bindings.knowledge.push({...knowledgeRef,...(knowledge[3]?{snapshotId:knowledge[3]}:{})});await onCreate(name,{title:"Supplier Quality Analyst",duties:["analyze supplier quality"],data:["quality records"],knowledge:["supplier quality policy"],skills:["root cause analysis"],capabilities:["supplier-quality-analysis"],runtimes:[],businessPurpose:purpose,bindings});setOpen(false)}
  if(!open)return <button onClick={()=>setOpen(true)}>Open guided Agent Builder</button>;
  const fields=(value:string[],setter:(v:string[])=>void,labels:string[])=>labels.map((label,index)=><label key={label}>{label}<input value={value[index]} onChange={event=>{const next=[...value];next[index]=event.target.value;setter(next)}} /></label>);
  return <section className="agent-review-card" aria-label="Guided Agent Builder"><p className="eyebrow">Guided Agent Builder</p><h2>Define purpose and exact governed resources</h2><label>Agent name<input value={name} onChange={event=>setName(event.target.value)}/></label><label>Business purpose<textarea value={purpose} onChange={event=>setPurpose(event.target.value)}/></label><fieldset><legend>Exact published Skill revision (optional)</legend>{fields(skill,setSkill,["Skill resource ID","Skill revision ID","Skill SHA-256 digest"])}</fieldset><fieldset><legend>Exact governed MCP tool (optional)</legend>{fields(mcp,setMcp,["MCP resource ID","MCP revision ID","MCP SHA-256 digest","Governed tool name"])}</fieldset><fieldset><legend>Exact Knowledge revision/snapshot (optional)</legend>{fields(knowledge,setKnowledge,["Knowledge resource ID","Knowledge revision ID","Knowledge SHA-256 digest","Snapshot ID"])}</fieldset><p className="qto-disclosure">Preview only: publication does not grant model, workflow, runtime, MCP invocation, Knowledge access, credentials, or execution authority.</p><div className="agent-actions"><button className="primary" disabled={saving} onClick={()=>void submit()}>Create governed draft</button><button onClick={()=>setOpen(false)}>Cancel</button></div></section>;
}
