import {useEffect,useMemo,useState} from "react";
import {
  SkillMcpRequestError,skillMcpControlledState,bindCapability,cloneResource,createResource,discoverMcp,exportManifest,getResource,healthMcp,importManifest,invokeCapability,invokeMcp,
  lifecycleResource,listResources,publishResource,reviewResource,runTest,saveTest,selectTool,successorResource,
  validateResource,type ResourceContent,type ResourceKind,type ResourceProjection,type SkillMcpResource,type SkillMcpControlledState,
} from "../api/skillMcpResources";
import {SkillMcpTechnicalProjection} from "./SkillMcpTechnicalProjection";

const localEndpoint="http://127.0.0.1:8765/mcp";
const content:Record<ResourceKind,ResourceContent>={
  skill:{description:"Analyze supplier quality through one governed capability",capabilities:["quality.lookup"],instructions:"Perform a bounded quality lookup and return redacted evidence.",inputSchema:{type:"object",required:["supplier"],properties:{supplier:{type:"string"}}},outputSchema:{type:"object"},parameters:[{name:"supplier",required:true}],errorPolicy:{mode:"FAIL_CLOSED"},timeoutSeconds:5,sideEffect:"READ",idempotency:"IDEMPOTENT",permissions:["supplier-quality:read"],dependencies:[],examples:[{supplier:"ACME"}]},
  mcp:{description:"Local deterministic MCP acceptance server",capabilities:["quality.lookup"],endpoint:localEndpoint,secretReference:"secret-ref:supplier-quality/mcp",timeoutSeconds:2,sideEffect:"READ",idempotency:"IDEMPOTENT",permissions:["supplier-quality:read"]},
};

function Builder({kind,draft}:{kind:ResourceKind;draft:SkillMcpResource["revisions"][number]}){
  const value=draft.content;
  return <section className="agent-section" aria-label={kind==="skill"?"Skill Builder":"MCP registration"}>
    <header><div><p className="eyebrow">{kind==="skill"?"Skill Builder":"Server registration"}</p><h3>{kind==="skill"?"Contract and behavior":"Endpoint and external Secret Reference"}</h3></div></header>
    <dl className="technical-grid"><dt>Description</dt><dd>{value.description}</dd><dt>Capabilities</dt><dd>{value.capabilities.join(", ")}</dd>{kind==="skill"?<><dt>Instructions</dt><dd>{value.instructions}</dd><dt>Input schema</dt><dd><code>{JSON.stringify(value.inputSchema)}</code></dd><dt>Output schema</dt><dd><code>{JSON.stringify(value.outputSchema)}</code></dd><dt>Error / timeout</dt><dd>{String(value.errorPolicy?.mode??"FAIL_CLOSED")} · {value.timeoutSeconds}s</dd><dt>Side effect / idempotency</dt><dd>{value.sideEffect} · {value.idempotency}</dd><dt>Permissions</dt><dd>{value.permissions?.join(", ")||"None"}</dd><dt>Dependencies</dt><dd>{value.dependencies?.join(", ")||"None"}</dd><dt>Usage examples</dt><dd><code>{JSON.stringify(value.examples)}</code></dd></>:<><dt>Streamable HTTP endpoint</dt><dd><code>{value.endpoint}</code></dd><dt>Credential</dt><dd><code>{value.secretReference}</code> (reference only)</dd><dt>Protocol</dt><dd><code>2025-06-18</code> · backend-originated · no redirects</dd></>}</dl>
  </section>;
}

export function ResourceWorkbench({kind}:{kind:ResourceKind}){
  const [items,setItems]=useState<SkillMcpResource[]>([]);const [selected,setSelected]=useState<ResourceProjection|null>(null);
  const [mcps,setMcps]=useState<SkillMcpResource[]>([]);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  const [loading,setLoading]=useState(true);const [projection,setProjection]=useState<"product"|"technical">("product");
  const [controlledState,setControlledState]=useState<SkillMcpControlledState|null>(null);const [recovery,setRecovery]=useState<{attemptedVersion:number;authoritative:ResourceProjection}|null>(null);
  const [query,setQuery]=useState("");const [state,setState]=useState("ALL");
  async function refresh(id?:string){try{const values=await listResources(kind);setItems(values);if(kind==="skill")setMcps(await listResources("mcp"));if(id)setSelected(await getResource(kind,id));setError(null)}catch(reason){setError(reason instanceof SkillMcpRequestError?reason.reasonCode:"SKILL_MCP_UNAVAILABLE")}}
  useEffect(()=>{let active=true;Promise.all([listResources(kind),kind==="skill"?listResources("mcp"):Promise.resolve([])]).then(([values,mcpValues])=>{if(active){setItems(values);setMcps(mcpValues);setLoading(false)}}).catch(reason=>{if(active){setError(reason instanceof SkillMcpRequestError?reason.reasonCode:"SKILL_MCP_UNAVAILABLE");setLoading(false)}});return()=>{active=false}},[kind]);
  async function create(){setBusy(true);try{const value=await createResource(kind,kind==="skill"?"Supplier Quality Skill":"Local Acceptance MCP",content[kind]);await refresh(value.resource.resourceId)}finally{setBusy(false)}}
  async function act(operation:(resource:SkillMcpResource)=>Promise<ResourceProjection>){if(!selected)return;const attemptedVersion=selected.resource.aggregateVersion;setBusy(true);try{const value=await operation(selected.resource);setSelected(value);await refresh();setError(null);setRecovery(null)}catch(reason){if(reason instanceof SkillMcpRequestError){setControlledState(skillMcpControlledState(reason));if(reason.status===409){try{const authoritative=await getResource(kind,selected.resource.resourceId);setSelected(authoritative);setRecovery({attemptedVersion,authoritative});setError(null);return}catch(fetchReason){setError(fetchReason instanceof SkillMcpRequestError?fetchReason.reasonCode:"SKILL_MCP_UNAVAILABLE")}}setError(reason.reasonCode)}else setError("ACTION_FAILED")}finally{setBusy(false)}}
  async function exportJson(){if(!resource)return;const manifest=await exportManifest(resource);const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([JSON.stringify(manifest,null,2)],{type:"application/json"}));link.download=`${resource.kind}-manifest.json`;link.click();URL.revokeObjectURL(link.href)}
  async function importCopy(){if(!resource)return;setBusy(true);try{const manifest=await exportManifest(resource);const value=await importManifest(manifest);await refresh(value.resource.resourceId)}finally{setBusy(false)}}
  const filtered=useMemo(()=>items.filter(item=>(state==="ALL"||item.lifecycleState===state)&&`${item.name} ${item.resourceId}`.toLowerCase().includes(query.toLowerCase())),[items,query,state]);
  const resource=selected?.resource;const draft=resource?.revisions.find(item=>item.revisionId===resource.currentDraftRevisionId);const review=resource?.reviews.at(-1);
  const eligibleMcp=mcps.find(item=>item.publishedRevisionId&&item.enabled);const snapshot=resource?.discoverySnapshots.at(-1);const tool=snapshot?.catalog.tools[0];const selection=resource?.toolSelections.at(-1);
  const title=kind==="skill"?"Skill Workbench":"MCP Workbench";
  return <main className="agent-workbench"><header className="agent-page-header"><div><p className="eyebrow">Enterprise Resource Workbench</p><h1>{title}</h1><p>Author, test, discover, govern, invoke and inspect one canonical backend-owned resource.</p></div><span className="agent-authority-note">PostgreSQL authoritative</span></header>
    {loading&&<p role="status" className="agent-state">Loading authoritative {kind.toUpperCase()} resources…</p>}
    {busy&&<p role="status" aria-label="Workbench save status" className="agent-state">Saving governed {kind.toUpperCase()} state…</p>}
    {error&&<div role="alert" className="agent-error" aria-label={`${controlledState??"retryable"} state`}><strong>{controlledState??"Action unavailable"}</strong><span>{controlledState==="denied"||controlledState==="not found"?"The resource is unavailable or access is not authorized.":error}</span><button onClick={()=>void refresh(resource?.resourceId)}>Retry authoritative fetch</button></div>}
    {recovery&&<section role="alert" aria-label="Guided conflict recovery"><h2>{controlledState}: explicit recovery required</h2><dl><dt>Attempted aggregate version</dt><dd>{recovery.attemptedVersion}</dd><dt>Authoritative aggregate version</dt><dd>{recovery.authoritative.resource.aggregateVersion}</dd><dt>Authoritative revision</dt><dd>{recovery.authoritative.resource.revisions.at(-1)?.revisionId}</dd></dl><p>The authoritative resource was fetched. No lifecycle, invocation, or publication command was replayed; there is no safe operation input to preserve.</p><button onClick={()=>setRecovery(null)}>Acknowledge authoritative version</button></section>}
    <section className="agent-dashboard" aria-label="Resource metrics"><article><span>Resources in scope</span><strong>{items.length}</strong></article><article><span>Published and enabled</span><strong>{items.filter(item=>item.publishedRevisionId&&item.enabled).length}</strong></article><article><span>{kind==="skill"?"Saved test results":"Discovery snapshots"}</span><strong>{items.reduce((count,item)=>count+(kind==="skill"?item.testResults.length:item.discoverySnapshots.length),0)}</strong></article><article><span>{kind==="skill"?"Authorized consumers":"Recorded invocations"}</span><strong>{items.reduce((count,item)=>count+(kind==="skill"?item.relationships.length:item.invocations.length),0)}</strong></article></section>
    <div className="agent-layout"><aside><div className="agent-list-heading"><div><p className="eyebrow">Catalog</p><h2>{kind==="skill"?"Skills":"MCP servers"}</h2></div><button className="primary" onClick={()=>void create()} disabled={busy}>Create governed {kind.toUpperCase()}</button></div>
      <label>Search catalog<input aria-label="Search catalog" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Name or canonical ID"/></label><label>Lifecycle filter<select aria-label="Lifecycle filter" value={state} onChange={event=>setState(event.target.value)}><option>ALL</option><option>DRAFT</option><option>VALIDATED</option><option>HUMAN_REVIEWED</option><option>PUBLISHED</option><option>DEPRECATED</option></select></label>
      {!loading&&filtered.length===0?<div className="agent-empty"><h3>No matching resources</h3><p>Clear filters or create a governed Draft. Creation never publishes it.</p></div>:<ul className="agent-list">{filtered.map(item=><li key={item.resourceId}><button className={resource?.resourceId===item.resourceId?"selected":""} onClick={()=>void refresh(item.resourceId)}><span className={`agent-status status-${item.lifecycleState.toLowerCase()}`}>{item.lifecycleState}</span><strong>{item.name}</strong><small>Aggregate v{item.aggregateVersion}</small></button></li>)}</ul>}</aside>
      <section className="agent-detail">{!resource?<div className="agent-empty"><h2>Select a resource</h2><p>Builder, tests, discovery, Evidence and relationships appear here.</p></div>:<><header><div><span className={`agent-status status-${resource.lifecycleState.toLowerCase()}`}>{resource.lifecycleState}</span><h2>{resource.name}</h2><code>{resource.resourceId}</code></div><span className={`agent-availability ${resource.enabled?"enabled":"disabled"}`}>{resource.enabled?"Enabled":"Disabled"}</span></header>
        <div className="agent-view-tabs" role="tablist" aria-label="Resource projection"><button role="tab" aria-selected={projection==="product"} onClick={()=>setProjection("product")}>Product View</button><button role="tab" aria-selected={projection==="technical"} onClick={()=>setProjection("technical")}>Technical View</button></div>
        {projection==="technical"?<SkillMcpTechnicalProjection projection={selected}/>:<>{draft&&<><Builder kind={kind} draft={draft}/><section className="agent-review-card"><header><div><p className="eyebrow">Revision workflow</p><h3>Current draft</h3></div><span className={`agent-status status-${draft.state.toLowerCase()}`}>{draft.state}</span></header><label>Exact revision digest<input readOnly value={draft.digest}/></label><div className="agent-validation-panel"><strong>{draft.state==="DRAFT"?"Validation required":draft.state==="VALIDATED"?"Validation passed — exact review required":"Exact digest reviewed — ready to publish"}</strong><span>Saving, Human review and immutable publication are separate governed actions.</span></div><div className="agent-actions workflow-actions">{draft.state==="DRAFT"&&<button onClick={()=>act(item=>validateResource(kind,item.resourceId,item.aggregateVersion))} disabled={busy}>Validate draft</button>}{draft.state==="VALIDATED"&&<button onClick={()=>act(item=>reviewResource(kind,item.resourceId,item.aggregateVersion,draft.digest))} disabled={busy}>Human review exact digest</button>}{draft.state==="HUMAN_REVIEWED"&&review&&<button className="publish" onClick={()=>act(item=>publishResource(kind,item.resourceId,item.aggregateVersion,draft.digest,review.reviewId))} disabled={busy}>Publish immutable revision</button>}</div></section></>}
          <section className="agent-section" aria-label={`${kind.toUpperCase()} professional operations`}><header><div><p className="eyebrow">Professional operations</p><h3>{kind==="skill"?"Saved tests and comparison":"Connection, discovery and Test Console"}</h3></div></header><div className="agent-actions">{kind==="skill"?<><button onClick={()=>act(saveTest)} disabled={busy}>Save test case</button>{resource.savedTests.at(-1)&&<button onClick={()=>act(item=>runTest(item,item.savedTests.at(-1)!.testId))} disabled={busy}>Run saved test</button>}</>:<><button onClick={()=>act(healthMcp)} disabled={busy}>Test connection</button><button onClick={()=>act(discoverMcp)} disabled={busy}>Discover Tools, Resources and Prompts</button>{snapshot&&tool&&<button onClick={()=>act(item=>selectTool(item,snapshot,tool.name))} disabled={busy}>Govern Tool selection</button>}{selection&&tool&&<button className="primary" onClick={()=>act(item=>invokeMcp(item,selection.selectionId,tool.name))} disabled={busy}>Authorize real bounded invocation</button>}</>}</div>
            {kind==="skill"?<><h4>Saved test cases</h4><ul>{resource.savedTests.map(test=><li key={test.testId}>{test.name} · <code>{test.testId}</code></li>)}</ul><h4>Test result comparison</h4><ul>{resource.testResults.map(result=><li key={result.resultId}><strong>{result.status}</strong> · revision <code>{result.revisionId}</code> · {result.errors.join(", ")||"expected equals actual"}</li>)}</ul></>:<><h4>Health observations</h4><ul>{resource.healthObservations.map(item=><li key={item.observationId}><strong>{item.status}</strong> · {item.reasonCode} · protocol {item.protocolRevision}</li>)}</ul><h4>Immutable discovery and schema snapshots</h4>{snapshot?<><p><code>{snapshot.digest}</code></p><p>{snapshot.catalog.tools.length} Tool(s) · {snapshot.catalog.resources.length} Resource(s) · {snapshot.catalog.prompts.length} Prompt(s)</p></>:<p>No discovery authority recorded.</p>}<h4>Schema/version drift</h4><p>{resource.driftRecords.length?`${resource.driftRecords.length} drift record(s) require inspection.`:"No drift detected between captured snapshots."}</p></>}
            {selected?.invocation&&<div role="status" aria-label="Invocation Evidence status" className="agent-invocation"><span className={`agent-status status-${selected.invocation.status.toLowerCase()}`}>{selected.invocation.status}</span><div><strong>Invocation Evidence recorded</strong><p>{selected.invocation.reasonCode??"SUCCEEDED"}; credential values redacted: {String(selected.invocation.evidence.redacted)}; ambiguous side effects were not retried.</p></div></div>}
          </section>
          <section className="agent-section"><header><div><p className="eyebrow">Governed lifecycle</p><h3>Publication, relationships and consumers</h3></div></header><div className="agent-actions">{resource.publishedRevisionId&&!resource.currentDraftRevisionId&&<button onClick={()=>act(item=>successorResource(kind,item.resourceId,item.aggregateVersion))} disabled={busy}>Create successor Draft</button>}<button onClick={()=>act(item=>cloneResource(item,item.publishedRevisionId??item.currentDraftRevisionId!))} disabled={busy}>Clone as template</button><button onClick={()=>void exportJson()} disabled={busy}>Export bounded manifest</button><button onClick={()=>void importCopy()} disabled={busy}>Import bounded manifest copy</button><button onClick={()=>act(item=>lifecycleResource(kind,item.resourceId,item.enabled?"DISABLE":"ENABLE",item.aggregateVersion))} disabled={busy}>{resource.enabled?"Disable":"Enable"}</button>{kind==="skill"&&resource.publishedRevisionId&&eligibleMcp&&resource.bindings.length===0&&<button onClick={()=>act(item=>bindCapability(item,eligibleMcp,"quality.lookup"))} disabled={busy}>Bind exact MCP capability</button>}{kind==="skill"&&resource.bindings.at(-1)&&<button onClick={()=>act(item=>invokeCapability(item,item.bindings.at(-1)!.bindingId))} disabled={busy}>Authorize bounded capability test</button>}</div><p>{resource.relationships.length} governed relationship(s) · published history is immutable · deprecation does not delete an external MCP server.</p>{resource.publishedRevisionId&&<button className="danger" onClick={()=>act(item=>lifecycleResource(kind,item.resourceId,"DEPRECATE",item.aggregateVersion))} disabled={busy||resource.lifecycleState==="DEPRECATED"}>Deprecate</button>}</section>
          <section className="agent-section"><h3>Revision diff and history</h3><ol className="agent-history">{resource.revisions.map((item,index)=><li key={item.revisionId}><span className={`agent-status status-${item.state.toLowerCase()}`}>{item.state}</span><code>{item.revisionId}</code><small>{index?` successor of ${item.predecessorRevisionId}`:" initial revision"}</small></li>)}</ol></section></>}</>}</section></div>
  </main>;
}
export function SkillWorkbenchPage(){return <ResourceWorkbench kind="skill"/>}
