import {useEffect,useRef,useState} from "react";
import {useSearchParams} from "react-router-dom";
import {
  SkillMcpRequestError,skillMcpControlledState,bindCapability,cloneResource,createResource,discoverMcp,editResource,exportManifest,getResource,healthMcp,importManifest,invokeCapability,invokeMcp,
  lifecycleResource,listResources,publishResource,reviewResource,runTest,saveTest,selectTools,successorResource,
  validateResource,type ResourceContent,type ResourceKind,type ResourceManifest,type ResourceProjection,type SkillMcpResource,type SkillMcpControlledState,
} from "../api/skillMcpResources";
import {SkillMcpTechnicalProjection} from "./SkillMcpTechnicalProjection";
import {CapabilityCenterDirectory} from "./CapabilityCenterDirectory";
import {CapabilityResourceDetails} from "./CapabilityResourceDetails";
import "../styles/capability-center.css";

const localEndpoint="http://127.0.0.1:8765/mcp";
const content:Record<ResourceKind,ResourceContent>={
  skill:{description:"Analyze supplier quality through one governed capability",capabilities:["quality.lookup"],instructions:"Perform a bounded quality lookup and return redacted evidence.",inputSchema:{type:"object",required:["supplier"],properties:{supplier:{type:"string"}}},outputSchema:{type:"object"},parameters:[{name:"supplier",required:true}],errorPolicy:{mode:"FAIL_CLOSED"},timeoutSeconds:5,sideEffect:"READ",idempotency:"IDEMPOTENT",permissions:["supplier-quality:read"],dependencies:[],examples:[{supplier:"ACME"}]},
  mcp:{description:"Local deterministic MCP acceptance server",capabilities:["quality.lookup"],endpoint:localEndpoint,secretReference:"secret-ref:supplier-quality/mcp",timeoutSeconds:2,sideEffect:"READ",idempotency:"IDEMPOTENT",permissions:["supplier-quality:read"]},
};

const csv=(value:string)=>value.split(",").map(item=>item.trim()).filter(Boolean);
const json=(value:string,label:string)=>{try{const parsed=JSON.parse(value);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error();return parsed as Record<string,unknown>}catch{throw new SkillMcpRequestError(`${label}_JSON_INVALID`,422)}};
type ReuseOperation="clone"|"export"|"import"|"successor";
type ReuseIntent={operation:ReuseOperation;sourceResourceId:string;sourceRevisionId:string;sourceDigest:string;targetName:string;manifest?:ResourceManifest};
type ReuseReceipt={operation:ReuseOperation;sourceResourceId:string;sourceRevisionId:string;sourceDigest:string;targetResourceId?:string;targetRevisionId?:string;targetDigest?:string;relationshipType?:string;sourceRelationshipRecorded?:boolean};
const exactRevision=(resource:SkillMcpResource,revisionId:string)=>resource.revisions.find(item=>item.revisionId===revisionId);
const revisionForProjection=(resource:SkillMcpResource)=>exactRevision(resource,resource.currentDraftRevisionId??resource.publishedRevisionId??"")??resource.revisions.at(-1);
const operationLabel:Record<ReuseOperation,string>={clone:"Clone exact revision",export:"Export bounded manifest",import:"Import bounded manifest copy",successor:"Create successor Draft"};
function ResourceAuthoring({kind,mode,name,value,onName,onChange}:{kind:ResourceKind;mode:"create"|"edit";name:string;value:ResourceContent;onName:(value:string)=>void;onChange:(value:ResourceContent)=>void}){
 const objectField=(key:"inputSchema"|"outputSchema"|"errorPolicy",element:HTMLTextAreaElement)=>{try{onChange({...value,[key]:json(element.value,key.toUpperCase())});element.setCustomValidity("")}catch{element.setCustomValidity("请输入有效的 JSON 对象");element.reportValidity()}};
 return <section className="agent-section resource-form" aria-label={`${kind.toUpperCase()} authoring form`}><header><div><p className="eyebrow">{kind==="skill"?"Skill Builder":"MCP Connection Builder"}</p><h3>{kind==="skill"?"Skill Draft 内容":"MCP Draft 连接配置"}</h3></div></header><p>字段会进入正式 Draft；保存、连接测试、发现、工具选择、管理调用与 Attempt invocation 始终分离。</p>
  <label>{kind==="skill"?"Skill":"MCP"} 名称<input value={name} readOnly={mode==="edit"} maxLength={120} onChange={event=>onName(event.target.value)}/></label>{mode==="edit"&&<p>名称只读：正式 Draft 更新 API 当前不支持改名。</p>}<label>说明<textarea aria-label="说明" value={value.description} onChange={event=>onChange({...value,description:event.target.value})}/></label><label>能力 / operation（逗号分隔）<input value={value.capabilities.join(", ")} onChange={event=>onChange({...value,capabilities:csv(event.target.value)})}/></label>{kind==="skill"?<label>执行说明<textarea aria-label="执行说明" value={value.instructions??""} onChange={event=>onChange({...value,instructions:event.target.value})}/></label>:<div className="resource-form-grid"><label>Streamable HTTP endpoint<input aria-label="Streamable HTTP endpoint" type="url" placeholder="http://127.0.0.1:8765/mcp" value={value.endpoint??""} onChange={event=>onChange({...value,endpoint:event.target.value})}/></label><label>Credential reference<input aria-label="Credential reference" placeholder="secret-ref:scope/name" value={value.secretReference??""} onChange={event=>onChange({...value,secretReference:event.target.value||null})}/></label><p className="qto-disclosure">只接受后端契约允许的 endpoint 和外部 secret-ref；页面不接收、保存或记录秘密明文。Trust 配置尚无正式 API 字段，保持 OPEN。</p></div>}
  <div className="resource-form-grid">{kind==="skill"&&<><label>输入 Schema（JSON）<textarea aria-label="输入 Schema（JSON）" defaultValue={JSON.stringify(value.inputSchema??{},null,2)} onBlur={event=>objectField("inputSchema",event.currentTarget)}/></label><label>输出 Schema（JSON）<textarea aria-label="输出 Schema（JSON）" defaultValue={JSON.stringify(value.outputSchema??{},null,2)} onBlur={event=>objectField("outputSchema",event.currentTarget)}/></label><label>错误策略（JSON）<textarea aria-label="错误策略（JSON）" defaultValue={JSON.stringify(value.errorPolicy??{},null,2)} onBlur={event=>objectField("errorPolicy",event.currentTarget)}/></label></>}<label>超时秒数<input type="number" min="1" max="30" value={value.timeoutSeconds??5} onChange={event=>onChange({...value,timeoutSeconds:Number(event.target.value)})}/></label><label>副作用声明<select value={value.sideEffect??"NONE"} onChange={event=>onChange({...value,sideEffect:event.target.value})}><option>NONE</option><option>READ</option><option>WRITE</option><option>DESTRUCTIVE</option></select></label><label>幂等性声明<select value={value.idempotency??"IDEMPOTENT"} onChange={event=>onChange({...value,idempotency:event.target.value})}><option>IDEMPOTENT</option><option>NON_IDEMPOTENT</option><option>UNKNOWN</option></select></label><label>权限（逗号分隔）<input value={value.permissions?.join(", ")??""} onChange={event=>onChange({...value,permissions:csv(event.target.value)})}/></label>{kind==="skill"&&<label>依赖（逗号分隔）<input value={value.dependencies?.join(", ")??""} onChange={event=>onChange({...value,dependencies:csv(event.target.value)})}/></label>}</div>
 </section>;
}

function Builder({kind,draft}:{kind:ResourceKind;draft:SkillMcpResource["revisions"][number]}){
  const value=draft.content;
  return <section className="agent-section" aria-label={kind==="skill"?"Skill Builder":"MCP registration"}>
    <header><div><p className="eyebrow">{kind==="skill"?"Skill Builder":"Server registration"}</p><h3>{kind==="skill"?"Contract and behavior":"Endpoint and external Secret Reference"}</h3></div></header>
    <dl className="technical-grid"><dt>Description</dt><dd>{value.description}</dd><dt>Capabilities</dt><dd>{value.capabilities.join(", ")}</dd>{kind==="skill"?<><dt>Instructions</dt><dd>{value.instructions}</dd><dt>Input schema</dt><dd><code>{JSON.stringify(value.inputSchema)}</code></dd><dt>Output schema</dt><dd><code>{JSON.stringify(value.outputSchema)}</code></dd><dt>Error / timeout</dt><dd>{String(value.errorPolicy?.mode??"FAIL_CLOSED")} · {value.timeoutSeconds}s</dd><dt>Side effect / idempotency</dt><dd>{value.sideEffect} · {value.idempotency}</dd><dt>Permissions</dt><dd>{value.permissions?.join(", ")||"None"}</dd><dt>Dependencies</dt><dd>{value.dependencies?.join(", ")||"None"}</dd><dt>Usage examples</dt><dd><code>{JSON.stringify(value.examples)}</code></dd></>:<><dt>Streamable HTTP endpoint</dt><dd><code>{value.endpoint}</code></dd><dt>Credential</dt><dd><code>{value.secretReference}</code> (reference only)</dd><dt>Protocol</dt><dd><code>2025-06-18</code> · backend-originated · no redirects</dd></>}</dl>
  </section>;
}

export function ResourceWorkbench({kind}:{kind:ResourceKind}){
  const [searchParams,setSearchParams]=useSearchParams();
  const [items,setItems]=useState<SkillMcpResource[]>([]);const [selected,setSelected]=useState<ResourceProjection|null>(null);
  const [mcps,setMcps]=useState<SkillMcpResource[]>([]);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  const [loading,setLoading]=useState(true);const [projection,setProjection]=useState<"product"|"technical">("product");
  const [controlledState,setControlledState]=useState<SkillMcpControlledState|null>(null);const [recovery,setRecovery]=useState<{attemptedVersion:number;authoritative:ResourceProjection}|null>(null);
  const [query,setQuery]=useState(searchParams.get("query")??"");const [state,setState]=useState(searchParams.get("lifecycle")??"ALL");
  const [authoringMode,setAuthoringMode]=useState<"create"|"edit">("create");const [authoring,setAuthoring]=useState<ResourceContent|null>(null),[authoringName,setAuthoringName]=useState("");const [bindingMcpId,setBindingMcpId]=useState(""),[bindingCapability,setBindingCapability]=useState("");
  const [testName,setTestName]=useState(""),[testInput,setTestInput]=useState("{}"),[testExpected,setTestExpected]=useState("{}"),[invocationInput,setInvocationInput]=useState("{}"),[toolDraft,setToolDraft]=useState<{resourceId:string;snapshotId:string;names:string[]}|null>(null),[invocationTool,setInvocationTool]=useState("");
  const [reuseIntent,setReuseIntent]=useState<ReuseIntent|null>(null),[reuseReceipt,setReuseReceipt]=useState<ReuseReceipt|null>(null);
  const requestId=useRef(0),writeInFlight=useRef<symbol|null>(null);const [initialResourceId]=useState(()=>searchParams.get("resourceId"));
  function preserveContext(patch:Record<string,string|null>){setSearchParams(current=>{const next=new URLSearchParams(current);for(const [key,value] of Object.entries(patch)){if(value)next.set(key,value);else next.delete(key)}return next},{replace:true})}
  function invalidate(){requestId.current+=1;writeInFlight.current=null;setBusy(false);setError(null);setControlledState(null);setRecovery(null);setToolDraft(null);setInvocationTool("");setReuseIntent(null);setReuseReceipt(null);return requestId.current}
  async function refresh(id?:string){const current=invalidate();setAuthoring(null);setSelected(null);setLoading(true);try{const values=await listResources(kind);if(current!==requestId.current)return;const mcpValues=kind==="skill"?await listResources("mcp"):[];if(current!==requestId.current)return;const detail=id?await getResource(kind,id):null;if(current!==requestId.current)return;setItems(values);setMcps(mcpValues);if(detail){setSelected(detail);preserveContext({resourceId:id!})}}catch(reason){if(current===requestId.current)fail(reason)}finally{if(current===requestId.current)setLoading(false)}}
  useEffect(()=>{const current=++requestId.current;Promise.all([listResources(kind),kind==="skill"?listResources("mcp"):Promise.resolve([]),initialResourceId?getResource(kind,initialResourceId):Promise.resolve(null)]).then(([values,mcpValues,detail])=>{if(current!==requestId.current)return;setItems(values);setMcps(mcpValues);if(detail)setSelected(detail);setLoading(false)}).catch(reason=>{if(current===requestId.current){setError(reason instanceof SkillMcpRequestError?reason.reasonCode:"SKILL_MCP_UNAVAILABLE");setLoading(false)}});return()=>{requestId.current+=1;writeInFlight.current=null}},[kind,initialResourceId]);
  function fail(reason:unknown){const failure=reason instanceof SkillMcpRequestError?reason:new SkillMcpRequestError("SKILL_MCP_UNAVAILABLE",503);setControlledState(skillMcpControlledState(failure));setError(failure.reasonCode)}
  function create(){invalidate();setLoading(false);setSelected(null);setAuthoringMode("create");setAuthoringName("");setAuthoring(structuredClone(content[kind]))}
  function editDraft(){if(!resource||!draft)return;setAuthoringMode("edit");setAuthoringName(resource.name);setAuthoring(structuredClone(draft.content));setError(null)}
  async function write(operation:(owns:()=>boolean)=>Promise<ResourceProjection|null>,closeAuthoring=false,authoritativeReadback=false,onSuccess?:(response:ResourceProjection,readback:ResourceProjection)=>void){
    if(writeInFlight.current)return;
    const current=requestId.current,atStart=selected?.resource,token=Symbol();
    const owns=()=>current===requestId.current&&writeInFlight.current===token;
    writeInFlight.current=token;setBusy(true);
    try{
      const value=await operation(owns);if(!owns()||!value)return;
      const values=await listResources(kind);if(!owns())return;
      const mcpValues=kind==="skill"?await listResources("mcp"):[];if(!owns())return;
      // Immediate invocation Evidence exists only on the write response; reuse mutations opt into exact detail readback.
      const readback=authoritativeReadback?await getResource(kind,value.resource.resourceId):value;if(!owns())return;
      setSelected(readback);setItems(values);setMcps(mcpValues);preserveContext({resourceId:readback.resource.resourceId});
      if(atStart?.resourceId!==readback.resource.resourceId||atStart?.discoverySnapshots.at(-1)?.snapshotId!==readback.resource.discoverySnapshots.at(-1)?.snapshotId){setToolDraft(null);setInvocationTool("")}
      if(closeAuthoring){setAuthoring(null);setAuthoringName("")}
      onSuccess?.(value,readback);
      setRecovery(null);setError(null);setControlledState(null);
    }catch(reason){
      if(!owns())return;
      if(reason instanceof SkillMcpRequestError&&reason.status===409&&atStart){
        try{const authoritative=await getResource(kind,atStart.resourceId);if(!owns())return;setSelected(authoritative);setRecovery({attemptedVersion:atStart.aggregateVersion,authoritative});setControlledState(skillMcpControlledState(reason));setError(null)}
        catch(fetchReason){if(owns())fail(fetchReason)}
      }else fail(reason);
    }finally{if(owns()){writeInFlight.current=null;setBusy(false)}}
  }
  async function saveAuthoring(){if(!authoring||!authoringName.trim())return;if(authoringMode==="edit"){if(resource?.currentDraftRevisionId)await write(()=>editResource(resource,authoring),true)}else await write(()=>createResource(kind,authoringName.trim(),authoring),true)}
  async function act(operation:(resource:SkillMcpResource)=>Promise<ResourceProjection>){if(selected)await write(()=>operation(selected.resource))}
  function beginClone(){if(!resource)return;const revision=revisionForProjection(resource);if(!revision)return;setReuseReceipt(null);setReuseIntent({operation:"clone",sourceResourceId:resource.resourceId,sourceRevisionId:revision.revisionId,sourceDigest:revision.digest,targetName:`${resource.name} Copy`})}
  function beginSuccessor(){if(!resource?.publishedRevisionId||resource.currentDraftRevisionId)return;const revision=exactRevision(resource,resource.publishedRevisionId);if(!revision)return;setReuseReceipt(null);setReuseIntent({operation:"successor",sourceResourceId:resource.resourceId,sourceRevisionId:revision.revisionId,sourceDigest:revision.digest,targetName:resource.name})}
  async function prepareManifest(operation:"export"|"import"){
    if(!resource||writeInFlight.current)return;
    const current=requestId.current,sourceResourceId=resource.resourceId,token=Symbol();const owns=()=>current===requestId.current&&writeInFlight.current===token;
    writeInFlight.current=token;setBusy(true);setReuseReceipt(null);
    try{const manifest=await exportManifest(resource);if(!owns())return;setReuseIntent({operation,sourceResourceId,sourceRevisionId:manifest.sourceRevisionId,sourceDigest:manifest.sourceDigest,targetName:operation==="import"?`${manifest.name} Imported`:manifest.name,manifest});setError(null);setControlledState(null)}catch(reason){if(owns())fail(reason)}finally{if(owns()){writeInFlight.current=null;setBusy(false)}}
  }
  function finishExport(){if(!reuseIntent?.manifest||reuseIntent.operation!=="export")return;const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([JSON.stringify(reuseIntent.manifest,null,2)],{type:"application/json"}));link.download=`${reuseIntent.manifest.kind}-manifest.json`;link.click();URL.revokeObjectURL(link.href);setReuseReceipt({operation:"export",sourceResourceId:reuseIntent.sourceResourceId,sourceRevisionId:reuseIntent.sourceRevisionId,sourceDigest:reuseIntent.sourceDigest});setReuseIntent(null)}
  async function confirmReuse(){
    if(!resource||!reuseIntent||!reuseIntent.targetName.trim())return;const intent=reuseIntent;
    const receipt=(_:ResourceProjection,readback:ResourceProjection)=>{const target=revisionForProjection(readback.resource);const relationship=readback.resource.relationships.find(item=>item.sourceResourceId===intent.sourceResourceId&&item.sourceRevisionId===intent.sourceRevisionId);setReuseReceipt({operation:intent.operation,sourceResourceId:intent.sourceResourceId,sourceRevisionId:intent.sourceRevisionId,sourceDigest:intent.sourceDigest,targetResourceId:readback.resource.resourceId,targetRevisionId:target?.revisionId,targetDigest:target?.digest,relationshipType:relationship?.type,sourceRelationshipRecorded:Boolean(relationship)});setReuseIntent(null)};
    if(intent.operation==="clone")await write(()=>cloneResource(resource,intent.sourceRevisionId,intent.targetName.trim()),false,true,receipt);
    else if(intent.operation==="import"&&intent.manifest)await write(()=>importManifest(intent.manifest!,intent.targetName.trim()),false,true,receipt);
    else if(intent.operation==="successor")await write(()=>successorResource(kind,resource.resourceId,resource.aggregateVersion),false,true,receipt);
  }
  const resource=selected?.resource;const draft=resource?.revisions.find(item=>item.revisionId===resource.currentDraftRevisionId);const review=resource?.reviews.at(-1);
  const eligibleMcps=mcps.filter(item=>item.publishedRevisionId&&item.enabled);const eligibleMcp=eligibleMcps.find(item=>item.resourceId===bindingMcpId);const snapshot=resource?.discoverySnapshots.at(-1);const selection=resource?.toolSelections.filter(item=>item.snapshotId===snapshot?.snapshotId).at(-1);const selectedToolNames=toolDraft?.resourceId===resource?.resourceId&&toolDraft?.snapshotId===snapshot?.snapshotId?toolDraft?.names??[]:[];const invocationToolValue=selection?.toolNames.includes(invocationTool)?invocationTool:"";
  const title=kind==="skill"?"技能中心":"MCP 连接中心";
  return <main className="agent-workbench skill-mcp-workbench capability-center"><header className="agent-page-header"><div><p className="eyebrow">企业资源工作台</p><h1>{title}</h1><p>管理由后端持有的规范资源，包括编写、测试、发现、治理、调用与检查。</p></div><span className="agent-authority-note">PostgreSQL 权威数据</span></header>
    {loading&&<p role="status" className="agent-state">Loading authoritative {kind.toUpperCase()} resources…</p>}
    {busy&&<p role="status" aria-label="Workbench save status" className="agent-state">Saving governed {kind.toUpperCase()} state…</p>}
    {error&&<div role="alert" className="agent-error" aria-label={`${controlledState??"retryable"} state`}><strong>{controlledState??"Action unavailable"}</strong><span>{controlledState==="denied"||controlledState==="not found"?"The resource is unavailable or access is not authorized.":error}</span><button onClick={()=>void refresh(resource?.resourceId)}>Retry authoritative fetch</button></div>}
    {recovery&&<section role="alert" aria-label="Guided conflict recovery"><h2>{controlledState}: explicit recovery required</h2><dl><dt>Attempted aggregate version</dt><dd>{recovery.attemptedVersion}</dd><dt>Authoritative aggregate version</dt><dd>{recovery.authoritative.resource.aggregateVersion}</dd><dt>Authoritative revision</dt><dd>{recovery.authoritative.resource.revisions.at(-1)?.revisionId}</dd></dl><p>The authoritative resource was fetched. No lifecycle, invocation, or publication command was replayed; there is no safe operation input to preserve.</p><button onClick={()=>setRecovery(null)}>Acknowledge authoritative version</button></section>}
    <section className="agent-dashboard" aria-label="Resource metrics"><article><span>Resources in scope</span><strong>{items.length}</strong></article><article><span>Published and enabled</span><strong>{items.filter(item=>item.publishedRevisionId&&item.enabled).length}</strong></article><article><span>{kind==="skill"?"Saved test results":"Discovery snapshots"}</span><strong>{items.reduce((count,item)=>count+(kind==="skill"?item.testResults.length:item.discoverySnapshots.length),0)}</strong></article><article><span>{kind==="skill"?"Authorized consumers":"Recorded invocations"}</span><strong>{items.reduce((count,item)=>count+(kind==="skill"?item.relationships.length:item.invocations.length),0)}</strong></article></section>
    {authoring&&<section aria-label={`${kind.toUpperCase()} Draft authoring`}><ResourceAuthoring kind={kind} mode={authoringMode} name={authoringName} value={authoring} onName={setAuthoringName} onChange={setAuthoring}/><div className="agent-actions"><button className="primary" onClick={()=>void saveAuthoring()} disabled={busy||!authoringName.trim()||!authoring.description.trim()||authoring.capabilities.length===0||(kind==="skill"?!authoring.instructions?.trim():!authoring.endpoint?.startsWith("http"))}>保存 {kind.toUpperCase()} Draft</button><button disabled={busy} onClick={()=>setAuthoring(null)}>取消</button></div></section>}
    <div className="agent-layout"><CapabilityCenterDirectory kind={kind} items={items} loading={loading} busy={busy} query={query} lifecycle={state} selectedId={resource?.resourceId} onQueryChange={value=>{setQuery(value);preserveContext({query:value||null})}} onLifecycleChange={value=>{setState(value);preserveContext({lifecycle:value==="ALL"?null:value})}} onSelect={id=>void refresh(id)} onCreate={create}/>
      <section className="agent-detail">{!resource?<div className="agent-empty"><h2>Select a resource</h2><p>Builder, tests, discovery, Evidence and relationships appear here.</p></div>:<><header><div><span className={`agent-status status-${resource.lifecycleState.toLowerCase()}`}>{resource.lifecycleState}</span><h2>{resource.name}</h2><code>{resource.resourceId}</code></div><span className={`agent-availability ${resource.enabled?"enabled":"disabled"}`}>{resource.enabled?"Enabled":"Disabled"}</span></header>
        <CapabilityResourceDetails kind={kind} resource={resource}/>
        <div className="agent-view-tabs" role="tablist" aria-label="Resource projection"><button role="tab" aria-selected={projection==="product"} onClick={()=>setProjection("product")}>Product View</button><button role="tab" aria-selected={projection==="technical"} onClick={()=>setProjection("technical")}>Technical View</button></div>
        {projection==="technical"?<SkillMcpTechnicalProjection projection={selected}/>:<>{draft&&<><Builder kind={kind} draft={draft}/><section className="agent-review-card"><header><div><p className="eyebrow">Revision workflow</p><h3>Current draft</h3></div><span className={`agent-status status-${draft.state.toLowerCase()}`}>{draft.state}</span></header><label>Exact revision digest<input readOnly value={draft.digest}/></label><div className="agent-validation-panel"><strong>{draft.state==="DRAFT"?"Validation required":draft.state==="VALIDATED"?"Validation passed — exact review required":"Exact digest reviewed — ready to publish"}</strong><span>保存、Human review 与不可变发布是分离的治理动作。</span></div><div className="agent-actions workflow-actions">{draft.state==="DRAFT"&&<button onClick={editDraft} disabled={busy}>编辑当前 {kind.toUpperCase()} Draft</button>}{draft.state==="DRAFT"&&<button onClick={()=>act(item=>validateResource(kind,item.resourceId,item.aggregateVersion))} disabled={busy}>Validate draft</button>}{draft.state==="VALIDATED"&&<button onClick={()=>act(item=>reviewResource(kind,item.resourceId,item.aggregateVersion,draft.digest))} disabled={busy}>Human review exact digest</button>}{draft.state==="HUMAN_REVIEWED"&&review&&<button className="publish" onClick={()=>act(item=>publishResource(kind,item.resourceId,item.aggregateVersion,draft.digest,review.reviewId))} disabled={busy}>Publish immutable revision</button>}</div></section></>}
          <section className="agent-section" aria-label={`${kind.toUpperCase()} professional operations`}><header><div><p className="eyebrow">Professional operations</p><h3>{kind==="skill"?"Saved tests and comparison":"连接测试、发现、工具治理与管理调用"}</h3></div></header>
            {kind==="skill"?<><div className="resource-form-grid"><label>测试名称<input value={testName} onChange={event=>setTestName(event.target.value)}/></label><label>测试输入（JSON）<textarea value={testInput} onChange={event=>setTestInput(event.target.value)}/></label><label>期望输出（JSON）<textarea value={testExpected} onChange={event=>setTestExpected(event.target.value)}/></label></div><div className="agent-actions"><button onClick={()=>{try{void act(item=>saveTest(item,testName.trim(),json(testInput,"TEST_INPUT"),json(testExpected,"TEST_EXPECTED")))}catch(reason){setControlledState("validation error");setError(reason instanceof SkillMcpRequestError?reason.reasonCode:"TEST_JSON_INVALID")}}} disabled={busy||!testName.trim()}>Save test case</button>{resource.savedTests.at(-1)&&<button onClick={()=>act(item=>runTest(item,item.savedTests.at(-1)!.testId))} disabled={busy}>Run saved test</button>}</div><h4>Saved test cases</h4><ul>{resource.savedTests.map(test=><li key={test.testId}>{test.name} · <code>{test.testId}</code></li>)}</ul><h4>Test result comparison</h4><ul>{resource.testResults.map(result=><li key={result.resultId}><strong>{result.status}</strong> · revision <code>{result.revisionId}</code> · {result.errors.join(", ")||"expected equals actual"}</li>)}</ul></>:<>
              <div className="agent-actions"><button onClick={()=>act(healthMcp)} disabled={busy}>Test connection</button><button onClick={()=>act(discoverMcp)} disabled={busy}>Discover Tools, Resources and Prompts</button></div>
              <h4>连接测试历史</h4>{resource.healthObservations.length?<ul>{resource.healthObservations.map(item=><li key={item.observationId}><strong>{item.status}</strong> · {item.reasonCode} · client {item.protocolRevision} · server {item.serverProtocolRevision??"NOT_REPORTED"}</li>)}</ul>:<p role="status">尚无连接测试结果。</p>}
              <h4>Immutable discovery snapshots</h4>{snapshot?<><p><code>{snapshot.snapshotId}</code> · <code>{snapshot.digest}</code> · {snapshot.capturedAt}</p><p>{snapshot.catalog.tools.length} Tool(s) · {snapshot.catalog.resources.length} Resource(s) · {snapshot.catalog.prompts.length} Prompt(s)</p><fieldset><legend>显式选择受治理 Tool</legend>{snapshot.catalog.tools.map(item=><label className="agent-choice" key={item.name}><input type="checkbox" checked={selectedToolNames.includes(item.name)} onChange={()=>setToolDraft({resourceId:resource.resourceId,snapshotId:snapshot.snapshotId,names:selectedToolNames.includes(item.name)?selectedToolNames.filter(name=>name!==item.name):[...selectedToolNames,item.name]})}/><span>{item.name}<small>{item.description??"No description"} · inputSchema {JSON.stringify(item.inputSchema??{})}</small></span></label>)}</fieldset><button disabled={busy||selectedToolNames.length===0} onClick={()=>act(item=>selectTools(item,snapshot,selectedToolNames))}>Govern explicit Tool selection</button></>:<p role="status">尚无 discovery authority；连接测试不等于工具发现。</p>}
              {snapshot&&!selection&&<p role="status">当前 snapshot 尚无已保存的 Tool selection；请显式重新选择并保存。</p>}{selection&&<div className="resource-form-grid"><label>管理调用 Tool<select aria-label="管理调用 Tool" value={invocationToolValue} onChange={event=>setInvocationTool(event.target.value)}><option value="">请选择已治理 Tool</option>{selection.toolNames.map(name=><option key={name}>{name}</option>)}</select></label><label>管理调用输入（JSON）<textarea aria-label="管理调用输入（JSON）" value={invocationInput} onChange={event=>setInvocationInput(event.target.value)}/></label><button className="primary" disabled={busy||!invocationToolValue} onClick={()=>{try{void act(item=>invokeMcp(item,selection.selectionId,invocationToolValue,json(invocationInput,"MCP_INVOCATION_INPUT")))}catch(reason){setControlledState("validation error");setError(reason instanceof SkillMcpRequestError?reason.reasonCode:"MCP_INVOCATION_INPUT_JSON_INVALID")}}}>Authorize bounded management invocation</button></div>}
              <section aria-label="MCP snapshot and selection history"><h4>Discovery and selection history</h4><ul>{resource.discoverySnapshots.map(item=><li key={item.snapshotId}>Snapshot <code>{item.snapshotId}</code> · digest <code>{item.digest}</code></li>)}</ul><ul>{resource.toolSelections.map(item=><li key={item.selectionId}>Selection <code>{item.selectionId}</code> · snapshot <code>{item.snapshotId}</code> · {item.toolNames.join(", ")}</li>)}</ul></section><h4>Schema/version drift</h4><p>{resource.driftRecords.length?`${resource.driftRecords.length} drift record(s) require inspection.`:"No drift detected between captured snapshots."}</p><h4>管理调用历史</h4>{resource.invocations.length?<ol>{resource.invocations.map(item=><li key={item.invocationId}><strong>{item.status}</strong> · {item.toolName} · <code>{item.invocationId}</code> · selection <code>{item.selectionId??"未提供"}</code> · snapshot <code>{resource.toolSelections.find(selection=>selection.selectionId===item.selectionId)?.snapshotId??"未提供"}</code> · {item.reasonCode} · input {JSON.stringify(item.input??{})} · result {JSON.stringify(item.result??{})}</li>)}</ol>:<p role="status">尚无管理调用记录；这不表示 Attempt 执行成功。</p>}
            </>}
            {selected?.invocation&&<div role="status" aria-label="Invocation Evidence status" className="agent-invocation"><span className={`agent-status status-${selected.invocation.status.toLowerCase()}`}>{selected.invocation.status}</span><div><strong>{kind==="skill"?"Invocation Evidence recorded":"管理调用即时结果已保留"}</strong><p>{selected.invocation.reasonCode??"SUCCEEDED"}; credential values redacted: {String(selected.invocation.evidence.redacted)}; ambiguous side effects were not retried.</p><pre>{JSON.stringify(selected.invocation.result,null,2)}</pre><p>{kind==="skill"?"管理测试不是 Attempt 级真实 invocation。":"此结果不是 Attempt-level governed MCP invocation Evidence。"}</p></div></div>}
          </section>
          <section className="agent-section"><header><div><p className="eyebrow">Governed lifecycle</p><h3>Publication, relationships and consumers</h3></div></header>
            {kind==="skill"&&resource.publishedRevisionId&&resource.bindings.length===0&&<div className="resource-form-grid"><label>选择精确 MCP<select aria-label="选择精确 MCP" value={bindingMcpId} onChange={event=>setBindingMcpId(event.target.value)}><option value="">请选择已发布且启用的 MCP</option>{eligibleMcps.map(item=><option value={item.resourceId} key={item.resourceId}>{item.name} · {item.resourceId} · {item.publishedRevisionId}</option>)}</select></label><label>共同能力 / operation<select aria-label="选择共同能力" value={bindingCapability} onChange={event=>setBindingCapability(event.target.value)}><option value="">请选择</option>{eligibleMcp&&resource.revisions.find(item=>item.revisionId===resource.publishedRevisionId)?.content.capabilities.filter(capability=>eligibleMcp.revisions.find(item=>item.revisionId===eligibleMcp.publishedRevisionId)?.content.capabilities.includes(capability)).map(capability=><option key={capability}>{capability}</option>)}</select></label></div>}
            {kind==="skill"&&resource.bindings.at(-1)&&<label>管理测试输入（JSON）<textarea value={invocationInput} onChange={event=>setInvocationInput(event.target.value)}/></label>}
            <div className="agent-actions">
              {resource.publishedRevisionId&&!resource.currentDraftRevisionId&&<button onClick={beginSuccessor} disabled={busy}>Create successor Draft</button>}
              <button onClick={beginClone} disabled={busy}>Clone exact revision</button>
              <button onClick={()=>void prepareManifest("export")} disabled={busy}>Export bounded manifest</button>
              <button onClick={()=>void prepareManifest("import")} disabled={busy}>Import bounded manifest copy</button>
              <button onClick={()=>act(item=>lifecycleResource(kind,item.resourceId,item.enabled?"DISABLE":"ENABLE",item.aggregateVersion))} disabled={busy}>{resource.enabled?"Disable":"Enable"}</button>
              {kind==="skill"&&resource.publishedRevisionId&&eligibleMcp&&bindingCapability&&resource.bindings.length===0&&<button onClick={()=>act(item=>bindCapability(item,eligibleMcp,bindingCapability))} disabled={busy}>Bind exact MCP capability</button>}
              {kind==="skill"&&resource.bindings.at(-1)&&<button onClick={()=>{try{void act(item=>invokeCapability(item,item.bindings.at(-1)!.bindingId,json(invocationInput,"INVOCATION_INPUT")))}catch(reason){setControlledState("validation error");setError(reason instanceof SkillMcpRequestError?reason.reasonCode:"INVOCATION_JSON_INVALID")}}} disabled={busy}>Authorize bounded capability test</button>}
            </div>
            <p>{resource.relationships.length} governed relationship(s) · 管理测试不是 Attempt 级真实 invocation · published history is immutable.</p>
            {resource.publishedRevisionId&&<button className="danger" onClick={()=>act(item=>lifecycleResource(kind,item.resourceId,"DEPRECATE",item.aggregateVersion))} disabled={busy||resource.lifecycleState==="DEPRECATED"}>Deprecate</button>}
          </section>
          {reuseIntent&&<section className="agent-section reuse-confirmation" aria-label="Reuse operation confirmation"><header><div><p className="eyebrow">Explicit confirmation</p><h3>{operationLabel[reuseIntent.operation]}</h3></div></header>
            <p>{reuseIntent.operation==="clone"?"Creates a separate DRAFT resource; the source remains unchanged.":reuseIntent.operation==="import"?"Creates a separate DRAFT from the bounded manifest. The current import contract does not persist a source relationship.":reuseIntent.operation==="export"?"Downloads a bounded manifest without changing either resource or lifecycle state. Credential material is excluded.":"Keeps the published revision immutable and creates a DRAFT successor on the same resource."}</p>
            {reuseIntent.operation==="clone"&&<label>Exact source revision<select aria-label="Exact source revision" value={reuseIntent.sourceRevisionId} onChange={event=>{const revision=exactRevision(resource,event.target.value);if(revision)setReuseIntent({...reuseIntent,sourceRevisionId:revision.revisionId,sourceDigest:revision.digest})}}>{resource.revisions.map(revision=><option key={revision.revisionId} value={revision.revisionId}>{revision.state} · {revision.revisionId}</option>)}</select></label>}
            {(reuseIntent.operation==="clone"||reuseIntent.operation==="import")&&<label>New resource name<input aria-label="New resource name" value={reuseIntent.targetName} maxLength={120} onChange={event=>setReuseIntent({...reuseIntent,targetName:event.target.value})}/></label>}
            <dl className="technical-grid"><dt>Source resource</dt><dd><code>{reuseIntent.sourceResourceId}</code></dd><dt>Source revision</dt><dd><code>{reuseIntent.sourceRevisionId}</code></dd><dt>Source digest</dt><dd><code>{reuseIntent.sourceDigest}</code></dd>{reuseIntent.manifest&&<><dt>Manifest version</dt><dd><code>{reuseIntent.manifest.manifestVersion}</code></dd><dt>Credential material</dt><dd><code>{reuseIntent.manifest.credentialMaterial}</code></dd></>}</dl>
            <div className="agent-actions"><button className="primary" disabled={busy||!reuseIntent.targetName.trim()} onClick={()=>reuseIntent.operation==="export"?finishExport():void confirmReuse()}>Confirm {operationLabel[reuseIntent.operation]}</button><button disabled={busy} onClick={()=>setReuseIntent(null)}>Cancel</button></div>
          </section>}
          {reuseReceipt&&<section className="agent-section reuse-receipt" role="status" aria-label="Reuse operation completion"><header><div><p className="eyebrow">Authoritative completion</p><h3>{operationLabel[reuseReceipt.operation]} completed</h3></div></header>
            <dl className="technical-grid"><dt>Source resource</dt><dd><code>{reuseReceipt.sourceResourceId}</code></dd><dt>Source revision</dt><dd><code>{reuseReceipt.sourceRevisionId}</code></dd><dt>Source digest</dt><dd><code>{reuseReceipt.sourceDigest}</code></dd>{reuseReceipt.targetResourceId&&<><dt>Read-back target resource</dt><dd><code>{reuseReceipt.targetResourceId}</code></dd><dt>Read-back target revision</dt><dd><code>{reuseReceipt.targetRevisionId??"NO_REVISION"}</code></dd><dt>Read-back target digest</dt><dd><code>{reuseReceipt.targetDigest??"NO_DIGEST"}</code></dd><dt>Source relationship</dt><dd><code>{reuseReceipt.sourceRelationshipRecorded?reuseReceipt.relationshipType:"NOT_RECORDED_BY_BACKEND"}</code></dd></>}</dl>
          </section>}
          <section className="agent-section"><h3>Revision diff and history</h3><ol className="agent-history">{resource.revisions.map((item,index)=><li key={item.revisionId}><span className={`agent-status status-${item.state.toLowerCase()}`}>{item.state}</span><code>{item.revisionId}</code><small>{index?` successor of ${item.predecessorRevisionId}`:" initial revision"}</small></li>)}</ol></section></>}</>}</section></div>
  </main>;
}
export function SkillWorkbenchPage(){return <ResourceWorkbench kind="skill"/>}
