import {expect,test} from "@playwright/test";
async function createAgent(page:import("@playwright/test").Page,name:string){await page.getByRole("button",{name:"创建 Agent Draft"}).click();await page.getByLabel("Agent 名称").fill(name);await page.getByLabel("角色标题").fill("供应商质量分析员");await page.getByLabel("业务目的").fill("分析供应商质量并提供有据可查的建议");await page.getByLabel("职责（逗号分隔）").fill("分析质量记录");await page.getByLabel("业务能力（逗号分隔）").fill("supplier-quality-analysis");await page.getByRole("button",{name:"保存 Agent Draft"}).click();await expect(page.getByRole("heading",{name})).toBeVisible()}
test("真实输入创建、编辑并发布精确 Agent revision",async({page})=>{await page.goto("/agents");await expect(page.getByRole("heading",{name:"Agent Workbench"})).toBeVisible();await createAgent(page,"质量分析 Agent");await page.getByRole("button",{name:"编辑当前 Draft"}).click();await expect(page.getByLabel("Agent 名称")).toHaveAttribute("readonly","");await page.getByLabel("业务目的").fill("分析供应商质量、读取受治理资源并形成建议");await page.getByRole("button",{name:"保存 Agent Draft"}).click();await expect(page.getByText(/读取受治理资源/)).toBeVisible();await page.getByRole("button",{name:"Validate draft"}).click();await page.getByRole("button",{name:"Human review exact digest"}).click();await page.getByRole("button",{name:"Publish immutable revision"}).click();await expect(page.locator(".agent-detail").getByText("PUBLISHED",{exact:true}).first()).toBeVisible();await page.getByRole("button",{name:"Export bounded manifest"}).click();await expect(page.getByLabel("Bounded Agent manifest")).toContainText("agent-definition.v1");await expect(page.getByText("Definition 发布不等于 Agent Instance 运行或执行授权。")).toBeVisible()});
test("目录上下文、迟到详情与同步重复提交隔离",async({page})=>{const suffix=Date.now().toString(),firstName=`第一 Agent ${suffix}`,secondName=`第二 Agent ${suffix}`;await page.goto("/agents");await createAgent(page,firstName);const firstId=(await page.locator(".agent-detail > header code").textContent())!.trim();await page.getByRole("button",{name:"创建 Agent Draft"}).click();await page.getByLabel("Agent 名称").fill(secondName);await page.getByLabel("角色标题").fill("第二角色");await page.getByLabel("业务目的").fill("验证目录竞态");await page.getByLabel("职责（逗号分隔）").fill("检查");await page.getByLabel("业务能力（逗号分隔）").fill("inspect");const save=page.getByRole("button",{name:"保存 Agent Draft"});await save.dblclick();await expect(page.getByRole("heading",{name:secondName})).toBeVisible();await page.getByLabel("搜索 Agent 目录").fill(suffix);await page.getByLabel("Agent 生命周期筛选").selectOption("DRAFT");await page.reload();await expect(page.getByLabel("搜索 Agent 目录")).toHaveValue(suffix);let release!:()=>void,started!:()=>void;const waiting=new Promise<void>(resolve=>started=resolve),held=new Promise<void>(resolve=>release=resolve);await page.route("**/*",async route=>{if(decodeURIComponent(new URL(route.request().url()).pathname).endsWith(`/${firstId}`)){started();await held}await route.continue()});await page.locator(".agent-list button").filter({hasText:firstName}).click();await waiting;await page.locator(".agent-list button").filter({hasText:secondName}).click();await expect(page.getByRole("heading",{name:secondName})).toBeVisible();release();await page.waitForTimeout(100);await expect(page.getByRole("heading",{name:secondName})).toBeVisible();expect(new URL(page.url()).searchParams.get("query")).toBe(suffix);expect(new URL(page.url()).searchParams.get("lifecycle")).toBe("DRAFT");await page.setViewportSize({width:390,height:844});await page.reload();await page.getByLabel("搜索 Agent 目录").focus();await expect(page.getByLabel("搜索 Agent 目录")).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)});
test("Agent stale CAS 保留输入且不自动重放",async({page})=>{const name=`CAS Agent ${Date.now()}`;await page.goto("/agents");await createAgent(page,name);const id=(await page.locator(".agent-detail > header code").textContent())!.trim();await page.getByRole("button",{name:"编辑当前 Draft"}).click();await page.getByLabel("业务目的").fill("用户尚未提交的冲突输入");const external=await page.evaluate(async resourceId=>{const detail=await (await fetch(`/api/internal/v0.2.2/agent-definitions/${encodeURIComponent(resourceId)}`)).json();const response=await fetch(`/api/internal/v0.2.2/agent-definitions/${encodeURIComponent(resourceId)}/draft`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({expectedVersion:detail.definition.aggregateVersion,content:{...detail.definition.revisions.at(-1).content,businessPurpose:"并发权威更新"}})});return response.status},id);expect(external).toBe(200);await page.getByRole("button",{name:"保存 Agent Draft"}).click();await expect(page.getByRole("alert",{name:"Guided conflict recovery"})).toBeVisible();await expect(page.getByLabel("业务目的")).toHaveValue("用户尚未提交的冲突输入");const authoritative=await page.evaluate(async resourceId=>(await (await fetch(`/api/internal/v0.2.2/agent-definitions/${encodeURIComponent(resourceId)}`)).json()).definition,id);expect(authoritative.aggregateVersion).toBe(2);expect(authoritative.revisions).toHaveLength(2)});

for(const operation of ["edit","lifecycle"] as const)test("agent write directory readback cannot own later selection or write: "+operation,async({page})=>{
  await page.goto("/agents");
  const suffix=Date.now(),names=[`race A agent ${suffix}`, `race B agent ${suffix}`];const ids:string[]=[];
  for(const name of names){await createAgent(page,name);ids.push((await page.locator(".agent-detail > header code").textContent())!.trim())}
  const read=()=>page.evaluate(async root=>(await(await fetch(root)).json()),"/api/internal/v0.2.2/agent-definitions");const before=await read();
  await page.locator(".agent-list button").filter({hasText:names[0]}).click();await expect(page.getByRole("heading",{name:names[0],exact:true})).toBeVisible();
  let release!:()=>void,started!:()=>void;const held=new Promise<void>(resolve=>release=resolve),waiting=new Promise<void>(resolve=>started=resolve);let delayed=false;
  await page.route("**/api/internal/**",async route=>{if(route.request().method()==="GET"&&new URL(route.request().url()).pathname==="/api/internal/v0.2.2/agent-definitions"&&!delayed){delayed=true;const response=await route.fetch();started();await held;await route.fulfill({response})}else await route.continue()});
  if(operation==="edit"){await page.getByRole("button",{name:"编辑当前 Draft"}).click();await expect(page.getByLabel("Agent 名称")).toHaveAttribute("readonly","");await page.getByLabel("业务目的",{exact:true}).fill("directory race saved content");await page.getByRole("button",{name:"保存 Agent Draft"}).click()}else await page.getByRole("button",{name:"Disable",exact:true}).click();
  await waiting;await page.locator(".agent-list button").filter({hasText:names[1]}).click();await expect(page.getByRole("heading",{name:names[1],exact:true})).toBeVisible();
  let releaseB!:()=>void,startedB!:()=>void;const heldB=new Promise<void>(resolve=>releaseB=resolve),waitingB=new Promise<void>(resolve=>startedB=resolve);
  await page.route("**/disable",async route=>{startedB();await heldB;await route.continue()});
  await page.getByRole("button",{name:"Disable",exact:true}).click();await waitingB;
  const responseA=page.waitForResponse(response=>new URL(response.url()).pathname==="/api/internal/v0.2.2/agent-definitions"&&response.request().method()==="GET");release();await responseA;await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
  await expect(page.getByRole("heading",{name:names[1],exact:true})).toBeVisible();expect(new URL(page.url()).searchParams.get("resourceId")).toBe(ids[1]);
  await expect(page.getByRole("status",{name:"Agent save status"})).toBeVisible();await expect(page.getByRole("button",{name:"Disable",exact:true})).toBeDisabled();
  releaseB();await expect(page.getByRole("button",{name:"Enable",exact:true})).toBeEnabled();await expect(page.getByRole("alert")).toHaveCount(0);
  const after=await read();expect(after).toHaveLength(before.length);expect(after.some((item:{definitionId:string})=>item.definitionId===ids[0])).toBe(true);
});

test("Builder explicitly selects every governed binding and exposes authoritative identities before review",async({page})=>{
  await page.setExtraHTTPHeaders({"X-Tenant-ID":`s5-builder-${Date.now()}`,"X-Security-Domain":"supplier-quality","X-Principal-ID":"console-user"});
  const {createServer}=await import("node:http");
  const server=createServer((request,response)=>{let raw="";request.on("data",chunk=>raw+=chunk);request.on("end",()=>{const message=JSON.parse(raw);if(message.method==="notifications/initialized"){response.writeHead(202);response.end();return}const result=message.method==="initialize"?{protocolVersion:"2025-06-18",capabilities:{},serverInfo:{name:"builder-test",version:"1"}}:message.method==="tools/list"?{tools:[{name:"quality.lookup",inputSchema:{type:"object"}}]}:message.method==="resources/list"?{resources:[]}:message.method==="prompts/list"?{prompts:[]}:{};response.writeHead(200,{"Content-Type":"application/json","Mcp-Session-Id":"builder-test"});response.end(JSON.stringify({jsonrpc:"2.0",id:message.id,result}))})});
  await new Promise<void>((resolve,reject)=>{server.once("error",reject);server.listen(8769,"127.0.0.1",resolve)});
  try{
    await page.goto("/agents");
    const prepared=await page.evaluate(async()=>{
      async function post(root:string,data:unknown){const response=await fetch(root,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!response.ok)throw new Error(`Binding preparation failed: ${response.status}`);return response.json()}
      async function publish(root:string,value:Awaited<ReturnType<typeof post>>,key:string,idKey:string){let record=value[key];const path=`${root}/${encodeURIComponent(record[idKey])}`;value=await post(`${path}/validation`,{expectedVersion:record.aggregateVersion});record=value[key];const draft=record.revisions.find((item:{revisionId:string})=>item.revisionId===record.currentDraftRevisionId);value=await post(`${path}/reviews`,{expectedVersion:record.aggregateVersion,digest:draft.digest,decision:"APPROVE",reason:"Explicit Builder binding regression"});record=value[key];return post(`${path}/publications`,{expectedVersion:record.aggregateVersion,digest:draft.digest,...(record.reviews?.at(-1)?.reviewId?{reviewId:record.reviews.at(-1).reviewId}:{})})}
      const root="/api/internal/v0.2.2",suffix=Date.now();
      const skill=await publish(`${root}/resources/skill`,await post(`${root}/resources/skill`,{name:`Builder Skill ${suffix}`,content:{description:"Builder exact resource",instructions:"Read governed evidence",capabilities:["supplier-quality-analysis"]}}),"resource","resourceId");
      let mcp=await publish(`${root}/resources/mcp`,await post(`${root}/resources/mcp`,{name:`Builder MCP ${suffix}`,content:{description:"Builder exact tool",capabilities:["supplier-quality-analysis"],endpoint:"http://127.0.0.1:8769",timeoutSeconds:2,sideEffect:"NONE",idempotency:"IDEMPOTENT"}}),"resource","resourceId");
      const mcpPath=`${root}/resources/mcp/${encodeURIComponent(mcp.resource.resourceId)}`;
      mcp=await post(`${mcpPath}/discovery`,{expectedVersion:mcp.resource.aggregateVersion,timeoutSeconds:2});
      const snapshotId=mcp.resource.discoverySnapshots.at(-1).snapshotId;
      mcp=await post(`${mcpPath}/tool-selections`,{expectedVersion:mcp.resource.aggregateVersion,snapshotId,toolNames:["quality.lookup"],reason:"Explicit Builder regression prerequisite"});
      const knowledge=await publish(`${root}/knowledge`,await post(`${root}/knowledge`,{name:`Builder Knowledge ${suffix}`,source:{sourceId:`source:builder-${suffix}`,documentId:`document:builder-${suffix}`,kind:"TEXT",provenance:"human:builder-review",content:"Verify supplier quality evidence."}}),"knowledge","knowledgeId");
      const runtime=await publish(`${root}/runtime-profiles`,await post(`${root}/runtime-profiles`,{name:`Builder Runtime ${suffix}`,content:{provider:"OPENCLAW",resources:{cpuRequest:"100m",cpuLimit:"500m",memoryRequest:"128Mi",memoryLimit:"512Mi"},isolation:"NAMESPACE",stateMode:"STATELESS",sessionAffinity:"NONE",secretReferences:[],openClawPackageRef:"openclaw://bounded/builder@1"}}),"profile","runtimeProfileId");
      const workflow=await publish(`${root}/workflow-definitions`,await post(`${root}/workflow-definitions`,{name:`Builder Workflow ${suffix}`,content:{description:"Builder workflow",runtimeProfile:{kind:"RUNTIME_PROFILE",resourceId:runtime.profile.runtimeProfileId,revisionId:runtime.profile.publishedRevisionId},inputs:["records"],outputs:["analysis"],tasks:[{taskId:"analyze",name:"Analyze",dependsOn:[],inputs:["records"],outputs:["analysis"],capabilityRequirements:["supplier-quality-analysis"],references:[],retryLimit:1,timeoutSeconds:300,failurePolicy:"FAIL_WORKFLOW"}]}}),"definition","workflowDefinitionId");
      return {skill:skill.resource,mcp:mcp.resource,knowledge:knowledge.knowledge,runtime:runtime.profile,workflow:workflow.definition,snapshotId};
    });
    await page.reload();await expect(page.getByRole("status").filter({hasText:"正在读取"})).toHaveCount(0);
    await page.getByRole("button",{name:"创建 Agent Draft"}).click();
    const name=`Explicit bound Agent ${Date.now()}`;
    await page.getByLabel("Agent 名称").fill(name);await page.getByLabel("角色标题").fill("Quality Analyst");await page.getByLabel("业务目的").fill("Verify exact bindings");await page.getByLabel("职责（逗号分隔）").fill("Analyze");await page.getByLabel("业务能力（逗号分隔）").fill("supplier-quality-analysis");
    const builder=page.getByRole("region",{name:"Agent Draft authoring"});
    await builder.getByRole("checkbox",{name:new RegExp(prepared.skill.name)}).check();await builder.getByRole("checkbox",{name:new RegExp(prepared.knowledge.name)}).check();
    await builder.getByLabel("MCP 连接").selectOption(prepared.mcp.resourceId);await builder.getByLabel("受治理 Tool").selectOption("quality.lookup");await builder.getByLabel("Workflow Definition",{exact:true}).selectOption(prepared.workflow.workflowDefinitionId);await builder.getByLabel("Runtime Profile",{exact:true}).selectOption(prepared.runtime.runtimeProfileId);
    const before=builder.getByRole("region",{name:"Agent exact resource bindings"});
    for(const record of [prepared.skill,prepared.mcp,prepared.knowledge,prepared.workflow,prepared.runtime]){const revision=record.revisions.find((item:{revisionId:string})=>item.revisionId===record.publishedRevisionId);await expect(before).toContainText(revision.revisionId);await expect(before).toContainText(revision.digest.replace(/^sha256:/,""))}
    await expect(before).toContainText(prepared.snapshotId);await expect(before).toContainText("quality.lookup");await expect(before).toContainText("未提供 / 未验证");
    await page.getByRole("button",{name:"保存 Agent Draft"}).click();await expect(page.getByRole("heading",{name,exact:true})).toBeVisible();
    const id=(await page.locator(".agent-detail > header code").textContent())!.trim();
    const authoritative=await page.evaluate(async id=>(await(await fetch(`/api/internal/v0.2.2/agent-definitions/${encodeURIComponent(id)}`)).json()).definition,id);
    const bindings=authoritative.revisions.at(-1).content.bindings;
    expect(bindings.skills[0].resourceId).toBe(prepared.skill.resourceId);expect(bindings.mcpTools[0].resourceId).toBe(prepared.mcp.resourceId);expect(bindings.mcpTools[0].snapshotId).toBe(prepared.snapshotId);expect(bindings.mcpTools[0].toolName).toBe("quality.lookup");expect(bindings.knowledge[0].resourceId).toBe(prepared.knowledge.knowledgeId);expect(bindings.workflow.resourceId).toBe(prepared.workflow.workflowDefinitionId);expect(bindings.runtimeProfile.resourceId).toBe(prepared.runtime.runtimeProfileId);
    await page.getByRole("button",{name:"Validate draft"}).click();await expect(page.getByRole("button",{name:"Human review exact digest"})).toBeEnabled();
    const details=page.locator(".agent-detail").getByRole("region",{name:"Agent exact resource bindings"});
    for(const binding of [...bindings.skills,...bindings.mcpTools,...bindings.knowledge,bindings.workflow,bindings.runtimeProfile]){for(const identity of [binding.resourceId,binding.revisionId,binding.digest])await expect(details).toContainText(identity)}
    await expect(details).toContainText(prepared.snapshotId);await expect(details).toContainText("quality.lookup");
  }finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()))}
});
