/* eslint-disable @typescript-eslint/no-explicit-any, prefer-const */
import {createServer,type Server} from "node:http";
import {expect,test,type APIRequestContext} from "@playwright/test";
import {backendUrl,restartOwnedBackend} from "../harness/ownedBackend";

const backend=backendUrl();
const headers={"X-Tenant-ID":`s5-impl-053-evidence-${process.pid}`,"X-Security-Domain":"unified-product-assembly","X-Principal-ID":"human:s5-impl-053-reviewer"};
type J=Record<string,any>;let provider:Server;
async function post(request:APIRequestContext,route:string,data:unknown){const response=await request.post(`${backend}${route}`,{headers,data});expect(response.ok(),`${route}: ${await response.text()}`).toBe(true);return response.json() as Promise<J>}
async function publish(request:APIRequestContext,root:string,value:J,key:string,idKey:string){let record=value[key],id=record[idKey];value=await post(request,`${root}/${encodeURIComponent(id)}/validation`,{expectedVersion:record.aggregateVersion});record=value[key];const draft=record.revisions.find((item:J)=>item.revisionId===record.currentDraftRevisionId);value=await post(request,`${root}/${encodeURIComponent(id)}/reviews`,{expectedVersion:record.aggregateVersion,digest:draft.digest,decision:"APPROVE",reason:"S5-IMPL-053 exact browser evidence"});record=value[key];const review=record.reviews?.at(-1);return post(request,`${root}/${encodeURIComponent(id)}/publications`,{expectedVersion:record.aggregateVersion,digest:draft.digest,...(review?.reviewId?{reviewId:review.reviewId}:{})})}
function active(value:J,key:string){const record=value[key];return record.revisions.find((item:J)=>item.revisionId===record.publishedRevisionId||item.revisionId===record.currentDraftRevisionId)}
async function restartBackend(request:APIRequestContext){await restartOwnedBackend();await expect.poll(async()=>{try{return(await request.get(`${backend}/healthz`,{timeout:500})).status()}catch{return 0}},{timeout:20_000}).toBe(200)}
async function startProvider(){provider=createServer((request,response)=>{let raw="";request.on("data",chunk=>raw+=chunk);request.on("end",()=>{const input=JSON.parse(raw);const body=request.url?.endsWith("/embeddings")?{data:input.input.map((_:string,index:number)=>({index,embedding:[1,index+1,0]}))}:{choices:[{message:{content:JSON.stringify({classification:"SUPPLIER_QUALITY",summary:"Governed supplier quality plan",needs_clarification:false,tasks:[{title:"Analyze supplier quality",purpose:"Establish a verified corrective plan"}]})}}]};response.writeHead(200,{"Content-Type":"application/json"});response.end(JSON.stringify(body))})});await new Promise<void>((resolve,reject)=>{provider.once("error",reject);provider.listen(8767,"127.0.0.1",resolve)});Object.assign(process.env,{S5_PLANNING_PROVIDER:"openai-compatible",S5_PLANNING_BASE_URL:"http://127.0.0.1:8767/v1/",S5_PLANNING_API_KEY:"bounded-test-key",S5_PLANNING_MODEL:"s5-evidence-planner",S5_EMBEDDING_PROVIDER:"openai-compatible",S5_EMBEDDING_BASE_URL:"http://127.0.0.1:8767/v1/",S5_EMBEDDING_API_KEY:"bounded-test-key",S5_EMBEDDING_MODEL:"s5-evidence-embedding"})}

test.afterAll(async()=>{if(provider)await new Promise<void>((resolve,reject)=>provider.close(error=>error?reject(error):resolve()))});

test("proves the complete durable unified-product browser journey",async({page,request})=>{test.setTimeout(180_000);await page.setExtraHTTPHeaders(headers);await startProvider();await restartBackend(request);
  let skill=await post(request,"/api/internal/v0.2.2/resources/skill",{name:"S5 Unified Supplier Quality Skill",content:{description:"Analyze supplier quality",capabilities:["supplier-quality-analysis"],instructions:"Use verified quality evidence."}});skill=await publish(request,"/api/internal/v0.2.2/resources/skill",skill,"resource","resourceId");
  let mcpResource=await post(request,"/api/internal/v0.2.2/resources/mcp",{name:"S5 Unified Quality MCP Definition",content:{description:"Governed definition; no callable Public Preview endpoint",capabilities:["supplier-quality-analysis"],endpoint:"https://unconfigured.invalid/mcp",timeoutSeconds:2,sideEffect:"NONE",idempotency:"IDEMPOTENT"}});mcpResource=await publish(request,"/api/internal/v0.2.2/resources/mcp",mcpResource,"resource","resourceId");expect(mcpResource.resource.discoverySnapshots).toHaveLength(0);expect(mcpResource.resource.toolSelections).toHaveLength(0);expect(mcpResource.resource.invocations).toHaveLength(0);
  let knowledge=await post(request,"/api/internal/v0.2.2/knowledge",{name:"S5 Unified Quality Knowledge",source:{sourceId:"source:s5-unified-quality",documentId:"document:s5-quality",kind:"TEXT",provenance:"human:s5-impl-053-reviewer",content:"Supplier containment starts immediately. Root cause analysis must cite verified evidence."}});knowledge=await publish(request,"/api/internal/v0.2.2/knowledge",knowledge,"knowledge","knowledgeId");knowledge=await post(request,`/api/internal/v0.2.2/knowledge/${knowledge.knowledge.knowledgeId}/ingestion`,{expectedVersion:knowledge.knowledge.aggregateVersion});knowledge=await post(request,`/api/internal/v0.2.2/knowledge/${knowledge.knowledge.knowledgeId}/retrievals`,{expectedVersion:knowledge.knowledge.aggregateVersion,authorization:"ALLOW",authorizationDecisionId:"authorization:s5-pv106-browser",query:"How should supplier containment begin?"});const retrieval=knowledge.knowledge.retrievals.at(-1);expect(retrieval.snapshotId).toBe(knowledge.knowledge.activeIndexSnapshotId);expect(retrieval.citations.length).toBeGreaterThan(0);expect(retrieval.citations[0].knowledgeId).toBe(knowledge.knowledge.knowledgeId);
  let runtime=await post(request,"/api/internal/v0.2.2/runtime-profiles",{name:"S5 Unified Runtime Profile",content:{provider:"OPENCLAW",resources:{cpuRequest:"100m",cpuLimit:"500m",memoryRequest:"128Mi",memoryLimit:"512Mi"},isolation:"NAMESPACE",stateMode:"STATELESS",sessionAffinity:"NONE",secretReferences:[],openClawPackageRef:"openclaw://bounded/s5-evidence@1"}});runtime=await publish(request,"/api/internal/v0.2.2/runtime-profiles",runtime,"profile","runtimeProfileId");
  const skillRevision=active(skill,"resource"),knowledgeRevision=active(knowledge,"knowledge"),runtimeRevision=active(runtime,"profile");
  let workflow=await post(request,"/api/internal/v0.2.2/workflow-definitions",{name:"S5 Unified Quality Workflow",content:{description:"Supplier quality response",inputs:["quality-records"],outputs:["reviewed-analysis"],runtimeProfile:{kind:"RUNTIME_PROFILE",resourceId:runtime.profile.runtimeProfileId,revisionId:runtimeRevision.revisionId},tasks:[{taskId:"analyze",name:"Analyze supplier quality",dependsOn:[],inputs:["quality-records"],outputs:["analysis"],capabilityRequirements:["supplier-quality-analysis"],references:[],retryLimit:1,timeoutSeconds:300,failurePolicy:"FAIL_WORKFLOW"}]}});workflow=await publish(request,"/api/internal/v0.2.2/workflow-definitions",workflow,"definition","workflowDefinitionId");const workflowRevision=active(workflow,"definition");
  workflowRevision.digest=workflowRevision.digest.replace("sha256:","");runtimeRevision.digest=runtimeRevision.digest.replace("sha256:","");
  let agent=await post(request,"/api/internal/v0.2.2/agent-definitions",{name:"S5 Unified Supplier Quality Agent",content:{title:"Supplier Quality Analyst",duties:["Analyze supplier quality"],data:["quality records"],knowledge:["verified procedure"],skills:["root cause analysis"],capabilities:["supplier-quality-analysis"],runtimes:["bounded OpenClaw declaration"],businessPurpose:"Analyze supplier quality",bindings:{skills:[{resourceId:skill.resource.resourceId,revisionId:skillRevision.revisionId,digest:skillRevision.digest}],mcpTools:[],knowledge:[{resourceId:knowledge.knowledge.knowledgeId,revisionId:knowledgeRevision.revisionId,digest:knowledgeRevision.digest,snapshotId:knowledge.knowledge.activeIndexSnapshotId}],workflow:{kind:"WORKFLOW",resourceId:workflow.definition.workflowDefinitionId,revisionId:workflowRevision.revisionId,digest:workflowRevision.digest},runtimeProfile:{kind:"RUNTIME_PROFILE",resourceId:runtime.profile.runtimeProfileId,revisionId:runtimeRevision.revisionId,digest:runtimeRevision.digest},model:{kind:"MODEL",resourceId:"model:unverified-evidence-reference"}}}});const agentDraft=active(agent,"definition");
  const problem=await post(request,"/api/internal/v0.2.1/problems",{name:"S5 supplier quality gap",description:"A supplier quality decline requires supplier quality analysis and a governed corrective plan.",includeNewKnowledge:true});
  await page.goto(`/api/internal/v0.2.1/problems/${encodeURIComponent(problem.problemId)}`);await expect(page.locator("body")).toContainText("supplier-quality-analysis");await expect(page.locator("body")).toContainText('"state":"GAP"');await page.goto("/problems");await expect(page.getByRole("heading",{name:"从业务问题到可审核计划"})).toBeVisible();
  await page.goto("/attention");const attention=page.locator(".attention-list article").filter({hasText:agent.definition.definitionId});await expect(attention).toContainText(agentDraft.revisionId);await expect(attention).toContainText(agentDraft.digest);await attention.getByRole("link",{name:"Open owning Workbench"}).click();await expect(page.getByRole("heading",{name:"Agent Workbench"})).toBeVisible();await page.getByRole("button",{name:/S5 Unified Supplier Quality Agent/}).last().click();await expect(page.locator(".agent-detail")).toContainText(agent.definition.definitionId);
  await page.getByRole("button",{name:"Validate draft"}).click();await page.getByRole("button",{name:"Human review exact digest"}).click();await page.getByRole("button",{name:"Publish immutable revision"}).click();await expect(page.locator(".agent-detail").getByText("PUBLISHED",{exact:true}).first()).toBeVisible();agent=await(await request.get(`${backend}/api/internal/v0.2.2/agent-definitions/${encodeURIComponent(agent.definition.definitionId)}`,{headers})).json();const agentRevision=active(agent,"definition");
  await expect(page.locator(".agent-detail > header")).toContainText(agent.definition.definitionId);const technical=page.getByLabel("Agent Definition Technical View");await expect(technical).toContainText(agent.definition.definitionId);await expect(technical).toContainText(agentRevision.revisionId);await expect(technical).toContainText(agentRevision.digest);await expect(technical).toContainText("does not authorize execution");
  await page.goto("/problems");await expect(page.getByRole("button",{name:/Rematch published Agent Definitions|重新匹配已发布 Agent Definition/})).toBeVisible();await post(request,`/api/internal/v0.2.1/problems/${encodeURIComponent(problem.problemId)}/rematches`,{});await page.goto(`/api/internal/v0.2.1/problems/${encodeURIComponent(problem.problemId)}`);await expect(page.locator("body")).toContainText('"state":"MATCHED"');await expect(page.locator("body")).toContainText(agent.definition.definitionId);await expect(page.locator("body")).toContainText(agentRevision.revisionId);await expect(page.locator("body")).toContainText(agentRevision.digest);await expect(page.locator("body")).toContainText("NOT_GRANTED");
  for(const[kind,identity,status]of[["AGENT",agent.definition.definitionId,"PUBLISHED"],["SKILL",skill.resource.resourceId,"PUBLISHED"],["MCP",mcpResource.resource.resourceId,"PUBLISHED"],["KNOWLEDGE",knowledge.knowledge.knowledgeId,"AVAILABLE"],["WORKFLOW",workflow.definition.workflowDefinitionId,"PUBLISHED"],["RUNTIME_PROFILE",runtime.profile.runtimeProfileId,"PUBLISHED"]]as const){await page.goto(`/catalog?kind=${kind}&status=${status}&query=${encodeURIComponent(identity)}`);await expect(page.getByLabel("资源类型")).toHaveValue(kind);await expect(page.getByLabel("生命周期状态")).toHaveValue(status);await expect(page.getByLabel("搜索")).toHaveValue(identity);await expect(page.getByLabel("资源目录结果")).toContainText(identity);await expect(page.getByLabel("资源目录结果").locator("a")).toHaveCount(1)}await expect(page.locator(".resource-detail")).toContainText("PREVIEW");await expect(page.locator(".resource-detail")).toContainText("NOT CERTIFIED");await expect(page.locator(".resource-detail")).toContainText("NON PRODUCTION READY");
  await page.goto(`/catalog?kind=MCP&status=PUBLISHED&query=${encodeURIComponent(mcpResource.resource.resourceId)}`);await expect(page.locator(".resource-detail")).toContainText("MCP 已完成治理定义与发布；当前 Public Preview 未配置可调用的正式 MCP 端点，未执行工具调用。");await page.goto(`/catalog?kind=SKILL&status=PUBLISHED&query=${encodeURIComponent(skill.resource.resourceId)}`);await expect(page.locator(".resource-detail")).toContainText("Skill 已完成治理定义与发布；当前 Public Preview 未证明实际执行。");
  await page.goto("/relationships");const relationship=page.locator(".relationship-list article").filter({hasText:skill.resource.resourceId}).filter({hasText:agent.definition.definitionId}).first();await expect(relationship).toContainText(skillRevision.revisionId);await expect(relationship).toContainText(skillRevision.digest);await relationship.getByRole("link",{name:"Open related resource"}).click();await expect(page.getByRole("heading",{name:"Skill Workbench"})).toBeVisible();await page.getByRole("button",{name:/S5 Unified Supplier Quality Skill/}).last().click();await page.getByRole("tab",{name:"Technical View"}).click();await expect(page.locator(".agent-detail")).toContainText(skillRevision.revisionId);await expect(page.locator(".agent-detail")).toContainText(skillRevision.digest);
  await page.goto("/digital-employees");const template=page.locator(".template-grid article").filter({hasText:agent.definition.definitionId});await expect(template).toContainText("数字员工模板");await expect(template).toContainText("定义投影");await expect(template).toContainText("可匹配");await expect(template).toContainText("未实例化");for(const[kind,identity,revision,digest]of[["SKILL",skill.resource.resourceId,skillRevision.revisionId,skillRevision.digest],["KNOWLEDGE",knowledge.knowledge.knowledgeId,knowledgeRevision.revisionId,knowledgeRevision.digest],["WORKFLOW",workflow.definition.workflowDefinitionId,workflowRevision.revisionId,workflowRevision.digest],["RUNTIME_PROFILE",runtime.profile.runtimeProfileId,runtimeRevision.revisionId,runtimeRevision.digest]]as const){const binding=template.getByRole("listitem").filter({hasText:identity});await expect(binding).toContainText(kind.replace("_"," "));await expect(binding).toContainText(revision);await expect(binding).toContainText(digest)}await expect(template).toContainText("TEMPLATE ONLY");await expect(template).toContainText("NO EXECUTION AUTHORITY");await expect(template).toContainText("UNVERIFIED MODEL REFERENCE");
  await post(request,"/api/internal/v0.2.2/resources/skill",{name:"S5 Restart Attention Draft",content:{description:"Review-required durable marker",capabilities:["review-marker"]}});await restartBackend(request);for(const[route,heading]of[["/dashboard","从数字员工模板理解企业智能体"],["/catalog","能力与资源"],["/relationships","Resource Relationships"],["/attention","Attention"],["/digital-employees","数字员工"]]as const){await page.goto(route);await expect(page.getByRole("heading",{name:heading,exact:true})).toBeVisible()}await expect(page.locator(".template-grid article").filter({hasText:agent.definition.definitionId})).toContainText("NO EXECUTION AUTHORITY");await page.goto(`/catalog?query=${encodeURIComponent(agent.definition.definitionId)}&kind=AGENT&status=PUBLISHED`);await expect(page.locator(".resource-detail")).toContainText(agentRevision.revisionId);await expect(page.locator(".resource-detail")).toContainText(agentRevision.digest);await expect(page.locator(".resource-detail")).toContainText("PREVIEW");expect(problem.problemId).toMatch(/^problem:/);
});

test("keeps the Chinese shell, disclosure, routes, and mobile controls truthful",async({page})=>{await page.route("**/api/internal/v0.2.2/product/catalog**",route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({detail:{reasonCode:"PRODUCT_ASSEMBLY_ACCESS_DENIED"}})}));await page.setViewportSize({width:390,height:844});await page.goto("/catalog");for(const label of ["首页","数字员工","能力与资源","业务任务","计划与审批","执行与结果","证据","技术详情"])await expect(page.getByRole("link",{name:label,exact:true})).toBeVisible();await expect(page.locator(".preview-disclosure")).toContainText("公开预览 / 非生产 / 未认证 / 不代表正式发布");await expect(page.getByRole("alert").getByText("PRODUCT_ASSEMBLY_ACCESS_DENIED")).toBeHidden();await expect(page.locator("main")).not.toContainText("S5 Unified");await expect(page.locator("html")).toHaveJSProperty("scrollWidth",390);for(const link of await page.locator(".demo-primary-nav a").all())expect((await link.boundingBox())?.height).toBeGreaterThanOrEqual(44);await page.keyboard.press("Tab");await expect(page.locator(":focus")).toBeVisible();await page.goto("/evidence");await expect(page.getByRole("heading",{name:"缺少证据上下文"})).toBeVisible();await expect(page.getByRole("link",{name:"返回能力与资源"})).toBeVisible();});
