import {expect,test,type BrowserContext,type Locator,type Page} from "@playwright/test";

test.skip(process.env.S5_V023_IMPL_299_LIVE!=="1","requires the exclusive IMPL-299 PostgreSQL/Public HTTP harness");

async function login(context:BrowserContext,credential:string){
  const page=await context.newPage();await page.goto("/api/workbench/v1/login");await page.locator('input[name="bootstrapCredential"]').fill(credential);await Promise.all([page.waitForURL(url=>url.pathname==="/work"),page.getByRole("button",{name:"登录并返回工作台"}).click()]);return page;
}

async function approve(page:Page,requestId:string){
  await page.goto(`/authorization-admin?request=${encodeURIComponent(requestId)}`);await page.getByRole("button",{name:"检查授权申请"}).click();await expect(page.getByText("等待处理",{exact:true})).toBeVisible();await page.getByRole("button",{name:"批准精确权限"}).click();await expect(page.getByText("已批准",{exact:true})).toBeVisible();
}

async function requestIdFrom(container:Locator){
  return (await container.locator("dt",{hasText:"申请编号"}).locator("xpath=following-sibling::dd[1]").textContent())!.trim();
}

test("real browser closes Problem and W3 exact authorization with an independent administrator",async({browser},testInfo)=>{
  test.setTimeout(120_000);const applicantContext=await browser.newContext({viewport:{width:1440,height:900}}),adminContext=await browser.newContext({viewport:{width:1440,height:900}});const applicant=await login(applicantContext,process.env.IMPL299_ALICE_CREDENTIAL!),admin=await login(adminContext,process.env.IMPL299_BOB_CREDENTIAL!);
  await applicant.getByLabel("你希望解决什么问题？").fill("恢复关键零部件交付，并由业务负责人确认连续三批按承诺日期完成。");await applicant.getByLabel("你希望解决什么问题？").press("Enter");const draft=applicant.getByLabel("问题草稿卡片");const createResponsePromise=applicant.waitForResponse(response=>response.request().method()==="POST"&&new URL(response.url()).pathname==="/api/workbench/v1/problems");await draft.getByRole("button",{name:"确认创建",exact:true}).click();const createResponse=await createResponsePromise;expect(createResponse.status(),await createResponse.text()).toBe(201);await applicant.getByRole("button",{name:"申请查看权限",exact:true}).click();let requestId=await requestIdFrom(applicant.locator("#authorization-message"));await approve(admin,requestId);await applicant.getByRole("button",{name:"刷新授权状态"}).click();await expect(applicant.getByText("尚未读取成功标准",{exact:true})).toBeVisible();
  await applicant.getByRole("button",{name:"申请定义与读取权限"}).click();requestId=await requestIdFrom(applicant.locator(".px-boundary-card"));await approve(admin,requestId);await applicant.getByRole("button",{name:"刷新权限状态并继续"}).click();await expect(applicant.getByRole("button",{name:"定义成功标准",exact:true})).toBeVisible();
  await applicant.getByRole("button",{name:"定义成功标准",exact:true}).click();const composer=applicant.getByLabel("怎样才算解决？");await composer.fill("业务负责人确认未来三批均能按承诺日期交付。");await composer.press("Enter");const criterion=applicant.getByLabel("成功标准待确认卡片");await criterion.getByLabel("人工验收标准").check();await criterion.getByRole("button",{name:"确认并保存"}).click();await expect(criterion).toContainText("关联未完成");await criterion.getByRole("button",{name:"申请所需精确权限"}).click();requestId=await requestIdFrom(criterion.getByLabel("成功标准权限申请"));await approve(admin,requestId);await criterion.getByRole("button",{name:"刷新权限状态并继续"}).click();await expect(criterion).toContainText("已保存并完成正式关联");await expect(applicant.getByLabel("已保存成功标准")).toContainText("业务负责人确认未来三批均能按承诺日期交付。");await applicant.screenshot({path:testInfo.outputPath("w3-real-authorization-1440x900.png")});
  await applicant.reload();const history=applicant.getByLabel("已保存成功标准");await expect(history).toContainText("业务负责人确认未来三批均能按承诺日期交付。");await history.getByRole("button",{name:"修订此标准"}).click();await applicant.getByLabel("修改成功标准原文").fill("业务负责人确认未来五批均能按承诺日期交付。");await applicant.getByRole("button",{name:"采用标准原文"}).click();const revision=applicant.getByLabel("成功标准待确认卡片");await revision.getByRole("button",{name:"确认并保存"}).click();await expect(revision).toContainText("标准未保存");await revision.getByRole("button",{name:"申请所需精确权限"}).click();requestId=await requestIdFrom(revision.getByLabel("成功标准权限申请"));await admin.goto(`/authorization-admin?request=${encodeURIComponent(requestId)}`);await admin.getByRole("button",{name:"检查授权申请"}).click();await admin.getByRole("button",{name:"拒绝申请"}).click();await expect(admin.getByText("已拒绝",{exact:true})).toBeVisible();await revision.getByRole("button",{name:"刷新权限状态并继续"}).click();await expect(revision.getByLabel("成功标准权限申请")).toContainText("已拒绝");await revision.getByRole("button",{name:"重新提交新申请"}).click();requestId=await requestIdFrom(revision.getByLabel("成功标准权限申请"));await approve(admin,requestId);await revision.getByRole("button",{name:"刷新权限状态并继续"}).click();await expect(revision).toContainText("关联未完成");await revision.getByRole("button",{name:"申请所需精确权限"}).click();requestId=await requestIdFrom(revision.getByLabel("成功标准权限申请"));await approve(admin,requestId);await revision.getByRole("button",{name:"刷新权限状态并继续"}).click();await expect(revision).toContainText("已保存并完成正式关联");await applicant.reload();await expect(applicant.getByLabel("已保存成功标准")).toContainText("业务负责人确认未来五批均能按承诺日期交付。");await applicant.screenshot({path:testInfo.outputPath("w3-real-revised-1440x900.png")});await applicantContext.close();await adminContext.close();
});
