/* eslint-disable @typescript-eslint/no-explicit-any */
import {createServer,type Server} from "node:http";
import {expect,test,type APIRequestContext,type Page} from "@playwright/test";
import {backendUrl,restartOwnedBackend,startOwnedBackend,stopOwnedBackend} from "../harness/ownedBackend";
import {parseUrlContext,serializeUrlContext,type CanonicalUrlContext} from "../../src/shared/urlContext";
const backend=backendUrl(),headers={"X-Tenant-ID":`s5-impl-054-final-${process.pid}`,"X-Security-Domain":"wave-3b-final","X-Principal-ID":"human:s5-impl-054-reviewer"};type J=Record<string,any>;let mcp:Server;
async function post(request:APIRequestContext,route:string,data:unknown){const response=await request.post(`${backend}${route}`,{headers,data});expect(response.ok(),`${route}: ${await response.text()}`).toBe(true);return response.json() as Promise<J>}
async function get(request:APIRequestContext,route:string){const response=await request.get(`${backend}${route}`,{headers});expect(response.ok(),`${route}: ${await response.text()}`).toBe(true);return response.json() as Promise<J>}
async function publish(request:APIRequestContext,root:string,value:J,key:string,idKey:string){let record=value[key];const id=record[idKey];value=await post(request,`${root}/${encodeURIComponent(id)}/validation`,{expectedVersion:record.aggregateVersion});record=value[key];const draft=record.revisions.find((x:J)=>x.revisionId===record.currentDraftRevisionId);value=await post(request,`${root}/${encodeURIComponent(id)}/reviews`,{expectedVersion:record.aggregateVersion,digest:draft.digest,decision:"APPROVE",reason:"S5-IMPL-054 exact browser evidence"});record=value[key];const review=record.reviews?.at(-1);return post(request,`${root}/${encodeURIComponent(id)}/publications`,{expectedVersion:record.aggregateVersion,digest:draft.digest,...(review?.reviewId?{reviewId:review.reviewId}:{})})}
function active(value:J,key:string){const record=value[key];return record.revisions.find((x:J)=>x.revisionId===record.publishedRevisionId)}
async function restartBackend(request:APIRequestContext){await restartOwnedBackend();await expect.poll(async()=>{try{return(await request.get(`${backend}/healthz`,{timeout:500})).status()}catch{return 0}},{timeout:20_000}).toBe(200)}
function route(view:"product"|"technical"|"evidence",context:CanonicalUrlContext){return`/${view==="product"?"product-view":view==="technical"?"technical-view":"evidence"}?${serializeUrlContext({...context,view})}`}
async function exact(page:Page,c:CanonicalUrlContext){for(const value of[c.resourceId,c.revisionId,c.digest])await expect(page.locator("body")).toContainText(value!)}

test.beforeAll(async()=>{mcp=createServer((req,res)=>{let raw="";req.on("data",c=>raw+=c);req.on("end",()=>{const msg=JSON.parse(raw);if(msg.method==="notifications/initialized"){res.writeHead(202);res.end();return}const result=msg.method==="initialize"?{protocolVersion:"2025-06-18",capabilities:{},serverInfo:{name:"wave-3b",version:"1"}}:msg.method==="tools/list"?{tools:[{name:"quality.lookup",description:"Bounded lookup",inputSchema:{type:"object"}}]}:msg.method==="resources/list"?{resources:[]}:msg.method==="prompts/list"?{prompts:[]}:{};res.writeHead(200,{"Content-Type":"application/json","Mcp-Session-Id":"wave-3b"});res.end(JSON.stringify({jsonrpc:"2.0",id:msg.id,result}))})});await new Promise<void>((resolve,reject)=>{mcp.once("error",reject);mcp.listen(8776,"127.0.0.1",resolve)})});
test.afterAll(async()=>new Promise<void>((resolve,reject)=>mcp.close(e=>e?reject(e):resolve())));

test("canonical URL context is deterministic and round-trip stable",()=>{const context:CanonicalUrlContext={kind:"AGENT",resourceId:"agent:quality",revisionId:"revision:1",digest:"sha256:exact",view:"evidence",evidenceId:"review:1",relationshipId:"relationship:1",claimKey:"resource.lifecycle",factKey:"resource.lifecycle",businessStepId:"govern-resource",query:"quality",kindFilter:"AGENT",lifecycleFilter:"PUBLISHED",timeFrom:"2026-08-01T00:00:00Z",timeTo:"2026-09-01T00:00:00Z",returnTo:"/catalog?query=quality&kind=AGENT&status=PUBLISHED"};const serialized=serializeUrlContext(context);expect(parseUrlContext(serialized)).toEqual({state:"VALID",context});expect(serializeUrlContext((parseUrlContext(serialized)as{state:"VALID";context:CanonicalUrlContext}).context)).toBe(serialized)});
test("invalid URL context fails closed",()=>{for(const search of["kind=AGENT&resourceId=agent%3Aquality","view=latest","view=product&view=technical","returnTo=https%3A%2F%2Fexample.com","returnTo=%2Fcatalog%3Ftoken%3Dsecret","namespace=tenant-a"])expect(parseUrlContext(search)).toEqual({state:"INVALID",reason:"INVALID_URL_CONTEXT"})});

test("proves all twelve Wave 3B real-service browser journeys",async({page,request})=>{test.setTimeout(240_000);await page.setExtraHTTPHeaders(headers);await restartBackend(request);
 let skill=await post(request,"/api/internal/v0.2.2/resources/skill",{name:"Wave 3B Skill",content:{description:"Analyze quality",capabilities:["supplier-quality-analysis"],instructions:"Use governed evidence."}});skill=await publish(request,"/api/internal/v0.2.2/resources/skill",skill,"resource","resourceId");
 let tool=await post(request,"/api/internal/v0.2.2/resources/mcp",{name:"Wave 3B MCP",content:{description:"Bounded lookup",capabilities:["supplier-quality-analysis"],endpoint:"http://127.0.0.1:8776",timeoutSeconds:2,sideEffect:"NONE",idempotency:"IDEMPOTENT"}});tool=await publish(request,"/api/internal/v0.2.2/resources/mcp",tool,"resource","resourceId");tool=await post(request,`/api/internal/v0.2.2/resources/mcp/${tool.resource.resourceId}/discovery`,{expectedVersion:tool.resource.aggregateVersion,timeoutSeconds:2});const snapshot=tool.resource.discoverySnapshots.at(-1);tool=await post(request,`/api/internal/v0.2.2/resources/mcp/${tool.resource.resourceId}/tool-selections`,{expectedVersion:tool.resource.aggregateVersion,snapshotId:snapshot.snapshotId,toolNames:["quality.lookup"],reason:"Exact selection"});
 let knowledge=await post(request,"/api/internal/v0.2.2/knowledge",{name:"Wave 3B Knowledge",source:{sourceId:"source:wave-3b",documentId:"document:quality",kind:"TEXT",provenance:"human:s5-impl-054-reviewer",content:"Containment starts immediately. Root cause analysis cites governed evidence."}});knowledge=await publish(request,"/api/internal/v0.2.2/knowledge",knowledge,"knowledge","knowledgeId");knowledge=await post(request,`/api/internal/v0.2.2/knowledge/${knowledge.knowledge.knowledgeId}/ingestion`,{expectedVersion:knowledge.knowledge.aggregateVersion});
 let runtime=await post(request,"/api/internal/v0.2.2/runtime-profiles",{name:"Wave 3B Runtime",content:{provider:"OPENCLAW",resources:{cpuRequest:"100m",cpuLimit:"500m",memoryRequest:"128Mi",memoryLimit:"512Mi"},isolation:"NAMESPACE",stateMode:"STATELESS",sessionAffinity:"NONE",secretReferences:[],openClawPackageRef:"openclaw://bounded/wave-3b@1"}});runtime=await publish(request,"/api/internal/v0.2.2/runtime-profiles",runtime,"profile","runtimeProfileId");
 const sr=active(skill,"resource"),tr=active(tool,"resource"),kr=active(knowledge,"knowledge"),rr=active(runtime,"profile"),rrBindingDigest=rr.digest.replace("sha256:","");
 let workflow=await post(request,"/api/internal/v0.2.2/workflow-definitions",{name:"Wave 3B Workflow",content:{description:"Quality response",inputs:["quality-records"],outputs:["analysis"],runtimeProfile:{kind:"RUNTIME_PROFILE",resourceId:runtime.profile.runtimeProfileId,revisionId:rr.revisionId},tasks:[{taskId:"analyze",name:"Analyze quality",dependsOn:[],inputs:["quality-records"],outputs:["analysis"],capabilityRequirements:["supplier-quality-analysis"],references:[],retryLimit:1,timeoutSeconds:300,failurePolicy:"FAIL_WORKFLOW"}]}});workflow=await publish(request,"/api/internal/v0.2.2/workflow-definitions",workflow,"definition","workflowDefinitionId");const wr=active(workflow,"definition");
 const wrBindingDigest=wr.digest.replace("sha256:","");let agent=await post(request,"/api/internal/v0.2.2/agent-definitions",{name:"Wave 3B Agent",content:{title:"Quality Analyst",duties:["Analyze quality"],data:["quality records"],knowledge:["governed procedure"],skills:["root cause analysis"],capabilities:["supplier-quality-analysis"],runtimes:["bounded declaration"],businessPurpose:"Analyze quality",bindings:{skills:[{resourceId:skill.resource.resourceId,revisionId:sr.revisionId,digest:sr.digest}],mcpTools:[{resourceId:tool.resource.resourceId,revisionId:tr.revisionId,digest:tr.digest,toolName:"quality.lookup",snapshotId:snapshot.snapshotId}],knowledge:[{resourceId:knowledge.knowledge.knowledgeId,revisionId:kr.revisionId,digest:kr.digest,snapshotId:knowledge.knowledge.activeIndexSnapshotId}],workflow:{kind:"WORKFLOW",resourceId:workflow.definition.workflowDefinitionId,revisionId:wr.revisionId,digest:wrBindingDigest},runtimeProfile:{kind:"RUNTIME_PROFILE",resourceId:runtime.profile.runtimeProfileId,revisionId:rr.revisionId,digest:rrBindingDigest},model:{kind:"MODEL",resourceId:"model:unverified-wave-3b"}}}});agent=await publish(request,"/api/internal/v0.2.2/agent-definitions",agent,"definition","definitionId");const ar=active(agent,"definition");
 const returnTo=`/catalog?query=${encodeURIComponent(agent.definition.definitionId)}&kind=AGENT&status=PUBLISHED`,context:CanonicalUrlContext={kind:"AGENT",resourceId:agent.definition.definitionId,revisionId:ar.revisionId,digest:ar.digest,query:agent.definition.definitionId,kindFilter:"AGENT",lifecycleFilter:"PUBLISHED",returnTo};const trace=await get(request,`/api/internal/v0.2.2/product/traceability/AGENT/${encodeURIComponent(agent.definition.definitionId)}?${new URLSearchParams({revisionId:ar.revisionId,digest:ar.digest})}`),claim=trace.claims.find((x:J)=>x.claimKey==="resource.lifecycle"),evidence=trace.evidence.find((x:J)=>x.evidenceType==="HUMAN_REVIEW");expect(claim).toBeTruthy();expect(evidence).toBeTruthy();
 await test.step("1 context-preserving catalog round trip",async()=>{await page.goto(returnTo);await page.getByRole("link",{name:"Open exact Product View"}).click();await exact(page,context);for(const name of["Technical","Evidence"]){await page.getByRole("link",{name,exact:true}).click();await exact(page,context)}await page.getByRole("button",{name:"Close Evidence Inspector"}).click();await expect(page.getByLabel("Search")).toHaveValue(agent.definition.definitionId)});
 await test.step("2 claim Evidence fact business-step chain",async()=>{await page.goto(route("product",{...context,claimKey:claim.claimKey,evidenceId:evidence.evidenceId,factKey:"resource.lifecycle"}));await page.locator('[id="claim-resource.lifecycle"]').getByRole("link",{name:new RegExp(`Evidence ${evidence.evidenceId}`)}).click();await page.getByRole("link",{name:"Fact: resource.lifecycle"}).click();await page.locator('[id="fact-resource.lifecycle"]').getByRole("link",{name:/Affected business step/}).click();await expect(page.locator(`[id="business-step-${claim.affectedBusinessStepIds[0]}"]`)).toBeVisible()});
 await test.step("3 fact reverses to exact claim",async()=>{await page.goto(route("technical",{...context,factKey:"resource.lifecycle",claimKey:claim.claimKey}));await page.locator('[id="fact-resource.lifecycle"]').getByRole("link",{name:`Affected claim ${claim.claimKey}`}).click();await expect(page.locator('[id="claim-resource.lifecycle"]')).toBeVisible();await exact(page,context)});
 await test.step("4 Agent retains five exact bindings",async()=>{await page.goto(route("technical",{...context,factKey:"resource.relationships"}));const fact=page.locator('[id="fact-resource.relationships"]');for(const value of[skill.resource.resourceId,tool.resource.resourceId,knowledge.knowledge.knowledgeId,workflow.definition.workflowDefinitionId,runtime.profile.runtimeProfileId,sr.revisionId,tr.revisionId,kr.revisionId,wr.revisionId,rr.revisionId,sr.digest,tr.digest,kr.digest,wrBindingDigest,rrBindingDigest])await expect(fact).toContainText(value)});
 await test.step("5 Workflow task edge and lifecycle Evidence survive",async()=>{const c:CanonicalUrlContext={kind:"WORKFLOW",resourceId:workflow.definition.workflowDefinitionId,revisionId:wr.revisionId,digest:wr.digest,businessStepId:"analyze",relationshipId:"edge:runtime",evidenceId:workflow.definition.reviews.at(-1).reviewId};await page.goto(route("product",c));await page.getByRole("link",{name:"Technical",exact:true}).click();await page.getByRole("link",{name:"Evidence",exact:true}).click();const url=new URL(page.url());expect(url.searchParams.get("businessStepId")).toBe("analyze");expect(url.searchParams.get("relationshipId")).toBe("edge:runtime");await expect(page.getByRole("dialog")).toContainText(c.evidenceId!)});
 await test.step("6 Runtime remains declaration-only",async()=>{const c:CanonicalUrlContext={kind:"RUNTIME_PROFILE",resourceId:runtime.profile.runtimeProfileId,revisionId:rr.revisionId,digest:rr.digest};await page.goto(route("product",c));await expect(page.locator("main")).toContainText("DECLARATION_ONLY");await expect(page.locator("main")).toContainText("NO_EXECUTION_AUTHORITY");await expect(page.locator("main")).toContainText("UNSUPPORTED");await page.getByRole("link",{name:"Technical",exact:true}).click();await expect(page.locator("main")).not.toContainText("VERIFIED MODEL")});
 await test.step("7 Knowledge routine precedes advanced",async()=>{await page.goto("/knowledge");await page.getByRole("button",{name:/Wave 3B Knowledge/}).click();const hierarchy=page.getByRole("navigation",{name:"Knowledge information hierarchy"});await expect(hierarchy.locator("li").first()).toContainText("Routine: Search, Retrieval and Citations");await expect(hierarchy.locator("li").last()).toContainText("Advanced high-impact: Rebuild, Purge and Recovery")});
 await test.step("8 stale conflict refreshes and explicitly reapplies",async()=>{await page.goto("/workflow-definitions");await page.getByRole("button",{name:/Wave 3B Workflow/}).click();await page.getByLabel("Published Runtime Profile ID").fill(runtime.profile.runtimeProfileId);await page.getByLabel("Published Runtime revision ID").fill(rr.revisionId);await page.getByRole("button",{name:"Open Workflow Builder"}).click();const authoritative=await get(request,`/api/internal/v0.2.2/workflow-definitions/${encodeURIComponent(workflow.definition.workflowDefinitionId)}`);await post(request,`/api/internal/v0.2.2/workflow-definitions/${encodeURIComponent(workflow.definition.workflowDefinitionId)}/successors`,{expectedVersion:authoritative.definition.aggregateVersion});await page.getByRole("button",{name:"Create Workflow successor"}).click();const recovery=page.getByRole("alert",{name:"Guided conflict recovery"});await expect(recovery).toContainText("Authoritative aggregate version");await recovery.getByRole("button",{name:"Explicitly reapply safe draft input"}).click();await expect(page.getByRole("button",{name:"Save governed Workflow draft"})).toBeVisible()});
 await test.step("9 denied and absent are nondisclosing",async()=>{await page.setExtraHTTPHeaders({...headers,"X-Product-Read-Authorized":"false"});await page.goto(route("product",context));await expect(page.locator("main")).toContainText("Resource context unavailable");for(const value of[context.resourceId,context.revisionId,context.digest,evidence.evidenceId])await expect(page.locator("main")).not.toContainText(value!);await page.setExtraHTTPHeaders(headers);await page.goto(route("product",{...context,resourceId:"definition:absent",revisionId:"revision:absent",digest:"sha256:absent"}));await expect(page.locator("main")).toContainText("Resource context unavailable");await expect(page.locator("main")).not.toContainText("definition:absent")});
 await test.step("10 unavailable backend shows no false success",async()=>{await stopOwnedBackend();await expect.poll(async()=>{try{return(await request.get(`${backend}/healthz`,{timeout:500})).status()}catch{return 0}}).toBe(0);await page.goto(route("product",context));await expect(page.locator("main")).toContainText("Evidence service unavailable");await expect(page.locator("main")).not.toContainText("SUPPORTED");await startOwnedBackend()});
 await test.step("11 refresh and restart recover exact URL",async()=>{const target=route("technical",{...context,factKey:"resource.lifecycle"});await page.goto(target);await exact(page,context);await restartBackend(request);await page.reload();expect(page.url()).toContain(encodeURIComponent(ar.revisionId));await exact(page,context)});
 await test.step("12 mobile keyboard focus returns accessibly",async()=>{await page.setViewportSize({width:390,height:844});await page.goto(route("product",{...context,claimKey:claim.claimKey}));const link=page.locator('[id="claim-resource.lifecycle"]').getByRole("link",{name:new RegExp(`Evidence ${evidence.evidenceId}`)});await link.focus();await page.keyboard.press("Enter");const close=page.getByRole("button",{name:"Close Evidence Inspector"});await expect(close).toBeFocused();await expect(close).toBeInViewport();await page.keyboard.press("Enter");await expect(page.locator('[id="claim-resource.lifecycle"]')).toBeFocused()});
});
