import type { JourneyIdentity, JourneyTaskProjection } from "../shared/livePlanningJourneyTypes";
import { useI18n } from "../i18n/useI18n";

type ObjectType = "AGENT_DEFINITION" | "BUSINESS_CAPABILITY" | "SKILL" | "MCP_CAPABILITY" | "KNOWLEDGE" | "RUNTIME" | "EXECUTION_RUNTIME";
interface Props { tasks: JourneyTaskProjection[]; identity: JourneyIdentity; onTechnical: (type: ObjectType, id: string, taskId?: string) => void; }
function unique(values: string[]) { return [...new Set(values)]; }
function status(value: string) { return ({ READY: "已准备", ROLE_GAP: "角色缺口", DENIED: "无权使用", UNAVAILABLE: "不可用", SUCCEEDED: "已完成", WAITING_DEPENDENCY: "等待前置任务" } as Record<string,string>)[value] ?? value; }
function statusFamily(value: string) { if (["SUCCEEDED","READY","PUBLISHED","MATCHABLE","APPROVED","PLACED"].includes(value)) return "success"; if (["RUNNING","AUTHORIZED_HANDOFF"].includes(value)) return "running"; if (["DENIED","FAILED"].includes(value)) return "failure"; if (["ROLE_GAP","STALE","EXPIRED"].includes(value)) return "warning"; if (["UNAVAILABLE","NOT_BOUND","NOT_ISSUED"].includes(value)) return "unavailable"; return "waiting"; }
function StatusBadge({ value }: { value: string }) { const label=({PUBLISHED:"已发布",MATCHABLE:"已允许匹配",APPROVED:"已授权",PLACED:"已就绪",PENDING:"等待你的确认",NOT_REQUESTED:"等待执行"} as Record<string,string>)[value]??status(value); const icon=statusFamily(value)==="success"?"✓":statusFamily(value)==="running"?"↻":statusFamily(value)==="failure"?"×":statusFamily(value)==="warning"?"△":statusFamily(value)==="unavailable"?"—":"○"; return <span className={`status-badge status-${statusFamily(value)}`}><span aria-hidden="true">{icon}</span>{label}</span>; }
function capabilityName(value: string) { return ({ COLLECT: "质量证据汇总", ANALYZE: "质量异常与根因分析", REVIEW: "整改计划审查" } as Record<string,string>)[value] ?? "当前业务能力"; }

export function DigitalEmployeeDirectory({ tasks, identity, onTechnical }: Props) {
  const { locale } = useI18n();
  const count = (value: number) => new Intl.NumberFormat(locale).format(value);
  const agents = unique(tasks.map(task => task.definitionId).filter((value): value is string => Boolean(value))).map(id => ({ id, tasks: tasks.filter(task => task.definitionId === id) }));
  const skills = unique(tasks.flatMap(task => task.skills));
  const businessCapabilities = unique(tasks.flatMap(task => task.actions));
  const capabilities = unique(tasks.flatMap(task => task.mcpCapabilities));
  const knowledge = unique(tasks.flatMap(task => task.knowledgeRefs));
  const runtimes = unique(tasks.flatMap(task => task.runtimeRefs));
  const ready = agents.filter(agent => agent.tasks.every(task => task.readiness === "READY")).length;
  const gaps = tasks.filter(task => task.readiness === "ROLE_GAP").length;
  const denied = tasks.filter(task => ["DENIED", "UNAVAILABLE"].includes(task.readiness)).length;
  const usedBy = (field: "skills" | "mcpCapabilities" | "knowledgeRefs" | "runtimeRefs", id: string) => tasks.filter(task => task[field].includes(id));
  return <><section id="team" className="qto-team" aria-labelledby="team-title"><p className="eyebrow">👥 数字员工团队</p><h2 id="team-title">当前 Demo 可用的数字员工</h2><div className="qto-team-summary" aria-label="团队准备度摘要"><span><b>{count(unique(tasks.map(task => task.requiredRole)).length)}</b> 个所需业务角色</span><span><b>{count(agents.length)}</b> 个已匹配数字员工</span><span><b>{count(ready)}</b> 个已准备</span><span><b>{count(gaps)}</b> 个角色或能力缺口</span><span><b>{count(denied)}</b> 个无权或不可用</span><strong>{gaps + denied === 0 ? "✓ 计划可以进入批准审查" : "⚠ 计划尚不能进入批准"}</strong></div><div className="qto-team-grid">{agents.map(agent => { const first=agent.tasks[0]; const executionOccurred=agent.tasks.some(task=>task.state==="SUCCEEDED"||task.state==="FAILED"); return <article key={agent.id}><p className="eyebrow">🤖 数字员工定义</p><h3>{first.requiredRole}</h3><dl><dt>已匹配发布角色</dt><dd>{first.matchedRole}</dd><dt>一句话职责</dt><dd>{first.actions.includes("REVIEW")?"审查整改计划、Human 边界与执行条件。":"汇总并分析脱敏供应商质量事实，形成有依据的判断。"}</dd><dt>负责任务</dt><dd>{agent.tasks.map(task => task.title).join("、")}</dd><dt>业务能力</dt><dd>{unique(agent.tasks.flatMap(task=>task.actions)).map(id=>capabilityName(id)).join("、")}</dd><dt>Skills</dt><dd>{unique(agent.tasks.flatMap(task=>task.skills)).join("、")}</dd><dt>MCP/Tools</dt><dd>{unique(agent.tasks.flatMap(task=>task.mcpCapabilities)).join("、")}</dd><dt>Knowledge</dt><dd>{unique(agent.tasks.flatMap(task => task.knowledgeRefs)).join("、")}</dd><dt>Human边界</dt><dd>{agent.tasks.some(task=>task.approvalRequired)?"计划必须由 Human 精确批准":"不得越过方案中的 Human 审批任务"}</dd><dt>当前参与状态</dt><dd>{executionOccurred?"已发生受控执行":"尚未执行"}</dd><dt>运行环境</dt><dd>{unique(agent.tasks.flatMap(task=>task.runtimeRefs)).join("、")||"当前版本尚未采集该运行信息。"}</dd><dt>执行位置与准备度</dt><dd>{identity.placementDecisionId==="NOT_BOUND"?"尚未绑定执行位置":`已绑定执行位置 · ${status(first.readiness)}`}</dd><dt>当前工作或产出</dt><dd>{agent.tasks.map(task => `${task.title}: ${status(task.state)}`).join("；")}</dd><dt>Evidence与结果</dt><dd>{identity.evidenceIds.length>0?`已记录 ${count(identity.evidenceIds.length)} 项 Evidence` : "尚未产生 Evidence 或 Outcome"}</dd></dl><div className="employee-actions"><button className="secondary-button" onClick={()=>document.getElementById("team")?.scrollIntoView({behavior:"smooth"})}>查看业务职责</button><button className="secondary-button" onClick={()=>document.getElementById("directory")?.scrollIntoView({behavior:"smooth"})}>查看能力与资源</button><button onClick={()=>onTechnical("AGENT_DEFINITION",agent.id,first.taskId)}>查看技术实现</button><button onClick={()=>onTechnical("EXECUTION_RUNTIME",identity.platformExecutionIdentity??agent.id,first.taskId)}>查看本次参与记录</button></div></article>})}</div>{agents.length===0&&<p role="status">当前没有已发布且符合要求的数字员工承担这项工作。</p>}{denied>0&&<p role="alert">已找到相关能力，但本次任务无权使用。</p>}</section>
  <section id="directory" className="qto-directory" aria-labelledby="directory-title"><p className="eyebrow">🗂 有效资源映射</p><h2 id="directory-title">当前 Demo 可用的能力与资源</h2><p><small>Digital Employees and Capability Resources</small></p><p><strong>当前范围：受控供应商质量 Demo</strong></p><p>以下内容来自当前有效的注册、发布、授权或执行快照，不代表企业全部数字员工和能力资源。</p><p className="qto-disclosure">本次任务使用的资源 · Snapshot <span className="technical-value">{identity.sharedSnapshotId}</span></p><nav className="resource-tabs" aria-label="资源类别"><a href="#resource-agents">数字员工</a><a href="#resource-capabilities">业务能力</a><a href="#resource-skills">Skill</a><a href="#resource-mcp">MCP与工具</a><a href="#resource-knowledge">Knowledge</a><a href="#resource-runtime">Runtime</a></nav>
  <details id="resource-agents" open><summary>数字员工（Agent Definitions）</summary><div className="table-scroll"><table><thead><tr><th>数字员工</th><th>业务角色</th><th>发布状态</th><th>参与任务</th><th>能力数量</th><th>状态</th></tr></thead><tbody>{agents.map(agent=>{const first=agent.tasks[0];return <tr key={agent.id}><td><button onClick={()=>onTechnical("AGENT_DEFINITION",agent.id,first.taskId)}>{first.matchedRole}</button></td><td>{first.requiredRole}</td><td><StatusBadge value={first.publicationState}/></td><td>{agent.tasks.length}</td><td>{unique(agent.tasks.flatMap(task=>[...task.actions,...task.skills,...task.mcpCapabilities])).length}</td><td><StatusBadge value={first.readiness}/></td></tr>})}</tbody></table></div></details>
  <details id="resource-capabilities"><summary>业务能力（Business Capabilities）</summary><div className="table-scroll"><table><thead><tr><th>业务能力</th><th>所需任务</th><th>实现Skill</th><th>支持Agent</th><th>满足状态</th></tr></thead><tbody>{businessCapabilities.map(id=>{const use=tasks.filter(task=>task.actions.includes(id));return <tr key={id}><td><button onClick={()=>onTechnical("BUSINESS_CAPABILITY",id,use[0]?.taskId)}>{capabilityName(id)} <small>{id}</small></button></td><td>{use.map(task=>task.title).join("、")}</td><td>{unique(use.flatMap(task=>task.skills)).join("、")}</td><td>{unique(use.map(task=>task.matchedRole??"ROLE_GAP")).join("、")}</td><td>{use.every(task=>task.readiness==="READY")?"已满足":"未满足"}</td></tr>})}</tbody></table></div></details>
  <details id="resource-skills"><summary>技能（Skills）</summary><div className="table-scroll"><table><thead><tr><th>Skill</th><th>支持能力</th><th>使用Agent</th><th>调用工具</th><th>状态</th></tr></thead><tbody>{skills.map(id=>{const use=usedBy("skills",id);return <tr key={id}><td><button onClick={()=>onTechnical("SKILL",id,use[0]?.taskId)}>{id}</button></td><td>{unique(use.flatMap(task=>task.actions).map(capabilityName)).join("、")}</td><td>{unique(use.map(task=>task.matchedRole??"ROLE_GAP")).join("、")}</td><td>{unique(use.flatMap(task=>task.mcpCapabilities)).join("、")||"当前版本尚未采集该运行信息。"}</td><td>{use.every(task=>task.readiness==="READY")?"已允许":"不可用"}</td></tr>})}</tbody></table></div></details>
  <details id="resource-mcp"><summary>MCP与工具（MCP Servers, Capabilities and Operations）</summary><div className="table-scroll"><table><thead><tr><th>MCP Server</th><th>Capability</th><th>Operation/Tool</th><th>使用任务</th><th>授权状态</th></tr></thead><tbody>{capabilities.map(id=>{const use=usedBy("mcpCapabilities",id);return <tr key={id}><td>当前版本尚未采集该运行信息。</td><td><button onClick={()=>onTechnical("MCP_CAPABILITY",id,use[0]?.taskId)}>{id}</button></td><td>当前版本尚未采集该运行信息。</td><td>{use.map(task=>task.title).join("、")}</td><td>{use.every(task=>task.readiness==="READY")?"已允许":"不可用"}</td></tr>})}</tbody></table></div></details>
  <details id="resource-knowledge"><summary>知识库（Knowledge Packs）</summary><div className="table-scroll"><table><thead><tr><th>Knowledge Pack</th><th>知识主题</th><th>使用任务</th><th>Citation</th><th>授权状态</th></tr></thead><tbody>{knowledge.map(id=>{const use=usedBy("knowledgeRefs",id);return <tr key={id}><td><button onClick={()=>onTechnical("KNOWLEDGE",id,use[0]?.taskId)}>{id}</button></td><td>供应商质量判断依据</td><td>{use.map(task=>task.title).join("、")}</td><td>{identity.citationIds.length}</td><td>{use.every(task=>task.readiness==="READY")?"已允许":"不可用"}</td></tr>})}</tbody></table></div></details>
  <details id="resource-runtime"><summary>当前 Demo Runtime（Runtimes）</summary><div className="table-scroll"><table><thead><tr><th>Runtime</th><th>类型</th><th>承载执行</th><th>Placement</th><th>状态</th><th>限制</th></tr></thead><tbody>{runtimes.map(id=>{const use=usedBy("runtimeRefs",id);return <tr key={id}><td><button onClick={()=>onTechnical("RUNTIME",id,use[0]?.taskId)}>{id}</button></td><td>{id}</td><td>{identity.platformExecutionIdentity?"本次执行身份":"尚未创建执行身份"}</td><td>{identity.placementDecisionId}</td><td>{use.map(task=>status(task.state)).join("、")}</td><td>仅当前受控演示；无基础设施遥测</td></tr>})}</tbody></table></div></details></section></>;
}
