import type { ProductFixture } from "./types";

export const productFixture: ProductFixture = {
  classification: ["DETERMINISTIC", "SYNTHETIC", "NON_AUTHORITATIVE", "TECHNICAL_PREVIEW"],
  platformExecutionIdentity: "pei-synthetic-qi-1042-attempt-1",
  graphSnapshotId: "gps:v0.2-candidate:fixture-6-product",
  projectionContext: "PRODUCT",
  securityFiltered: true,
  questionKey: "product.question.default",
  questions: ["product.question.default", "product.question.alternate"],
  planRevision: "plan-revision.synthetic.qi-1042.r1",
  correctionRevision: "plan-revision.synthetic.qi-1042.r2",
  workflowId: "workflow.synthetic.complaint-analysis.v1",
  taskKeys: ["product.task.collect", "product.task.analyze", "product.task.recommend"],
  employees: [
    {
      id: "de.synthetic.customer-insight.v1",
      nameKey: "product.employee.mira.name",
      roleKey: "product.employee.mira.role",
      descriptionKey: "product.employee.mira.description",
      responsibilityKeys: ["product.employee.mira.responsibility"],
      allowedKeys: ["product.employee.mira.allowed"],
      prohibitedKeys: ["product.employee.common.prohibited"],
      capabilities: ["CAPABILITY_SYNTHETIC_COMPLAINT_READ", "CAPABILITY_SYNTHETIC_SUMMARIZE"],
      runtimeId: "NATIVE",
      previewInstanceCount: 1,
      previewState: "SYNTHETIC_PREVIEW_NOT_ORCHESTRATED",
    },
    {
      id: "de.synthetic.quality-analysis.v1",
      nameKey: "product.employee.aria.name",
      roleKey: "product.employee.aria.role",
      descriptionKey: "product.employee.aria.description",
      responsibilityKeys: ["product.employee.aria.responsibility"],
      allowedKeys: ["product.employee.aria.allowed"],
      prohibitedKeys: ["product.employee.common.prohibited"],
      capabilities: ["CAPABILITY_SYNTHETIC_QUALITY_ANALYSIS"],
      runtimeId: "NATIVE",
      previewInstanceCount: 1,
      previewState: "SYNTHETIC_PREVIEW_NOT_ORCHESTRATED",
    },
  ],
  nodes: [
    { id: "problem.synthetic.qi-1042", type: "BUSINESS_PROBLEM", labelKey: "product.graph.problem", phase: "COMPLETED" },
    { id: "plan-revision.synthetic.qi-1042.r1", type: "PLAN", labelKey: "product.graph.plan", phase: "COMPLETED" },
    { id: "workflow.synthetic.complaint-analysis.v1", type: "WORKFLOW", labelKey: "product.graph.workflow", phase: "RUNNING" },
    { id: "task.synthetic.collect", type: "TASK", labelKey: "product.task.collect", phase: "COMPLETED" },
    { id: "task.synthetic.analyze", type: "TASK", labelKey: "product.task.analyze", phase: "RUNNING" },
    { id: "task.synthetic.recommend", type: "TASK", labelKey: "product.task.recommend", phase: "UNKNOWN" },
    { id: "de.synthetic.customer-insight.v1", type: "DEFINITION", labelKey: "product.employee.mira.role", phase: "RUNNING" },
    { id: "instance.synthetic.customer-insight.001", type: "INSTANCE", labelKey: "product.graph.instance", phase: "RUNNING" },
    { id: "outcome.synthetic.qi-1042", type: "OUTCOME", labelKey: "product.graph.outcome", phase: "UNKNOWN" },
  ],
  edges: [
    { id: "aggregate.problem-plan", source: "problem.synthetic.qi-1042", target: "plan-revision.synthetic.qi-1042.r1", rawRelations: [{ id: "gpr.problem-plan", type: "DECOMPOSES_TO", direction: "SOURCE_TO_TARGET", cardinality: "ONE_TO_ONE", evidenceIds: ["evidence.synthetic.plan.001"] }] },
    { id: "aggregate.plan-workflow", source: "plan-revision.synthetic.qi-1042.r1", target: "workflow.synthetic.complaint-analysis.v1", rawRelations: [{ id: "gpr.plan-workflow", type: "CONTAINS", direction: "SOURCE_TO_TARGET", cardinality: "ONE_TO_ONE", evidenceIds: ["evidence.synthetic.workflow.001"] }] },
    { id: "aggregate.fixture-6", source: "task.synthetic.analyze", target: "task.synthetic.collect", rawRelations: [
      { id: "gpr.fixture6.depends", type: "DEPENDS_ON", direction: "SOURCE_TO_TARGET", cardinality: "MANY_TO_ONE", evidenceIds: ["evidence.synthetic.depends.006"] },
      { id: "gpr.fixture6.triggers", type: "TRIGGERS", direction: "SOURCE_TO_TARGET", cardinality: "ONE_TO_MANY", evidenceIds: ["evidence.synthetic.triggers.006"] },
      { id: "gpr.fixture6.flow", type: "DATA_FLOW", direction: "SOURCE_TO_TARGET", cardinality: "MANY_TO_MANY", evidenceIds: ["evidence.synthetic.flow.006"] },
    ] },
    { id: "aggregate.task-role", source: "task.synthetic.analyze", target: "de.synthetic.customer-insight.v1", rawRelations: [{ id: "gpr.task-role", type: "ASSIGNED_TO", direction: "SOURCE_TO_TARGET", cardinality: "MANY_TO_ONE", evidenceIds: ["evidence.synthetic.assignment.001"] }] },
    { id: "aggregate.role-instance", source: "de.synthetic.customer-insight.v1", target: "instance.synthetic.customer-insight.001", rawRelations: [{ id: "gpr.role-instance", type: "EXECUTED_BY", direction: "SOURCE_TO_TARGET", cardinality: "ONE_TO_MANY", evidenceIds: ["evidence.synthetic.instance.001"] }] },
    { id: "aggregate-workflow-outcome", source: "workflow.synthetic.complaint-analysis.v1", target: "outcome.synthetic.qi-1042", rawRelations: [{ id: "gpr.workflow-outcome", type: "PRODUCES", direction: "SOURCE_TO_TARGET", cardinality: "MANY_TO_ONE", evidenceIds: ["evidence.synthetic.outcome.001"] }] },
  ],
  groups: [],
  approval: { state: "PENDING_HUMAN_REVIEW", decidedAt: null, decisionFingerprint: "sha256:synthetic-plan-r1" },
  outcome: { status: "PASS", summaryKey: "product.outcome.summary", evidenceIds: ["evidence.synthetic.complaints.001", "evidence.synthetic.quality.002"] },
  citations: [{ evidenceId: "evidence.synthetic.quality.002", assetId: "knowledge-asset.synthetic.quality.v1", revisionId: "revision.synthetic.quality.v1", labelKey: "product.citation.quality" }],
  capability: { decision: "ALLOW", reasonCode: "SYNTHETIC_POLICY_ALLOW", providerCallCount: 1 },
};
