import { useEffect, useState } from "react";
import { fetchLivePlanningJourney, LivePlanningJourneyError, requestBoundedRerun, submitExactApproval, submitSemanticCorrection } from "../api/livePlanningJourney";
import type { LivePlanningJourney as Journey } from "../shared/livePlanningJourneyTypes";
import { useI18n } from "../i18n/useI18n";

export function LivePlanningJourney({ journeyId }: { journeyId: string }) {
  const { t } = useI18n(); const [journey, setJourney] = useState<Journey | null>(null); const [failure, setFailure] = useState<string | null>(null); const [objective, setObjective] = useState("");
  useEffect(() => { const controller = new AbortController(); fetchLivePlanningJourney(journeyId, controller.signal).then(setJourney).catch((error: unknown) => { if (!controller.signal.aborted) setFailure(error instanceof LivePlanningJourneyError ? `${error.state}:${error.reasonCode}` : "ERROR:LIVE_JOURNEY_ERROR"); }); return () => controller.abort(); }, [journeyId]);
  if (failure) return <section className="live-journey-state" role="alert"><strong>{t("liveJourney.unavailable")}</strong><span className="stable-id">{failure}</span></section>;
  if (!journey) return <section className="live-journey-state" role="status">{t("liveJourney.loading")}</section>;
  const revision = journey.product.revision;
  return <section className="live-journey" aria-labelledby="live-journey-title"><header><p className="eyebrow">{journey.provenance} · {journey.state}</p><h2 id="live-journey-title">{t("liveJourney.product.title")}</h2><p>{revision.objective}</p></header><div className="journey-grid"><article><h3>{t("liveJourney.plan")}</h3><ol>{revision.planTaskIds.map((id) => <li className="stable-id" key={id}>{id}</li>)}</ol><p className="stable-id">{revision.matchState} · {revision.placementState} · {revision.knowledgeState}</p></article><article><h3>{t("liveJourney.approval")}</h3><p className="stable-id">{revision.approvalState} · {revision.identity.canonicalDigest}</p>{revision.approvalState === "PENDING" && <button onClick={() => submitExactApproval(journeyId, revision.identity.canonicalDigest).then(setJourney).catch((e: LivePlanningJourneyError) => setFailure(`${e.state}:${e.reasonCode}`))}>{t("liveJourney.approve")}</button>}</article><article><h3>{t("liveJourney.answer")}</h3><p>{revision.answer ?? t("liveJourney.answerPending")}</p>{revision.citations.map((citation) => <p key={citation.citationId}><span className="stable-id">{citation.citationId}</span><br />{citation.documentId} · {citation.sectionId} · {citation.status}</p>)}</article><article><h3>{t("liveJourney.outcome")}</h3><p>{revision.outcome?.summary ?? t("liveJourney.outcomePending")}</p><p className="stable-id">{revision.outcome?.comparableMetric} · {revision.outcome?.comparableValue}</p>{revision.approvalState === "APPROVED" && revision.executionState === "NOT_REQUESTED" && <button onClick={() => requestBoundedRerun(journeyId, revision.identity.canonicalWorkflowRevisionId, revision.identity.canonicalDigest).then(setJourney).catch((e: LivePlanningJourneyError) => setFailure(`${e.state}:${e.reasonCode}`))}>{t("liveJourney.rerun")}</button>}</article></div><div className="journey-correction"><label htmlFor="live-correction">{t("liveJourney.correction")}</label><textarea id="live-correction" value={objective} onChange={(event) => setObjective(event.target.value)} /><button disabled={!objective.trim() || revision.lifecycle === "PENDING_APPROVAL"} onClick={() => submitSemanticCorrection(journeyId, revision.identity.canonicalWorkflowRevisionId, revision.identity.canonicalDigest, objective).then((value) => { setJourney(value); setObjective(""); }).catch((e: LivePlanningJourneyError) => setFailure(`${e.state}:${e.reasonCode}`))}>{t("liveJourney.createSuccessor")}</button></div></section>;
}
