import {useEffect,useMemo,useState} from "react";
import {Link,useSearchParams} from "react-router-dom";
import {listProblems,type ProblemPlan} from "../api/problemPlanning";

type EvidenceRow={id:string;type:string;subject:string;revision:string;digest:string;source:string;meaning:string};
function rows(problem:ProblemPlan):EvidenceRow[]{const plan=problem.planRevisions.at(-1);return [
  ...problem.knowledge.citations.map(item=>({id:item.citationId,type:"知识引用",subject:problem.name,revision:item.documentRevisionId,digest:item.chunkDigest,source:item.documentTitle,meaning:"规划采用的知识依据，不代表执行成功"})),
  ...problem.humanDecisions.map(item=>({id:item.evidenceId,type:"人工决定",subject:problem.name,revision:item.planRevisionId,digest:item.canonicalDigest,source:"业务问题治理记录",meaning:"人工修订或治理决定"})),
  ...(problem.approval?[{id:problem.approval.evidence.evidenceId,type:"计划批准",subject:problem.name,revision:problem.approval.planRevisionId,digest:problem.approval.canonicalDigest,source:"计划审批记录",meaning:"批准精确计划，不代表已经执行"}]:[]),
  ...problem.events.map(item=>({id:item.eventId,type:"业务事件",subject:problem.name,revision:plan?.planRevisionId??"未配置",digest:item.eventDigest,source:item.classification,meaning:"业务问题生命周期事件"})),
]}
export function EvidenceCenterPage(){const[items,setItems]=useState<ProblemPlan[]|null>(null),[error,setError]=useState(""),[params,setParams]=useSearchParams();const view=params.get("view")==="technical"?"technical":"product";const query=params.get("q")??"";useEffect(()=>{let active=true;listProblems().then(value=>active&&setItems(value)).catch(reason=>active&&setError(reason.reasonCode??"EVIDENCE_SOURCE_UNAVAILABLE"));return()=>{active=false}},[]);const evidence=useMemo(()=>items?.flatMap(rows).filter(item=>`${item.type}${item.subject}${item.id}`.toLowerCase().includes(query.toLowerCase()))??[],[items,query]);return <main className="px-page px-center-page"><header className="px-page-title"><div><p>证据中心 <small>Evidence</small></p><h1>Evidence：可追溯事实与依据</h1><span>区分知识引用、人工决定、批准记录与执行 Evidence；缺少事实时不推断成功。</span></div><Link className="px-secondary-button" to="/work">返回业务问题工作台</Link></header><section className="px-truth-banner" role="status"><span className="px-status success">REAL</span><strong>当前列表来自业务问题权威投影</strong><p>执行 Attempt Evidence 尚无跨执行聚合接口，因此标记为 NOT_CONNECTED。</p></section><nav className="px-view-tabs" aria-label="Evidence Product Technical View"><button className={view==="product"?"active":""} onClick={()=>setParams({view:"product",q:query})}>产品视图</button><button className={view==="technical"?"active":""} onClick={()=>setParams({view:"technical",q:query})}>技术视图</button></nav><section className="px-center-card"><label className="px-center-search">搜索 Evidence<input value={query} onChange={event=>setParams({view,q:event.target.value})} placeholder="按类型、业务问题或精确 ID 搜索"/></label>{error?<div className="px-state danger" role="alert"><strong>Evidence 数据源暂不可用</strong><p>{error}</p><button onClick={()=>location.reload()}>重试</button></div>:items===null?<div className="px-state" role="status"><strong>正在读取 Evidence</strong></div>:evidence.length===0?<div className="px-empty"><strong>尚无符合条件的 Evidence</strong><p>空列表不是成功，也不是数值 0。</p></div>:<div className="px-record-list">{evidence.map(item=><article key={item.id}><div><span className="px-status info">{item.type}</span><h2>{item.subject}</h2><p>{item.meaning}</p></div>{view==="product"?<dl><dt>数据来源</dt><dd>{item.source}</dd><dt>事实分类</dt><dd>REAL</dd></dl>:<dl><dt>Evidence ID</dt><dd><code>{item.id}</code></dd><dt>Revision</dt><dd><code>{item.revision}</code></dd><dt>Digest</dt><dd><code>{item.digest}</code></dd></dl>}<Link to="/work">查看业务上下文</Link></article>)}</div>}</section><section className="px-unavailable-grid"><article><span className="px-status neutral">NOT_CONNECTED</span><h2>执行 Evidence</h2><p>缺少跨 Attempt 的前端可调用聚合 read model。请从具体执行上下文检查。</p></article><article><span className="px-status neutral">UNAVAILABLE</span><h2>恢复与重新采集</h2><p>只有权威执行接口可触发恢复；本页不会模拟成功。</p><button disabled title="当前没有恢复 authority">恢复不可用</button></article></section></main>}
