import {useEffect,useMemo,useRef,useState} from "react";
import {useSearchParams} from "react-router-dom";
import {createWorkflowDefinition,editWorkflowDefinition,getWorkflowDefinition,hasSkillOperationBindings,listWorkflowDefinitions,publishWorkflowDefinition,referenceSupportsBinding,reviewWorkflowDefinition,successorWorkflowDefinition,validateWorkflowDefinition,workflowControlledState,WorkflowDefinitionRequestError,type WorkflowContent,type WorkflowControlledState,type WorkflowProjection,type WorkflowValidationIssue} from "../api/workflowDefinitions";
import {listWorkflowSkillOperations,WorkflowSkillOperationDirectoryError,type WorkflowSkillOperationEntry} from "../api/workflowSkillOperations";
import {WorkflowBuilderPage} from "./WorkflowBuilderPage";
import {WorkflowRevisionDesigner} from "./WorkflowRevisionDesigner";
import {WorkflowSkillOperationBindingEditor} from "./WorkflowSkillOperationBindingEditor";
import {WorkflowTechnicalProjection} from "./WorkflowTechnicalProjection";
import {WorkflowVersionComparison} from "./WorkflowVersionComparison";

const blank=(runtimeProfileId="",runtimeRevisionId=""):WorkflowContent=>({description:"",inputs:[],outputs:[],runtimeProfile:{kind:"RUNTIME_PROFILE",resourceId:runtimeProfileId,revisionId:runtimeRevisionId},tasks:[{taskId:"step-1",name:"",dependsOn:[],inputs:[],outputs:[],capabilityRequirements:[],references:[],retryLimit:0,timeoutSeconds:300,failurePolicy:"FAIL_WORKFLOW"}]});
const lifecycleLabel:Record<string,string>={DRAFT:"草稿",VALIDATED:"已校验",HUMAN_REVIEWED:"已审核",PUBLISHED:"已发布"};
type Recovery={state:WorkflowControlledState;reason:string;attemptedVersion:number;attemptedRevisionId:string|null;authoritative:WorkflowProjection;safeDraft:WorkflowContent|null};

export function WorkflowWorkbenchPage(){
 const [searchParams,setSearchParams]=useSearchParams();const [initialDefinitionId]=useState(()=>searchParams.get("resourceId"));
 const [items,setItems]=useState<WorkflowProjection[]>([]),[selected,setSelected]=useState<WorkflowProjection|null>(null),[builder,setBuilder]=useState<WorkflowContent|null>(null),[builderName,setBuilderName]=useState("");
 const [catalogCollapsed,setCatalogCollapsed]=useState(false),[catalogPage,setCatalogPage]=useState(0),[pendingSwitch,setPendingSwitch]=useState<string|null>(null),[editorBaseline,setEditorBaseline]=useState(""),[saveNotice,setSaveNotice]=useState<string|null>(null),[mobilePane,setMobilePane]=useState<"catalog"|"workspace">(()=>initialDefinitionId?"workspace":"catalog");
 const [state,setState]=useState<"LOADING"|"READY"|"SAVING">("LOADING"),[failure,setFailure]=useState<{state:WorkflowControlledState;reason:string;issues:WorkflowValidationIssue[]}|null>(null),[recovery,setRecovery]=useState<Recovery|null>(null),[selectedTask,setSelectedTask]=useState<string|null>(null),[query,setQuery]=useState(searchParams.get("query")??""),[filter,setFilter]=useState(searchParams.get("lifecycle")??"ALL"),[runtimeId,setRuntimeId]=useState(""),[runtimeRevision,setRuntimeRevision]=useState("");
 const [operationDirectory,setOperationDirectory]=useState<WorkflowSkillOperationEntry[]>([]),[operationDirectoryState,setOperationDirectoryState]=useState<"LOADING"|"READY"|"UNAVAILABLE">("LOADING"),[operationDirectoryReason,setOperationDirectoryReason]=useState<string|null>(null),[rejectedSkillCount,setRejectedSkillCount]=useState(0);
 const requestId=useRef(0),directoryRequestId=useRef(0),actionInFlight=useRef(false),saveInFlight=useRef(false),readAbort=useRef<AbortController|null>(null);
 const editorId=useRef(0);const [savingEditor,setSavingEditor]=useState(false);const renderedEditorId=editorId.current;
 const editorLocked=()=>saveInFlight.current||renderedEditorId!==editorId.current;
 const changeBuilder=(value:WorkflowContent)=>{if(!editorLocked()){setBuilder(value);setSaveNotice(null)}};
 const closeEditor=()=>{editorId.current+=1;requestId.current+=1;setBuilder(null);setRecovery(null);setSaveNotice(null);setState("READY")};
 const editorSnapshot=(name:string,content:WorkflowContent)=>JSON.stringify({name,content});
 function preserveContext(patch:Record<string,string|null>){const next=new URLSearchParams(searchParams);for(const [key,value] of Object.entries(patch)){if(value)next.set(key,value);else next.delete(key)}setSearchParams(next,{replace:true})}
 function recordFailure(reason:unknown){const error=reason instanceof WorkflowDefinitionRequestError?reason:new WorkflowDefinitionRequestError("WORKFLOW_DEFINITION_UNAVAILABLE",503);setFailure({state:workflowControlledState(error),reason:error.reasonCode,issues:error.validationIssues});setState("READY")}
 async function loadOperationDirectory(){const current=++directoryRequestId.current;setOperationDirectoryState("LOADING");try{const result=await listWorkflowSkillOperations();if(current!==directoryRequestId.current)return;setOperationDirectory(result.entries);setRejectedSkillCount(result.rejectedResources);setOperationDirectoryReason(null);setOperationDirectoryState("READY")}catch(reason){if(current!==directoryRequestId.current)return;setOperationDirectory([]);setRejectedSkillCount(0);setOperationDirectoryReason(reason instanceof WorkflowSkillOperationDirectoryError?reason.reasonCode:"SKILL_OPERATION_DIRECTORY_UNAVAILABLE");setOperationDirectoryState("UNAVAILABLE")}}
 async function refresh(id?:string){editorId.current+=1;setBuilder(null);readAbort.current?.abort();const controller=new AbortController();readAbort.current=controller;const current=++requestId.current;setState("LOADING");try{const values=await listWorkflowDefinitions(controller.signal);if(current!==requestId.current)return;const detail=id?await getWorkflowDefinition(id,controller.signal):null;if(current!==requestId.current)return;setItems(values);setSelected(detail);setSelectedTask(null);setMobilePane(id?"workspace":"catalog");if(id)preserveContext({resourceId:id});setFailure(null);setRecovery(null);setPendingSwitch(null);setSaveNotice(null);setState("READY")}catch(reason){if(reason instanceof DOMException&&reason.name==="AbortError")return;if(current===requestId.current)recordFailure(reason)}}
 useEffect(()=>{const controller=new AbortController();readAbort.current=controller;const current=++requestId.current;Promise.all([listWorkflowDefinitions(controller.signal),initialDefinitionId?getWorkflowDefinition(initialDefinitionId,controller.signal):Promise.resolve(null)]).then(([values,detail])=>{if(current!==requestId.current)return;setItems(values);if(detail)setSelected(detail);setState("READY")}).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;if(current===requestId.current)recordFailure(reason)});return()=>{controller.abort();requestId.current+=1}},[initialDefinitionId]);
 useEffect(()=>{const current=++directoryRequestId.current;listWorkflowSkillOperations().then(result=>{if(current!==directoryRequestId.current)return;setOperationDirectory(result.entries);setRejectedSkillCount(result.rejectedResources);setOperationDirectoryReason(null);setOperationDirectoryState("READY")}).catch(reason=>{if(current!==directoryRequestId.current)return;setOperationDirectory([]);setRejectedSkillCount(0);setOperationDirectoryReason(reason instanceof WorkflowSkillOperationDirectoryError?reason.reasonCode:"SKILL_OPERATION_DIRECTORY_UNAVAILABLE");setOperationDirectoryState("UNAVAILABLE")});return()=>{directoryRequestId.current+=1}},[]);
 function startCreate(){const content=blank();editorId.current+=1;requestId.current+=1;setBuilderName("");setBuilder(content);setEditorBaseline(editorSnapshot("",content));setMobilePane("workspace");setSaveNotice(null);setFailure(null);setRecovery(null)}
 function openWithRuntime(){const name=selected?.definition.name??"",content=blank(runtimeId,runtimeRevision);editorId.current+=1;requestId.current+=1;setBuilderName(name);setBuilder(content);setEditorBaseline(editorSnapshot(name,content));setMobilePane("workspace");setSaveNotice(null);setFailure(null)}
 function startEdit(){if(!selected)return;const draft=selected.definition.revisions.find(item=>item.revisionId===selected.definition.currentDraftRevisionId);if(draft){const content=structuredClone(draft.content);editorId.current+=1;requestId.current+=1;setBuilderName(selected.definition.name);setBuilder(content);setEditorBaseline(editorSnapshot(selected.definition.name,content));setMobilePane("workspace");setSaveNotice(null);setFailure(null)}}
 async function save(){if(editorLocked()||!builder||!builderName.trim()||saveInFlight.current)return;const current=++requestId.current,ownerEditor=editorId.current,selectedAtStart=selected,builderAtStart=structuredClone(builder),nameAtStart=builderName;saveInFlight.current=true;setSavingEditor(true);setSaveNotice(null);setRecovery(null);setState("SAVING");try{const value=selectedAtStart?.definition.currentDraftRevisionId&&selectedAtStart.definition.name===nameAtStart?await editWorkflowDefinition(selectedAtStart.definition,builderAtStart):await createWorkflowDefinition(nameAtStart.trim(),builderAtStart);if(current!==requestId.current||ownerEditor!==editorId.current)return;const [values,authoritative]=await Promise.all([listWorkflowDefinitions(),getWorkflowDefinition(value.definition.workflowDefinitionId)]);if(current!==requestId.current||ownerEditor!==editorId.current)return;setItems(values);setSelected(authoritative);setSelectedTask(null);setBuilder(null);setBuilderName("");setSaveNotice(`已保存 ${nameAtStart.trim()}，并读回权威修订。`);preserveContext({resourceId:value.definition.workflowDefinitionId});setFailure(null);setRecovery(null);setState("READY")}catch(reason){if(current!==requestId.current||ownerEditor!==editorId.current)return;const error=reason instanceof WorkflowDefinitionRequestError?reason:new WorkflowDefinitionRequestError("WORKFLOW_DEFINITION_UNAVAILABLE",503);if(error.status===409&&selectedAtStart){try{const authoritative=await getWorkflowDefinition(selectedAtStart.definition.workflowDefinitionId);if(current!==requestId.current||ownerEditor!==editorId.current)return;setSelected(authoritative);setRecovery({state:workflowControlledState(error),reason:error.reasonCode,attemptedVersion:selectedAtStart.definition.aggregateVersion,attemptedRevisionId:selectedAtStart.definition.currentDraftRevisionId,authoritative,safeDraft:builderAtStart});setFailure(null);setState("READY");return}catch(fetchReason){if(current===requestId.current&&ownerEditor===editorId.current)recordFailure(fetchReason);return}}recordFailure(error)}finally{saveInFlight.current=false;setSavingEditor(false)}}
 async function act(operation:(value:WorkflowProjection["definition"])=>Promise<WorkflowProjection>){if(!selected||actionInFlight.current)return;const current=++requestId.current,selectedAtStart=selected,attemptedVersion=selected.definition.aggregateVersion,attemptedRevisionId=selected.definition.currentDraftRevisionId??selected.definition.publishedRevisionId;actionInFlight.current=true;setState("SAVING");try{const value=await operation(selectedAtStart.definition);if(current!==requestId.current)return;const [values,authoritative]=await Promise.all([listWorkflowDefinitions(),getWorkflowDefinition(value.definition.workflowDefinitionId)]);if(current!==requestId.current)return;setSelected(authoritative);setItems(values);setSelectedTask(null);setFailure(null);setRecovery(null);setState("READY")}catch(reason){if(current!==requestId.current)return;const error=reason instanceof WorkflowDefinitionRequestError?reason:new WorkflowDefinitionRequestError("WORKFLOW_DEFINITION_UNAVAILABLE",503);if(error.status===409){try{const authoritative=await getWorkflowDefinition(selectedAtStart.definition.workflowDefinitionId);if(current!==requestId.current)return;setSelected(authoritative);setRecovery({state:workflowControlledState(error),reason:error.reasonCode,attemptedVersion,attemptedRevisionId,authoritative,safeDraft:builder?structuredClone(builder):null});setFailure(null);setState("READY");return}catch(fetchReason){if(current===requestId.current)recordFailure(fetchReason);return}}recordFailure(error)}finally{actionInFlight.current=false}}
 const filtered=useMemo(()=>items.filter(item=>(filter==="ALL"||item.definition.lifecycleState===filter)&&`${item.definition.name} ${item.definition.workflowDefinitionId} ${item.definition.revisions.at(-1)?.content.description??""}`.toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
 const pageSize=8,pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)),currentCatalogPage=Math.min(catalogPage,pageCount-1),visibleDefinitions=filtered.slice(currentCatalogPage*pageSize,(currentCatalogPage+1)*pageSize);
 function requestSwitch(id:string){if(builder){setPendingSwitch(id);return}void refresh(id)}
 const definition=selected?.definition,draft=definition?.revisions.find(item=>item.revisionId===definition.currentDraftRevisionId),review=definition?.reviews.at(-1),active=draft??definition?.revisions.at(-1),activeHasSkillBindings=Boolean(active?.content.tasks.some(hasSkillOperationBindings));
 const activeBindingsReviewable=operationDirectoryState==="READY"&&Boolean(active)&&active!.content.tasks.every(task=>(task.skillOperationBindings??[]).every(binding=>referenceSupportsBinding(task,binding)&&operationDirectory.some(entry=>entry.skillId===binding.skillId&&entry.skillRevisionId===binding.skillRevisionId&&entry.skillDigest===binding.skillDigest&&entry.operation.name===binding.operation)));
 const bindingValidationBlocked=activeHasSkillBindings&&!activeBindingsReviewable;
 const hasUnsavedChanges=Boolean(builder)&&editorSnapshot(builderName,builder!)!==editorBaseline;
 return <main className="module-workbench resource-management workflow-workbench">
  <header className="workflow-workbench__header"><div><p className="eyebrow">Workflow 定义</p><h1>工作流中心</h1><p>设计、校验和发布工作流定义。配置有效不表示正在运行或执行成功。</p></div><div className="workflow-workbench__header-actions"><button className="workflow-primary-action" disabled={state!=="READY"} onClick={startCreate}>新建 Workflow Definition</button></div></header>
  {state==="LOADING"&&<p role="status">正在读取权威 Workflow Definition…</p>}{state==="SAVING"&&<p role="status">正在保存受治理的 Workflow Definition…</p>}{saveNotice&&<p className="workflow-save-notice" role="status">{saveNotice}</p>}
  {failure&&<section role="alert" aria-label={`${failure.state} state`}><h2>{failure.state}</h2><p>{failure.state==="denied"||failure.state==="not found"?"Workflow 不可用或当前访问未获授权。":failure.reason}</p>{failure.issues.length>0&&<><h3>字段错误</h3><ul>{failure.issues.map((issue,index)=><li key={`${issue.path.join(".")}:${index}`}><code>{issue.path.join(".")}</code> · {issue.code}</li>)}</ul><p>仅展示字段路径和错误类型，不回显提交 input 或未脱敏响应。</p></>}<button onClick={()=>void refresh(definition?.workflowDefinitionId)}>重新读取权威数据</button></section>}
  {recovery&&<section role="alert" aria-label="Guided conflict recovery"><h2>{recovery.state}: 需要明确恢复操作</h2><dl><dt>Attempted aggregate version / 尝试的聚合版本</dt><dd>{recovery.attemptedVersion}</dd><dt>Authoritative aggregate version / 权威聚合版本</dt><dd>{recovery.authoritative.definition.aggregateVersion}</dd><dt>尝试的修订</dt><dd>{recovery.attemptedRevisionId??"NO_REVISION"}</dd><dt>权威修订</dt><dd>{recovery.authoritative.definition.revisions.at(-1)?.revisionId??"NO_REVISION"}</dd></dl><p>已只读获取权威版本。写请求不会自动重放，未保存的 Definition 输入（包括完整 Skill operation binding）会保留到你明确决定。</p>{recovery.safeDraft?<button aria-label="Explicitly reapply safe draft input" onClick={()=>{if(editorLocked())return;setBuilder(structuredClone(recovery.safeDraft!));setBuilderName(recovery.authoritative.definition.name);setRecovery(null)}}>明确恢复保留的定义输入</button>:<button onClick={()=>setRecovery(null)}>确认权威版本</button>}<button onClick={closeEditor}>放弃保留输入</button></section>}
  {pendingSwitch&&<section role="alert" aria-label="未保存 Workflow 编辑"><h2>当前编写器有未保存输入</h2><p>切换 Workflow 会关闭当前编写器。输入不会被静默丢弃。</p><button type="button" onClick={()=>setPendingSwitch(null)}>继续编辑当前 Workflow</button><button type="button" onClick={()=>{const id=pendingSwitch;setPendingSwitch(null);void refresh(id)}}>放弃未保存输入并切换</button></section>}
  <section className="workbench-card resource-form workflow-quick-create" aria-label="Workflow quick authoring context"><div><h2>创建工作流</h2><p>直接新建，或带入已发布 Runtime Profile 的精确修订。</p></div><div className="workflow-quick-create__fields"><label>Published Runtime Profile ID<input value={runtimeId} onChange={event=>setRuntimeId(event.target.value)}/></label><label>Published Runtime revision ID<input value={runtimeRevision} onChange={event=>setRuntimeRevision(event.target.value)}/></label></div><div className="module-actions"><button disabled={state!=="READY"} onClick={startCreate}>新建 Workflow Definition</button><button disabled={state!=="READY"||!runtimeId||!runtimeRevision} onClick={openWithRuntime}>Open Workflow Builder</button></div></section>
  <details className="workflow-operation-directory-status" aria-label="Skill operation directory status"><summary>Skill operation 目录状态</summary><p>{operationDirectoryState==="LOADING"?"正在读取正式目录…":operationDirectoryState==="UNAVAILABLE"?`目录不可用：${operationDirectoryReason}`:`${operationDirectory.length} 个合格 operation；${rejectedSkillCount} 个不合格或缺少 operation 的 Skill 已排除。`}</p>{operationDirectoryState==="UNAVAILABLE"&&<button type="button" onClick={()=>void loadOperationDirectory()}>重新读取 Skill operation 目录</button>}<p>只接收已发布、启用、未归档、未弃用且契约完整的 READ_ONLY operation；不会从名称或 capability 推断。</p></details>
  <div className="workflow-mobile-pane-tabs" role="tablist" aria-label="工作流页面区域"><button type="button" role="tab" aria-selected={mobilePane==="catalog"} onClick={()=>setMobilePane("catalog")}>工作流目录</button><button type="button" role="tab" aria-selected={mobilePane==="workspace"} onClick={()=>setMobilePane("workspace")}>流程设计</button></div>
  <div className={`module-layout workflow-catalog-layout${catalogCollapsed?" workflow-catalog-layout--collapsed":""}`} data-mobile-pane={mobilePane}>
   <aside aria-label="Workflow 列表">
    <header className="workflow-catalog__header"><div><p className="eyebrow">工作流目录</p><h2>选择工作流</h2></div><button type="button" className="workflow-catalog__collapse" aria-label={catalogCollapsed?"展开 Workflow 列表":"折叠 Workflow 列表"} title={catalogCollapsed?"展开工作流目录":"折叠工作流目录"} aria-expanded={!catalogCollapsed} onClick={()=>setCatalogCollapsed(value=>!value)}>{catalogCollapsed?"›":"‹"}</button></header>
    {!catalogCollapsed&&<><div className="workflow-catalog__filters"><label>搜索<input aria-label="搜索 Workflow Definition" value={query} placeholder="名称、说明或 ID" onChange={event=>{setQuery(event.target.value);setCatalogPage(0);preserveContext({query:event.target.value||null})}}/></label><label>生命周期<select aria-label="Workflow 生命周期筛选" value={filter} onChange={event=>{setFilter(event.target.value);setCatalogPage(0);preserveContext({lifecycle:event.target.value==="ALL"?null:event.target.value})}}><option value="ALL">全部</option><option value="DRAFT">草稿</option><option value="VALIDATED">已校验</option><option value="HUMAN_REVIEWED">已审核</option><option value="PUBLISHED">已发布</option></select></label></div>{filtered.length===0&&state==="READY"?<p>没有匹配的 Workflow Definition。</p>:<div className="workflow-catalog__items">{visibleDefinitions.map(item=>{const revision=item.definition.revisions.find(candidate=>candidate.revisionId===(item.definition.currentDraftRevisionId??item.definition.publishedRevisionId))??item.definition.revisions.at(-1);return <article className={`workflow-catalog__item${definition?.workflowDefinitionId===item.definition.workflowDefinitionId?" selected":""}`} key={item.definition.workflowDefinitionId}><button type="button" onClick={()=>requestSwitch(item.definition.workflowDefinitionId)}><span className="workflow-catalog__item-heading"><strong>{item.definition.name}</strong><span className="workflow-lifecycle-badge">{lifecycleLabel[item.definition.lifecycleState]??item.definition.lifecycleState}</span></span><span className="workflow-catalog__summary">摘要：{revision?.content.description||"暂无简介"}</span><small>适用修订 · {revision?.revisionId??"NO_REVISION"}</small></button><details><summary>查看技术 ID</summary><code>{item.definition.workflowDefinitionId}</code></details></article>})}</div>}<nav className="workflow-catalog-pagination" aria-label="Workflow 列表分页"><button type="button" disabled={currentCatalogPage<=0} onClick={()=>setCatalogPage(Math.max(0,currentCatalogPage-1))}>上一页</button><span>第 {currentCatalogPage+1} / {pageCount} 页</span><button type="button" disabled={currentCatalogPage>=pageCount-1} onClick={()=>setCatalogPage(Math.min(pageCount-1,currentCatalogPage+1))}>下一页</button></nav></>}
   </aside>
   <section className="workflow-workspace">
    {definition?.publishedRevisionId&&!definition.currentDraftRevisionId&&<section className="workflow-successor-callout"><div><strong>此修订已发布并保持只读</strong><p>需要修改时，请创建正式后继草稿。</p></div><button className="workflow-primary-action" disabled={state!=="READY"} onClick={()=>void act(x=>successorWorkflowDefinition(x.workflowDefinitionId,x.aggregateVersion))}>Create Workflow successor</button></section>}
    {builder?<section className="workflow-authoring" aria-label="Workflow authoring" aria-busy={savingEditor}><header className="workflow-authoring__header"><div><p className="eyebrow">草稿编辑</p><h2>{builderName||"新工作流"}</h2><p className={`workflow-dirty-state${hasUnsavedChanges?" is-dirty":""}`} role="status">{hasUnsavedChanges?"有未保存修改":"尚无未保存修改"}</p></div><div className="workflow-authoring__actions"><button className="workflow-primary-action workflow-mobile-save-action" disabled={state!=="READY"||!builderName.trim()} onClick={()=>void save()}>保存当前草稿</button><button className="workflow-secondary-action" onClick={closeEditor}>关闭编写器并保留权威版本</button></div></header>{savingEditor&&<p role="status">正在保存当前编写器，提交内容已锁定。离开或关闭编写器不会取消后端保存。</p>}<fieldset disabled={savingEditor} aria-label="Workflow editor fields" onChangeCapture={event=>{if(editorLocked()){event.preventDefault();event.stopPropagation()}}} onClickCapture={event=>{if(editorLocked()){event.preventDefault();event.stopPropagation()}}}><label className="workflow-name-field">Workflow 名称<input value={builderName} maxLength={120} onChange={event=>{if(!editorLocked()){setBuilderName(event.target.value);setSaveNotice(null)}}}/></label><WorkflowBuilderPage content={builder} onChange={changeBuilder} isLocked={editorLocked} operationDirectory={operationDirectory} operationDirectoryState={operationDirectoryState} operationDirectoryReason={operationDirectoryReason}/><div className="module-actions workflow-savebar"><span>{hasUnsavedChanges?"准备保存当前完整定义":"可继续编辑或保存当前定义"}</span><button className="workflow-primary-action" disabled={state!=="READY"||!builderName.trim()} onClick={()=>void save()}>保存工作流草稿<span className="sr-only"> Save governed Workflow draft</span></button></div></fieldset></section>:!definition?<div className="empty-state workflow-workspace__empty"><h2>选择工作流</h2><p>从目录选择后，可查看步骤、精确资源绑定、修订与消费者。</p><button type="button" className="workflow-secondary-action workflow-mobile-catalog-shortcut" onClick={()=>setMobilePane("catalog")}>打开工作流目录</button></div>:<><header className="workflow-definition-header"><div><span className="workflow-lifecycle-badge">{lifecycleLabel[definition.lifecycleState]??definition.lifecycleState}<span className="workflow-technical-state">{definition.lifecycleState}</span></span><h2>{definition.name}</h2><p>{active?.content.description||"未提供用途说明"}</p></div><details><summary>查看 Workflow 技术 ID</summary><span className="technical-value">{definition.workflowDefinitionId}</span></details></header>
    {active&&<section className="workflow-definition-body"><header className="workflow-section-heading"><div><p className="eyebrow">流程设计</p><h3>步骤与依赖 <small>Canonical DAG</small></h3></div>{draft&&<div className="module-actions workflow-lifecycle-actions"><button className="workflow-primary-action" disabled={state!=="READY"} onClick={startEdit}>编辑当前 Draft</button>{draft.state==="DRAFT"&&<button disabled={state!=="READY"||bindingValidationBlocked} aria-describedby={bindingValidationBlocked?"workflow-skill-validation-blocked":undefined} onClick={()=>void act(x=>validateWorkflowDefinition(x.workflowDefinitionId,x.aggregateVersion))}>Validate DAG and references</button>}{draft.state==="VALIDATED"&&<button disabled={state!=="READY"} onClick={()=>void act(x=>reviewWorkflowDefinition(x.workflowDefinitionId,x.aggregateVersion,draft.digest))}>Review exact Workflow digest</button>}{draft.state==="HUMAN_REVIEWED"&&review&&<button disabled={state!=="READY"} onClick={()=>void act(x=>publishWorkflowDefinition(x.workflowDefinitionId,x.aggregateVersion,draft.digest,review.reviewId))}>Publish immutable Workflow</button>}</div>}</header><WorkflowRevisionDesigner key={active.revisionId} content={active.content} selectedTaskId={selectedTask} onSelect={setSelectedTask} directory={operationDirectory} directoryState={operationDirectoryState}/>{selectedTask&&<p role="status">已选择 Definition 步骤：<span className="technical-value">{selectedTask}</span>。这不是运行状态。</p>}{draft?.state==="DRAFT"&&bindingValidationBlocked&&<p id="workflow-skill-validation-blocked" role="status">正式目录尚未返回与已保存 Skill revision、digest、operation 完全一致的合格身份。Draft 会保留，但页面不会把缺失或不合格 operation 提交为已验证。</p>}<details className="workflow-review-details"><summary>校验、绑定与修订详情</summary><section className="workflow-binding-review" aria-label="Workflow Skill operation binding review"><h3>Validate / review / publish 前绑定审查</h3>{active.content.tasks.map(task=><WorkflowSkillOperationBindingEditor key={task.taskId} task={task} readOnly directory={operationDirectory} directoryState={operationDirectoryState} directoryReason={operationDirectoryReason}/>)}<p>这里显示后端 GET 返回的实际绑定；历史无绑定版本保持未绑定，不会自动补写。</p></section><label>Exact revision digest<input readOnly value={active.digest}/></label><h4>生命周期证据</h4><p>Validation: {draft?.state!=="DRAFT"?"RECORDED":"REQUIRED"} · Human review: {review?.reviewId??"REQUIRED"} · Publication: {definition.publishedRevisionId??"NOT_PUBLISHED"}</p><p>绑定与发布不等于执行授权；本页不创建 Run、Task Run、Attempt、Plan 或 dispatch。</p></details></section>}
    <details className="workflow-history-details"><summary>关系、消费者与修订历史 <span>{definition.relationships.length} relationships · {definition.consumers.length} consumers</span></summary><ol>{definition.revisions.map(item=><li key={item.revisionId}>{item.state} · <span className="technical-value">{item.revisionId}</span> · digest {item.digest} · Skill operations {item.content.tasks.reduce((count,task)=>count+(task.skillOperationBindings?.length??0),0)}</li>)}</ol><WorkflowVersionComparison definition={definition}/><WorkflowTechnicalProjection projection={selected}/></details></>}
   </section>
  </div>
 </main>;
}
