import {useEffect,useMemo,useRef,useState} from "react";
import {useSearchParams} from "react-router-dom";
import {createWorkflowDefinition,editWorkflowDefinition,getWorkflowDefinition,hasSkillOperationBindings,listWorkflowDefinitions,publishWorkflowDefinition,referenceSupportsBinding,reviewWorkflowDefinition,successorWorkflowDefinition,validateWorkflowDefinition,workflowControlledState,WorkflowDefinitionRequestError,type WorkflowContent,type WorkflowControlledState,type WorkflowProjection} from "../api/workflowDefinitions";
import {listWorkflowSkillOperations,WorkflowSkillOperationDirectoryError,type WorkflowSkillOperationEntry} from "../api/workflowSkillOperations";
import {WorkflowBuilderPage} from "./WorkflowBuilderPage";
import {WorkflowSkillOperationBindingEditor} from "./WorkflowSkillOperationBindingEditor";
import {WorkflowTechnicalProjection} from "./WorkflowTechnicalProjection";
import {WorkflowVersionComparison} from "./WorkflowVersionComparison";

const blank=(runtimeProfileId="",runtimeRevisionId=""):WorkflowContent=>({description:"",inputs:[],outputs:[],runtimeProfile:{kind:"RUNTIME_PROFILE",resourceId:runtimeProfileId,revisionId:runtimeRevisionId},tasks:[{taskId:"step-1",name:"",dependsOn:[],inputs:[],outputs:[],capabilityRequirements:[],references:[],retryLimit:0,timeoutSeconds:300,failurePolicy:"FAIL_WORKFLOW"}]});
type Recovery={state:WorkflowControlledState;reason:string;attemptedVersion:number;attemptedRevisionId:string|null;authoritative:WorkflowProjection;safeDraft:WorkflowContent|null};

export function WorkflowWorkbenchPage(){
 const [searchParams,setSearchParams]=useSearchParams();const [initialDefinitionId]=useState(()=>searchParams.get("resourceId"));
 const [items,setItems]=useState<WorkflowProjection[]>([]),[selected,setSelected]=useState<WorkflowProjection|null>(null),[builder,setBuilder]=useState<WorkflowContent|null>(null),[builderName,setBuilderName]=useState("");
 const [state,setState]=useState<"LOADING"|"READY"|"SAVING">("LOADING"),[failure,setFailure]=useState<{state:WorkflowControlledState;reason:string}|null>(null),[recovery,setRecovery]=useState<Recovery|null>(null),[selectedTask,setSelectedTask]=useState<string|null>(null),[query,setQuery]=useState(searchParams.get("query")??""),[filter,setFilter]=useState(searchParams.get("lifecycle")??"ALL"),[runtimeId,setRuntimeId]=useState(""),[runtimeRevision,setRuntimeRevision]=useState("");
 const [operationDirectory,setOperationDirectory]=useState<WorkflowSkillOperationEntry[]>([]),[operationDirectoryState,setOperationDirectoryState]=useState<"LOADING"|"READY"|"UNAVAILABLE">("LOADING"),[operationDirectoryReason,setOperationDirectoryReason]=useState<string|null>(null),[rejectedSkillCount,setRejectedSkillCount]=useState(0);
 const requestId=useRef(0),directoryRequestId=useRef(0),actionInFlight=useRef(false),saveInFlight=useRef(false);
 const editorId=useRef(0);const [savingEditor,setSavingEditor]=useState(false);const renderedEditorId=editorId.current;
 const editorLocked=()=>saveInFlight.current||renderedEditorId!==editorId.current;
 const changeBuilder=(value:WorkflowContent)=>{if(!editorLocked())setBuilder(value)};
 const closeEditor=()=>{editorId.current+=1;requestId.current+=1;setBuilder(null);setRecovery(null);setState("READY")};
 function preserveContext(patch:Record<string,string|null>){const next=new URLSearchParams(searchParams);for(const [key,value] of Object.entries(patch)){if(value)next.set(key,value);else next.delete(key)}setSearchParams(next,{replace:true})}
 function recordFailure(reason:unknown){const error=reason instanceof WorkflowDefinitionRequestError?reason:new WorkflowDefinitionRequestError("WORKFLOW_DEFINITION_UNAVAILABLE",503);setFailure({state:workflowControlledState(error),reason:error.reasonCode});setState("READY")}
 async function loadOperationDirectory(){const current=++directoryRequestId.current;setOperationDirectoryState("LOADING");try{const result=await listWorkflowSkillOperations();if(current!==directoryRequestId.current)return;setOperationDirectory(result.entries);setRejectedSkillCount(result.rejectedResources);setOperationDirectoryReason(null);setOperationDirectoryState("READY")}catch(reason){if(current!==directoryRequestId.current)return;setOperationDirectory([]);setRejectedSkillCount(0);setOperationDirectoryReason(reason instanceof WorkflowSkillOperationDirectoryError?reason.reasonCode:"SKILL_OPERATION_DIRECTORY_UNAVAILABLE");setOperationDirectoryState("UNAVAILABLE")}}
 async function refresh(id?:string){editorId.current+=1;setBuilder(null);const current=++requestId.current;setState("LOADING");try{const values=await listWorkflowDefinitions();if(current!==requestId.current)return;const detail=id?await getWorkflowDefinition(id):null;if(current!==requestId.current)return;setItems(values);setSelected(detail);setSelectedTask(null);if(id)preserveContext({resourceId:id});setFailure(null);setRecovery(null);setState("READY")}catch(reason){if(current===requestId.current)recordFailure(reason)}}
 useEffect(()=>{const current=++requestId.current;Promise.all([listWorkflowDefinitions(),initialDefinitionId?getWorkflowDefinition(initialDefinitionId):Promise.resolve(null)]).then(([values,detail])=>{if(current!==requestId.current)return;setItems(values);if(detail)setSelected(detail);setState("READY")}).catch(reason=>{if(current===requestId.current)recordFailure(reason)});return()=>{requestId.current+=1}},[initialDefinitionId]);
 useEffect(()=>{const current=++directoryRequestId.current;listWorkflowSkillOperations().then(result=>{if(current!==directoryRequestId.current)return;setOperationDirectory(result.entries);setRejectedSkillCount(result.rejectedResources);setOperationDirectoryReason(null);setOperationDirectoryState("READY")}).catch(reason=>{if(current!==directoryRequestId.current)return;setOperationDirectory([]);setRejectedSkillCount(0);setOperationDirectoryReason(reason instanceof WorkflowSkillOperationDirectoryError?reason.reasonCode:"SKILL_OPERATION_DIRECTORY_UNAVAILABLE");setOperationDirectoryState("UNAVAILABLE")});return()=>{directoryRequestId.current+=1}},[]);
 function startCreate(){editorId.current+=1;requestId.current+=1;setBuilderName("");setBuilder(blank());setFailure(null);setRecovery(null)}
 function openWithRuntime(){editorId.current+=1;requestId.current+=1;setBuilderName(selected?.definition.name??"");setBuilder(blank(runtimeId,runtimeRevision));setFailure(null)}
 function startEdit(){if(!selected)return;const draft=selected.definition.revisions.find(item=>item.revisionId===selected.definition.currentDraftRevisionId);if(draft){editorId.current+=1;requestId.current+=1;setBuilderName(selected.definition.name);setBuilder(structuredClone(draft.content));setFailure(null)}}
 async function save(){if(editorLocked()||!builder||!builderName.trim()||saveInFlight.current)return;const current=++requestId.current,ownerEditor=editorId.current,selectedAtStart=selected,builderAtStart=structuredClone(builder),nameAtStart=builderName;saveInFlight.current=true;setSavingEditor(true);setRecovery(null);setState("SAVING");try{const value=selectedAtStart?.definition.currentDraftRevisionId&&selectedAtStart.definition.name===nameAtStart?await editWorkflowDefinition(selectedAtStart.definition,builderAtStart):await createWorkflowDefinition(nameAtStart.trim(),builderAtStart);if(current!==requestId.current||ownerEditor!==editorId.current)return;const [values,authoritative]=await Promise.all([listWorkflowDefinitions(),getWorkflowDefinition(value.definition.workflowDefinitionId)]);if(current!==requestId.current||ownerEditor!==editorId.current)return;setItems(values);setSelected(authoritative);setSelectedTask(null);setBuilder(null);setBuilderName("");preserveContext({resourceId:value.definition.workflowDefinitionId});setFailure(null);setRecovery(null);setState("READY")}catch(reason){if(current!==requestId.current||ownerEditor!==editorId.current)return;const error=reason instanceof WorkflowDefinitionRequestError?reason:new WorkflowDefinitionRequestError("WORKFLOW_DEFINITION_UNAVAILABLE",503);if(error.status===409&&selectedAtStart){try{const authoritative=await getWorkflowDefinition(selectedAtStart.definition.workflowDefinitionId);if(current!==requestId.current||ownerEditor!==editorId.current)return;setSelected(authoritative);setRecovery({state:workflowControlledState(error),reason:error.reasonCode,attemptedVersion:selectedAtStart.definition.aggregateVersion,attemptedRevisionId:selectedAtStart.definition.currentDraftRevisionId,authoritative,safeDraft:builderAtStart});setFailure(null);setState("READY");return}catch(fetchReason){if(current===requestId.current&&ownerEditor===editorId.current)recordFailure(fetchReason);return}}recordFailure(error)}finally{saveInFlight.current=false;setSavingEditor(false)}}
 async function act(operation:(value:WorkflowProjection["definition"])=>Promise<WorkflowProjection>){if(!selected||actionInFlight.current)return;const current=++requestId.current,selectedAtStart=selected,attemptedVersion=selected.definition.aggregateVersion,attemptedRevisionId=selected.definition.currentDraftRevisionId??selected.definition.publishedRevisionId;actionInFlight.current=true;setState("SAVING");try{const value=await operation(selectedAtStart.definition);if(current!==requestId.current)return;const [values,authoritative]=await Promise.all([listWorkflowDefinitions(),getWorkflowDefinition(value.definition.workflowDefinitionId)]);if(current!==requestId.current)return;setSelected(authoritative);setItems(values);setSelectedTask(null);setFailure(null);setRecovery(null);setState("READY")}catch(reason){if(current!==requestId.current)return;const error=reason instanceof WorkflowDefinitionRequestError?reason:new WorkflowDefinitionRequestError("WORKFLOW_DEFINITION_UNAVAILABLE",503);if(error.status===409){try{const authoritative=await getWorkflowDefinition(selectedAtStart.definition.workflowDefinitionId);if(current!==requestId.current)return;setSelected(authoritative);setRecovery({state:workflowControlledState(error),reason:error.reasonCode,attemptedVersion,attemptedRevisionId,authoritative,safeDraft:builder?structuredClone(builder):null});setFailure(null);setState("READY");return}catch(fetchReason){if(current===requestId.current)recordFailure(fetchReason);return}}recordFailure(error)}finally{actionInFlight.current=false}}
 const filtered=useMemo(()=>items.filter(item=>(filter==="ALL"||item.definition.lifecycleState===filter)&&`${item.definition.name} ${item.definition.workflowDefinitionId}`.toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
 const definition=selected?.definition,draft=definition?.revisions.find(item=>item.revisionId===definition.currentDraftRevisionId),review=definition?.reviews.at(-1),active=draft??definition?.revisions.at(-1),activeHasSkillBindings=Boolean(active?.content.tasks.some(hasSkillOperationBindings));
 const activeBindingsReviewable=operationDirectoryState==="READY"&&Boolean(active)&&active!.content.tasks.every(task=>(task.skillOperationBindings??[]).every(binding=>referenceSupportsBinding(task,binding)&&operationDirectory.some(entry=>entry.skillId===binding.skillId&&entry.skillRevisionId===binding.skillRevisionId&&entry.skillDigest===binding.skillDigest&&entry.operation.name===binding.operation)));
 const bindingValidationBlocked=activeHasSkillBindings&&!activeBindingsReviewable;
 return <main className="module-workbench resource-management"><header><p className="eyebrow">Workflow 定义工作台</p><h1>工作流中心</h1><p>编写与发布 Workflow Definition。Definition 不代表 Workflow Run、Task Run、Attempt 或任何执行状态。</p></header>
 {state==="LOADING"&&<p role="status">正在读取权威 Workflow Definition…</p>}{state==="SAVING"&&<p role="status">正在保存受治理的 Workflow Definition…</p>}{failure&&<section role="alert" aria-label={`${failure.state} state`}><h2>{failure.state}</h2><p>{failure.state==="denied"||failure.state==="not found"?"Workflow 不可用或当前访问未获授权。":failure.reason}</p><button onClick={()=>void refresh(definition?.workflowDefinitionId)}>重新读取权威数据</button></section>}
 {recovery&&<section role="alert" aria-label="Guided conflict recovery"><h2>{recovery.state}: 需要明确恢复操作</h2><dl><dt>Attempted aggregate version / 尝试的聚合版本</dt><dd>{recovery.attemptedVersion}</dd><dt>Authoritative aggregate version / 权威聚合版本</dt><dd>{recovery.authoritative.definition.aggregateVersion}</dd><dt>尝试的修订</dt><dd>{recovery.attemptedRevisionId??"NO_REVISION"}</dd><dt>权威修订</dt><dd>{recovery.authoritative.definition.revisions.at(-1)?.revisionId??"NO_REVISION"}</dd></dl><p>已只读获取权威版本。写请求不会自动重放，未保存的 Definition 输入（包括完整 Skill operation binding）会保留到你明确决定。</p>{recovery.safeDraft?<button aria-label="Explicitly reapply safe draft input" onClick={()=>{if(editorLocked())return;setBuilder(structuredClone(recovery.safeDraft!));setBuilderName(recovery.authoritative.definition.name);setRecovery(null)}}>明确恢复保留的定义输入</button>:<button onClick={()=>setRecovery(null)}>确认权威版本</button>}<button onClick={closeEditor}>放弃保留输入</button></section>}
 <section className="module-dashboard" aria-label="Workflow dashboard"><article><strong>{items.length}</strong><span>Definitions</span></article><article><strong>{items.filter(x=>x.definition.lifecycleState==="PUBLISHED").length}</strong><span>Published</span></article><article><strong>{items.reduce((sum,x)=>sum+(x.definition.revisions.at(-1)?.content.tasks.length??0),0)}</strong><span>Canonical Tasks</span></article></section>
 <section className="workbench-card workflow-operation-directory-status" aria-label="Skill operation directory status"><h2>Skill operation 目录</h2><p>{operationDirectoryState==="LOADING"?"正在读取正式目录…":operationDirectoryState==="UNAVAILABLE"?`目录不可用：${operationDirectoryReason}`:`${operationDirectory.length} 个合格 operation；${rejectedSkillCount} 个不合格或缺少 operation 的 Skill 已排除。`}</p>{operationDirectoryState==="UNAVAILABLE"&&<button type="button" onClick={()=>void loadOperationDirectory()}>重新读取 Skill operation 目录</button>}<p>只接收已发布、启用、未归档、未弃用且契约完整的 READ_ONLY operation；不会从名称或 capability 推断。</p></section>
 {builder?<section aria-label="Workflow authoring" aria-busy={savingEditor}>{savingEditor&&<p role="status">正在保存当前编写器，提交内容已锁定。离开或关闭编写器不会取消后端保存。</p>}<fieldset disabled={savingEditor} aria-label="Workflow editor fields" onChangeCapture={event=>{if(editorLocked()){event.preventDefault();event.stopPropagation()}}} onClickCapture={event=>{if(editorLocked()){event.preventDefault();event.stopPropagation()}}}><label>Workflow 名称<input value={builderName} maxLength={120} onChange={event=>{if(!editorLocked())setBuilderName(event.target.value)}}/></label><WorkflowBuilderPage content={builder} onChange={changeBuilder} isLocked={editorLocked} operationDirectory={operationDirectory} operationDirectoryState={operationDirectoryState} operationDirectoryReason={operationDirectoryReason}/><div className="module-actions"><button disabled={state!=="READY"||!builderName.trim()} onClick={()=>void save()}>Save governed Workflow draft</button></div></fieldset><button onClick={closeEditor}>关闭编写器并保留权威版本</button></section>:<section className="workbench-card resource-form" aria-label="Workflow quick authoring context"><h2>新建 Workflow Definition</h2><p>可直接打开完整编写器；已有浏览器消费者也可先提供精确 Runtime Profile 上下文。</p><label>Published Runtime Profile ID<input value={runtimeId} onChange={event=>setRuntimeId(event.target.value)}/></label><label>Published Runtime revision ID<input value={runtimeRevision} onChange={event=>setRuntimeRevision(event.target.value)}/></label><div className="module-actions"><button disabled={state!=="READY"} onClick={startCreate}>新建 Workflow Definition</button><button disabled={state!=="READY"||!runtimeId||!runtimeRevision} onClick={openWithRuntime}>Open Workflow Builder</button></div></section>}
 <div className="module-layout"><aside><h2>Workflow Catalog</h2><label>搜索定义<input aria-label="搜索 Workflow Definition" value={query} onChange={event=>{setQuery(event.target.value);preserveContext({query:event.target.value||null})}}/></label><label>生命周期筛选<select aria-label="Workflow 生命周期筛选" value={filter} onChange={event=>{setFilter(event.target.value);preserveContext({lifecycle:event.target.value==="ALL"?null:event.target.value})}}><option>ALL</option><option>DRAFT</option><option>VALIDATED</option><option>HUMAN_REVIEWED</option><option>PUBLISHED</option></select></label>{filtered.length===0&&state==="READY"?<p>没有匹配的 Workflow Definition。</p>:filtered.map(item=><button className={definition?.workflowDefinitionId===item.definition.workflowDefinitionId?"selected":""} key={item.definition.workflowDefinitionId} onClick={()=>void refresh(item.definition.workflowDefinitionId)}><strong>{item.definition.name}</strong><span>{item.definition.lifecycleState}</span></button>)}</aside>
 <section>{!definition?<div className="empty-state"><h2>选择 Workflow Definition</h2><p>DAG、精确资源绑定、digest、消费者与历史会显示在这里。</p></div>:<><header><p className="eyebrow">{definition.lifecycleState}</p><h2>{definition.name}</h2><span className="technical-value">{definition.workflowDefinitionId}</span></header>
 {active&&<section className="workbench-card"><h3>Canonical DAG</h3><p>{active.content.description||"未提供用途说明"}</p><ol>{active.content.tasks.map(task=><li key={task.taskId}><button aria-pressed={selectedTask===task.taskId} onClick={()=>setSelectedTask(task.taskId)}>{task.name}</button> · depends on {task.dependsOn.join(", ")||"nothing"} · {task.references.length} exact reference(s) · {task.skillOperationBindings?.length??0} Skill operation binding(s) · retry {task.retryLimit} · timeout {task.timeoutSeconds}s · {task.failurePolicy}</li>)}</ol>{selectedTask&&<p role="status">已选择 Definition 步骤：<span className="technical-value">{selectedTask}</span>。这不是运行状态。</p>}<section className="workflow-binding-review" aria-label="Workflow Skill operation binding review"><h3>Validate / review / publish 前绑定审查</h3>{active.content.tasks.map(task=><WorkflowSkillOperationBindingEditor key={task.taskId} task={task} readOnly directory={operationDirectory} directoryState={operationDirectoryState} directoryReason={operationDirectoryReason}/>)}<p>这里显示后端 GET 返回的实际绑定；历史无绑定版本保持未绑定，不会自动补写。</p></section><label>Exact revision digest<input readOnly value={active.digest}/></label>{draft&&<div className="module-actions"><button disabled={state!=="READY"} onClick={startEdit}>编辑当前 Draft</button>{draft.state==="DRAFT"&&<button disabled={state!=="READY"||bindingValidationBlocked} aria-describedby={bindingValidationBlocked?"workflow-skill-validation-blocked":undefined} onClick={()=>void act(x=>validateWorkflowDefinition(x.workflowDefinitionId,x.aggregateVersion))}>Validate DAG and references</button>}{draft.state==="VALIDATED"&&<button disabled={state!=="READY"} onClick={()=>void act(x=>reviewWorkflowDefinition(x.workflowDefinitionId,x.aggregateVersion,draft.digest))}>Review exact Workflow digest</button>}{draft.state==="HUMAN_REVIEWED"&&review&&<button disabled={state!=="READY"} onClick={()=>void act(x=>publishWorkflowDefinition(x.workflowDefinitionId,x.aggregateVersion,draft.digest,review.reviewId))}>Publish immutable Workflow</button>}</div>}{draft?.state==="DRAFT"&&bindingValidationBlocked&&<p id="workflow-skill-validation-blocked" role="status">正式目录尚未返回与已保存 Skill revision、digest、operation 完全一致的合格身份。Draft 会保留，但页面不会把缺失或不合格 operation 提交为已验证。</p>}<h4>Lifecycle Evidence</h4><p>Validation: {draft?.state!=="DRAFT"?"RECORDED":"REQUIRED"} · Human review: {review?.reviewId??"REQUIRED"} · Publication: {definition.publishedRevisionId??"NOT_PUBLISHED"}</p><p>绑定与发布不等于执行授权；本页不创建 Run、Task Run、Attempt、Plan 或 dispatch。</p></section>}
 {definition.publishedRevisionId&&!definition.currentDraftRevisionId&&<button disabled={state!=="READY"} onClick={()=>void act(x=>successorWorkflowDefinition(x.workflowDefinitionId,x.aggregateVersion))}>Create Workflow successor</button>}<section><h3>Relationships and consumers</h3><p>{definition.relationships.length} relationships · {definition.consumers.length} consumers</p><h3>Revision history</h3><ol>{definition.revisions.map(item=><li key={item.revisionId}>{item.state} · <span className="technical-value">{item.revisionId}</span> · digest {item.digest} · Skill operations {item.content.tasks.reduce((count,task)=>count+(task.skillOperationBindings?.length??0),0)}</li>)}</ol></section><WorkflowVersionComparison definition={definition}/><WorkflowTechnicalProjection projection={selected}/></>}</section></div></main>;
}
