import {referenceSupportsBinding,type ExactReference,type WorkflowContent,type WorkflowTask} from "../api/workflowDefinitions";
import type {WorkflowSkillOperationEntry} from "../api/workflowSkillOperations";
import {WorkflowSkillOperationBindingEditor} from "./WorkflowSkillOperationBindingEditor";

const kinds: ExactReference["kind"][] = ["AGENT", "SKILL", "MCP", "KNOWLEDGE", "RUNTIME_PROFILE"];
const csv = (value: string) => value.split(",").map(item => item.trim()).filter(Boolean);
const emptyTask = (index: number): WorkflowTask => ({taskId:`step-${index}`,name:"",dependsOn:[],inputs:[],outputs:[],capabilityRequirements:[],references:[],retryLimit:0,timeoutSeconds:300,failurePolicy:"FAIL_WORKFLOW"});

export function WorkflowBuilderPage({content,onChange,operationDirectory=[],operationDirectoryState="UNAVAILABLE",operationDirectoryReason,isLocked=()=>false}:{content:WorkflowContent;onChange:(value:WorkflowContent)=>void;operationDirectory?:WorkflowSkillOperationEntry[];operationDirectoryState?:"LOADING"|"READY"|"UNAVAILABLE";operationDirectoryReason?:string|null;isLocked?:()=>boolean}){
  const updateTask=(index:number,patch:Partial<WorkflowTask>)=>{if(isLocked())return;onChange({...content,tasks:content.tasks.map((task,position)=>position===index?{...task,...patch}:task)})};
  const updateReference=(taskIndex:number,referenceIndex:number,patch:Partial<ExactReference>)=>updateTask(taskIndex,{references:content.tasks[taskIndex].references.map((reference,index)=>index===referenceIndex?{...reference,...patch}:reference)});
  return <section className="workbench-card resource-form" aria-label="Workflow Builder">
    <header><p className="eyebrow">Definition Builder</p><h3>Workflow Definition 编写器</h3><p>这里保存定义，不创建 Workflow Run、Task Run 或 Attempt。</p></header>
    <label>用途说明<textarea value={content.description} onChange={event=>onChange({...content,description:event.target.value})}/></label>
    <div className="resource-form-grid"><label>Workflow 输入（逗号分隔）<input value={content.inputs.join(", ")} onChange={event=>onChange({...content,inputs:csv(event.target.value)})}/></label><label>Workflow 输出（逗号分隔）<input value={content.outputs.join(", ")} onChange={event=>onChange({...content,outputs:csv(event.target.value)})}/></label></div>
    <fieldset><legend>精确 Runtime Profile 绑定</legend><label>资源 ID<input value={content.runtimeProfile.resourceId} onChange={event=>onChange({...content,runtimeProfile:{...content.runtimeProfile,resourceId:event.target.value}})}/></label><label>修订 ID<input value={content.runtimeProfile.revisionId} onChange={event=>onChange({...content,runtimeProfile:{...content.runtimeProfile,revisionId:event.target.value}})}/></label></fieldset>
    {content.tasks.map((task,index)=><fieldset key={`${index}-${task.taskId}`}><legend>步骤 {index+1}</legend>
      <label>步骤 ID<input value={task.taskId} pattern="[a-z][a-z0-9-]{0,62}" onChange={event=>updateTask(index,{taskId:event.target.value})}/></label><label>名称<input value={task.name} onChange={event=>updateTask(index,{name:event.target.value})}/></label>
      <label>依赖步骤 ID（逗号分隔）<input value={task.dependsOn.join(", ")} onChange={event=>updateTask(index,{dependsOn:csv(event.target.value)})}/></label><label>能力要求（逗号分隔）<input value={task.capabilityRequirements.join(", ")} onChange={event=>updateTask(index,{capabilityRequirements:csv(event.target.value)})}/></label>
      <label>输入（逗号分隔）<input value={task.inputs.join(", ")} onChange={event=>updateTask(index,{inputs:csv(event.target.value)})}/></label><label>输出（逗号分隔）<input value={task.outputs.join(", ")} onChange={event=>updateTask(index,{outputs:csv(event.target.value)})}/></label>
      <label>重试上限<input type="number" min="0" max="10" value={task.retryLimit} onChange={event=>updateTask(index,{retryLimit:Number(event.target.value)})}/></label><label>超时秒数<input type="number" min="1" max="86400" value={task.timeoutSeconds} onChange={event=>updateTask(index,{timeoutSeconds:Number(event.target.value)})}/></label>
      <label>失败策略<select value={task.failurePolicy} onChange={event=>updateTask(index,{failurePolicy:event.target.value as WorkflowTask["failurePolicy"]})}><option value="FAIL_WORKFLOW">FAIL_WORKFLOW</option><option value="SKIP_DEPENDENTS">SKIP_DEPENDENTS</option></select></label>
      <div className="resource-reference-list"><strong>步骤资源引用</strong><p>通用资源引用不会自动创建 Skill operation binding。</p>{task.references.map((reference,referenceIndex)=>{const protectsBinding=task.skillOperationBindings?.some(binding=>referenceSupportsBinding(task,binding)&&reference.kind==="SKILL"&&reference.resourceId===binding.skillId&&reference.revisionId===binding.skillRevisionId);return <div className="resource-reference" key={referenceIndex}><label>类型<select value={reference.kind} disabled={protectsBinding} onChange={event=>updateReference(index,referenceIndex,{kind:event.target.value as ExactReference["kind"]})}>{kinds.map(kind=><option key={kind}>{kind}</option>)}</select></label><label>资源 ID<input value={reference.resourceId} readOnly={protectsBinding} onChange={event=>updateReference(index,referenceIndex,{resourceId:event.target.value})}/></label><label>修订 ID<input value={reference.revisionId} readOnly={protectsBinding} onChange={event=>updateReference(index,referenceIndex,{revisionId:event.target.value})}/></label><label>Digest（可选）<input value={reference.digest??""} readOnly={protectsBinding} onChange={event=>updateReference(index,referenceIndex,{digest:event.target.value||null})}/></label><button type="button" disabled={protectsBinding} title={protectsBinding?"当前契约不支持仅删除已有 Skill operation binding":""} onClick={()=>updateTask(index,{references:task.references.filter((_,position)=>position!==referenceIndex)})}>移除此引用</button></div>})}<button type="button" onClick={()=>updateTask(index,{references:[...task.references,{kind:"SKILL",resourceId:"",revisionId:""}]})}>添加精确资源引用</button></div>
      <WorkflowSkillOperationBindingEditor task={task} isLocked={isLocked} directory={operationDirectory} directoryState={operationDirectoryState} directoryReason={operationDirectoryReason} onChange={value=>updateTask(index,value)}/>
      <button type="button" disabled={content.tasks.length===1} onClick={()=>onChange({...content,tasks:content.tasks.filter((_,position)=>position!==index)})}>移除此步骤</button>
    </fieldset>)}
    <button type="button" onClick={()=>onChange({...content,tasks:[...content.tasks,emptyTask(content.tasks.length+1)]})}>添加步骤</button>
  </section>;
}
