import {useState} from "react";
import {referenceSupportsBinding,type ExactReference,type WorkflowContent,type WorkflowTask} from "../api/workflowDefinitions";
import type {WorkflowSkillOperationEntry} from "../api/workflowSkillOperations";
import {WorkflowSkillOperationBindingEditor} from "./WorkflowSkillOperationBindingEditor";

const kinds:ExactReference["kind"][]=["AGENT","SKILL","MCP","KNOWLEDGE","RUNTIME_PROFILE"];
const csv=(value:string)=>value.split(",").map(item=>item.trim()).filter(Boolean);
const referenceIdentity=(reference:ExactReference)=>`${reference.kind}:${reference.resourceId}:${reference.revisionId}:${reference.digest??"NO_DIGEST"}`;

export function WorkflowNodeForm({task,content,onUpdate,onRename,onRemove,directory,directoryState,directoryReason,isLocked}:{task:WorkflowTask;content:WorkflowContent;onUpdate:(task:WorkflowTask)=>void;onRename:(nextId:string)=>void;onRemove:()=>void;directory:WorkflowSkillOperationEntry[];directoryState:"LOADING"|"READY"|"UNAVAILABLE";directoryReason?:string|null;isLocked:()=>boolean}){
  const [confirmDelete,setConfirmDelete]=useState(false);
  const [pendingDependency,setPendingDependency]=useState<{taskId:string;remove:boolean}|null>(null);
  const dependents=content.tasks.filter(candidate=>candidate.dependsOn.includes(task.taskId));
  const safeId=task.taskId.replace(/[^a-zA-Z0-9_-]/g,"_");
  const patch=(value:Partial<WorkflowTask>)=>{if(!isLocked())onUpdate({...task,...value})};
  function updateReference(target:ExactReference,value:Partial<ExactReference>){patch({references:task.references.map(reference=>reference===target?{...reference,...value}:reference)})}
  return <section className="workflow-designer__node-form resource-form" aria-label={`步骤 ${task.taskId} 配置`}>
    <header><div><p className="eyebrow">当前节点</p><h3>{task.name||"未命名步骤"}</h3><code>{task.taskId}</code></div><button type="button" className="workflow-secondary-action" onClick={()=>{document.querySelector<HTMLButtonElement>(`[data-workflow-node="${CSS.escape(`editor:${task.taskId}`)}"]`)?.focus()}}>返回画布节点</button></header>
    <fieldset className="workflow-designer__form-section"><legend>基本信息</legend><div className="resource-form-grid"><label>步骤 ID<input id={`workflow-task-${safeId}-taskId`} value={task.taskId} pattern="[a-z][a-z0-9-]{0,62}" onChange={event=>{if(!isLocked())onRename(event.target.value)}}/></label><label>名称<input id={`workflow-task-${safeId}-name`} value={task.name} maxLength={120} onChange={event=>patch({name:event.target.value})}/></label></div><label>能力要求（逗号分隔）<input value={task.capabilityRequirements.join(", ")} onChange={event=>patch({capabilityRequirements:csv(event.target.value)})}/></label></fieldset>
    <fieldset className="workflow-designer__form-section"><legend>输入与输出</legend><div className="resource-form-grid"><label>输入（逗号分隔）<input value={task.inputs.join(", ")} onChange={event=>patch({inputs:csv(event.target.value)})}/></label><label>输出（逗号分隔）<input value={task.outputs.join(", ")} onChange={event=>patch({outputs:csv(event.target.value)})}/></label></div></fieldset>
    <section className="workflow-designer__form-section workflow-designer__resource-editor" aria-labelledby={`workflow-task-${safeId}-resources`}><h4 id={`workflow-task-${safeId}-resources`}>资源绑定</h4><p>保留正式 GET 返回的 resource ID、revision 与 digest；通用引用不会自动创建 operation binding。</p><div className="resource-reference-list">{task.references.map(reference=>{const protectsBinding=task.skillOperationBindings?.some(binding=>referenceSupportsBinding(task,binding)&&reference.kind==="SKILL"&&reference.resourceId===binding.skillId&&reference.revisionId===binding.skillRevisionId);return <div className="resource-reference" key={referenceIdentity(reference)}><label>类型<select value={reference.kind} disabled={protectsBinding} onChange={event=>updateReference(reference,{kind:event.target.value as ExactReference["kind"]})}>{kinds.map(kind=><option key={kind}>{kind}</option>)}</select></label><label>资源 ID<input value={reference.resourceId} readOnly={protectsBinding} onChange={event=>updateReference(reference,{resourceId:event.target.value})}/></label><label>修订 ID<input value={reference.revisionId} readOnly={protectsBinding} onChange={event=>updateReference(reference,{revisionId:event.target.value})}/></label><label>Digest（可选）<input value={reference.digest??""} readOnly={protectsBinding} onChange={event=>updateReference(reference,{digest:event.target.value||null})}/></label><button type="button" disabled={protectsBinding} title={protectsBinding?"当前契约不支持仅删除已有 Skill operation binding":""} onClick={()=>patch({references:task.references.filter(candidate=>candidate!==reference)})}>移除此引用</button></div>})}<button type="button" onClick={()=>patch({references:[...task.references,{kind:"SKILL",resourceId:"",revisionId:""}]})}>添加精确资源引用</button></div><WorkflowSkillOperationBindingEditor task={task} isLocked={isLocked} directory={directory} directoryState={directoryState} directoryReason={directoryReason} onChange={onUpdate}/></section>
    <fieldset className="workflow-designer__form-section" id={`workflow-task-${safeId}-dependsOn`}><legend>依赖关系</legend><p>这里直接编辑正式 <code>dependsOn</code>。每次变更都会先展示实际影响。</p>{content.tasks.filter(candidate=>candidate.taskId!==task.taskId).map(candidate=>{const checked=task.dependsOn.includes(candidate.taskId);return <label className="workflow-designer__dependency" key={candidate.taskId}><input type="checkbox" checked={checked} onChange={()=>setPendingDependency({taskId:candidate.taskId,remove:checked})}/><span><strong>{candidate.name||candidate.taskId}</strong><code>{candidate.taskId}</code></span></label>})}{task.dependsOn.filter(id=>!content.tasks.some(candidate=>candidate.taskId===id)).map((id,occurrence)=><div className="workflow-designer__invalid-dependency" key={`${id}:${occurrence}`}><span>无效目标：<code>{id}</code></span><button type="button" onClick={()=>setPendingDependency({taskId:id,remove:true})}>移除无效依赖</button></div>)}{pendingDependency&&<div className="workflow-designer__dependency-impact" role="alert"><strong>{pendingDependency.remove?"移除":"新增"}直接依赖 {pendingDependency.taskId}</strong><p>{pendingDependency.remove?`${task.taskId} 将不再等待 ${pendingDependency.taskId}；不会自动连接其上游，也不改变其他依赖、资源或 binding。`:`${task.taskId} 将直接依赖 ${pendingDependency.taskId}；可能形成环路，后端仍会权威校验。其他字段不变。`}</p><button type="button" onClick={()=>{patch({dependsOn:pendingDependency.remove?task.dependsOn.filter(id=>id!==pendingDependency.taskId):[...task.dependsOn,pendingDependency.taskId]});setPendingDependency(null)}}>确认依赖变更</button><button type="button" onClick={()=>setPendingDependency(null)}>取消依赖变更</button></div>}</fieldset>
    <details className="workflow-designer__form-section workflow-designer__advanced" open><summary>执行策略</summary><div className="resource-form-grid"><label>重试上限<input type="number" min="0" max="10" value={task.retryLimit} onChange={event=>patch({retryLimit:Number(event.target.value)})}/></label><label>超时秒数<input type="number" min="1" max="86400" value={task.timeoutSeconds} onChange={event=>patch({timeoutSeconds:Number(event.target.value)})}/></label></div><label>失败策略<select value={task.failurePolicy} onChange={event=>patch({failurePolicy:event.target.value as WorkflowTask["failurePolicy"]})}><option value="FAIL_WORKFLOW">FAIL_WORKFLOW</option><option value="SKIP_DEPENDENTS">SKIP_DEPENDENTS</option></select></label></details>
    <section className="workflow-designer__danger-zone"><h4>删除步骤</h4>{!confirmDelete?<button type="button" disabled={content.tasks.length===1} onClick={()=>setConfirmDelete(true)}>检查并移除此步骤</button>:<div role="alert"><strong>此操作会删除步骤 {task.taskId}</strong><p>{dependents.length?`并从 ${dependents.map(item=>item.taskId).join("、")} 的 dependsOn 中移除此 ID。`:"没有其他步骤依赖它。"} 其他步骤的 references 与 bindings 不会改变。</p><button type="button" onClick={onRemove}>确认删除步骤及上述依赖</button><button type="button" onClick={()=>setConfirmDelete(false)}>取消</button></div>}</section>
  </section>;
}
